# Generated by Django 4.2.6 on 2023-12-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=320)),
                ("data", models.JSONField(default=True)),
                ("active", models.BooleanField()),
            ],
        ),
    ]
