# Generated by Django 4.2.6 on 2023-12-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
