# Generated by Django 4.2.11 on 2024-05-29 14:40

import configuration.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0002_alter_configuration_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="data",
            field=configuration.fields.OrderedJSONField(default=dict),
        ),
    ]
