from .base import ConfigurationData
from screener.models import WhiteLabel


class MaConfigurationData(ConfigurationData):
    @classmethod
    def get_white_label(self) -> WhiteLabel:
        return WhiteLabel.objects.get(code="ma")

    state = {"name": "Massachusetts"}

    public_charge_rule = {
        "link": "https://www.mass.gov/info-details/information-about-the-public-charge-rule-and-how-it-may-impact-you#information-about-the-public-charge-rule-",
        "text": {
            "_label": "landingPage.publicChargeLinkMA",
            "_default_message": "Massachusetts Department of Health and Human Services website",
        },
    }

    more_help_options = {
        "moreHelpOptions": [
            {
                "name": {"_label": "moreHelp.ma.211.name", "_default_message": "Mass 211"},
                "phone": {"_label": "moreHelp.ma.211.phone", "_default_message": "Dial 2-1-1 or 877.211.6277"},
                "link": "https://mass211.org/",
            },
            {
                "name": {"_label": "moreHelp.ma.masscap.name", "_default_message": "MASSCAP Community Action Agencies"},
                "description": {
                    "_label": "moreHelp.ma.masscap.phone",
                    "_default_message": "Your local community action agency may be able to connect you to other resources and support services. Find an agency near you.",
                },
                "link": "https://www.masscap.org/agencies/",
            },
        ]
    }

    acute_condition_options = {
        "food": {
            "icon": {"_icon": "Food", "_classname": "option-card-icon"},
            "text": {
                "_label": "acuteConditionOptions.food",
                "_default_message": "Food or groceries",
            },
        },
        "babySupplies": {
            "icon": {"_icon": "Baby_supplies", "_classname": "option-card-icon"},
            "text": {
                "_label": "acuteConditionOptions.babySupplies",
                "_default_message": "Diapers and other baby supplies",
            },
        },
        "housing": {
            "icon": {"_icon": "Housing", "_classname": "option-card-icon"},
            "text": {
                "_label": "acuteConditionOptions.housing",
                "_default_message": "Help with managing your mortgage, rent, or utilities",
            },
        },
        "support": {
            "icon": {"_icon": "Support", "_classname": "option-card-icon"},
            "text": {
                "_label": "acuteConditionOptions.support",
                "_default_message": "A challenge you or your child would like to talk about",
            },
        },
        "childDevelopment": {
            "icon": {"_icon": "Child_development", "_classname": "option-card-icon"},
            "text": {
                "_label": "acuteConditionOptions.childDevelopment",
                "_default_message": "Concern about your child's development",
            },
        },
        "familyPlanning": {
            "icon": {"_icon": "Family_planning", "_classname": "option-card-icon"},
            "text": {
                "_label": "acuteConditionOptions.familyPlanning",
                "_default_message": "Family planning or birth control",
            },
        },
        "jobResources": {
            "icon": {"_icon": "Job_resources", "_classname": "option-card-icon"},
            "text": {
                "_label": "acuteConditionOptions.jobResources",
                "_default_message": "Finding a job",
            },
        },
        "dentalCare": {
            "icon": {"_icon": "Dental_care", "_classname": "option-card-icon"},
            "text": {
                "_label": "acuteConditionOptions.dentalCare",
                "_default_message": "Low-cost dental care",
            },
        },
        "legalServices": {
            "icon": {"_icon": "Legal_services", "_classname": "option-card-icon"},
            "text": {
                "_label": "acuteConditionOptions.legalServices",
                "_default_message": "Free or low-cost help with civil legal needs or identity documents",
            },
        },
        "veteranServices": {
            "icon": {"_icon": "Military", "_classname": "option-card-icon"},
            "text": {
                "_label": "acuteConditionOptions.veteranServices",
                "_default_message": "Resources for veterans and their families",
            },
        },
    }

    sign_up_options = {
        "sendUpdates": {
            "_label": "signUpOptions.sendUpdates",
            "_default_message": "Please notify me when new benefits become available to me that I am likely eligible for based on the information I have provided.",
        },
        "sendOffers": {
            "_label": "signUpOptions.sendOffers",
            "_default_message": "Please notify me when there are paid opportunities to provide feedback on MyFriendBen.",
        },
    }

    relationship_options = {
        "child": {"_label": "relationshipOptions.child", "_default_message": "Child"},
        "fosterChild": {
            "_label": "relationshipOptions.fosterChildOrKinshipChild.ma",
            "_default_message": "Foster Child / Kinship-Guardianship Care",
        },
        "stepChild": {"_label": "relationshipOptions.stepChild", "_default_message": "Step-child"},
        "grandChild": {"_label": "relationshipOptions.grandChild", "_default_message": "Grandchild"},
        "spouse": {"_label": "relationshipOptions.spouse", "_default_message": "Spouse"},
        "parent": {"_label": "relationshipOptions.parent", "_default_message": "Parent"},
        "fosterParent": {"_label": "relationshipOptions.fosterParent", "_default_message": "Foster Parent"},
        "stepParent": {"_label": "relationshipOptions.stepParent", "_default_message": "Step-parent"},
        "grandParent": {"_label": "relationshipOptions.grandParent", "_default_message": "Grandparent"},
        "sisterOrBrother": {"_label": "relationshipOptions.sisterOrBrother", "_default_message": "Sister/Brother"},
        "stepSisterOrBrother": {
            "_label": "relationshipOptions.stepSisterOrBrother",
            "_default_message": "Step-sister/Step-brother",
        },
        "boyfriendOrGirlfriend": {
            "_label": "relationshipOptions.boyfriendOrGirlfriend",
            "_default_message": "Boyfriend/Girlfriend",
        },
        "domesticPartner": {"_label": "relationshipOptions.domesticPartner", "_default_message": "Domestic Partner"},
        "relatedOther": {"_label": "relationshipOptions.relatedOther", "_default_message": "Related in some other way"},
    }

    referral_options = {
        "bch": "Boston Children's Hospital",
        "socialMedia": {"_label": "referralOptions.socialMedia", "_default_message": "Social Media"},
        "friend": {"_label": "referralOptions.friend", "_default_message": "Friend / Family / Word of Mouth"},
        "other": {"_label": "referralOptions.other", "_default_message": "Other"},
        "testOrProspect": {
            "_label": "referralOptions.testOrProspect",
            "_default_message": "Test / Prospective Partner",
        },
    }

    language_options = {
        "en-us": "English",
        "es": "Español",
        "vi": "Tiếng Việt",
        "fr": "Français",
        "am": "አማርኛ",
        "so": "Soomaali",
        "ru": "Русский",
        "ne": "नेपाली",
        "my": "မြန်မာဘာသာစကား",
        "zh-hans": "中文 (简体)",
        "ar": "عربي",
        "sw": "Kiswahili",
    }

    income_options = {
        "wages": {"_label": "incomeOptions.wages", "_default_message": "Wages, salaries, tips"},
        "selfEmployment": {
            "_label": "incomeOptions.selfEmployment",
            "_default_message": "Income from freelance, independent contractor, or self-employment work",
        },
        "sSDisability": {
            "_label": "incomeOptions.sSDisability",
            "_default_message": "Social Security Disability Benefits",
        },
        "sSRetirement": {
            "_label": "incomeOptions.sSRetirement",
            "_default_message": "Social Security Retirement Benefits",
        },
        "sSI": {"_label": "incomeOptions.sSI", "_default_message": "Supplemental Security Income (SSI)"},
        "childSupport": {"_label": "incomeOptions.childSupport", "_default_message": "Child Support (Received)"},
        "pension": {
            "_label": "incomeOptions.pension.ma",
            "_default_message": "Military, Government, or Private Pension",
        },
        "veteran": {"_label": "incomeOptions.veteran", "_default_message": "Veteran's Pension or Benefits"},
        "sSSurvivor": {
            "_label": "incomeOptions.sSSurvivor",
            "_default_message": "Social Security Survivor's Benefits (Widowed)",
        },
        "unemployment": {"_label": "incomeOptions.unemployment", "_default_message": "Unemployment Benefits"},
        "sSDependent": {
            "_label": "incomeOptions.sSDependent",
            "_default_message": "Social Security Dependent Benefits (retirement, disability, or survivors)",
        },
        "cashAssistance": {
            "_label": "incomeOptions.cashAssistance.ma",
            "_default_message": "Government Cash Assistance (including TAFDC and EAEDC)",
        },
        "gifts": {"_label": "incomeOptions.gifts", "_default_message": "Gifts/Contributions (Received)"},
        "investment": {
            "_label": "incomeOptions.investment",
            "_default_message": "Investment Income (interest, dividends, and profit from selling stocks)",
        },
        "stateDisability": {
            "_label": "incomeOptions.stateDisability.ma",
            "_default_message": "State Disability Benefits",
        },
        "rental": {"_label": "incomeOptions.rental", "_default_message": "Rental Income"},
        "alimony": {"_label": "incomeOptions.alimony", "_default_message": "Alimony (Received)"},
        "deferredComp": {
            "_label": "incomeOptions.deferredComp",
            "_default_message": "Withdrawals from Deferred Compensation (IRA, Keogh, etc.)",
        },
        "workersComp": {"_label": "incomeOptions.workersComp", "_default_message": "Worker's Compensation"},
        "boarder": {"_label": "incomeOptions.boarder", "_default_message": "Boarder or Lodger"},
    }

    health_insurance_options = {
        "you": {
            "none": {
                "icon": {"_icon": "None", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.none-dont-know-I",
                    "_default_message": "I don't have or know if I have health insurance",
                },
            },
            "employer": {
                "icon": {"_icon": "Employer", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.employer",
                    "_default_message": "Employer-provided health insurance",
                },
            },
            "private": {
                "icon": {"_icon": "PrivateInsurance", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.private",
                    "_default_message": "Private (student or non-employer) health insurance",
                },
            },
            "mass_health": {
                "icon": {"_icon": "Medicaid", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.mass_health",
                    "_default_message": "MassHealth",
                },
            },
            "medicare": {
                "icon": {"_icon": "Medicare", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.medicare",
                    "_default_message": "Medicare",
                },
            },
            "va": {
                "icon": {"_icon": "VA", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.va",
                    "_default_message": "VA health care benefits",
                },
            },
        },
        "them": {
            "none": {
                "icon": {"_icon": "None", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.none-dont-know-they",
                    "_default_message": "They don't have or know if they have health insurance",
                },
            },
            "employer": {
                "icon": {"_icon": "Employer", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.employer",
                    "_default_message": "Employer-provided health insurance",
                },
            },
            "private": {
                "icon": {"_icon": "PrivateInsurance", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.private",
                    "_default_message": "Private (student or non-employer) health insurance",
                },
            },
            "mass_health": {
                "icon": {"_icon": "Medicaid", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.mass_health",
                    "_default_message": "MassHealth",
                },
            },
            "medicare": {
                "icon": {"_icon": "Medicare", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.medicare",
                    "_default_message": "Medicare",
                },
            },
            "va": {
                "icon": {"_icon": "VA", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.va",
                    "_default_message": "VA health care benefits",
                },
            },
        },
    }

    frequency_options = {
        "weekly": {"_label": "frequencyOptions.weekly", "_default_message": "every week"},
        "biweekly": {"_label": "frequencyOptions.biweekly", "_default_message": "every 2 weeks"},
        "semimonthly": {"_label": "frequencyOptions.semimonthly", "_default_message": "twice a month"},
        "monthly": {"_label": "frequencyOptions.monthly", "_default_message": "every month"},
        "hourly": {"_label": "frequencyOptions.hourly", "_default_message": "hourly"},
    }

    expense_options = {
        "rent": {"_label": "expenseOptions.nonSubidizedRent", "_default_message": "Rent (Non-Subsidized)"},
        "subsidizedRent": {
            "_label": "expenseOptions.subidizedRent",
            "_default_message": "Rent (Public / Subidized Housing)",
        },
        "telephone": {"_label": "expenseOptions.telephone", "_default_message": "Telephone"},
        "internet": {"_label": "expenseOptions.internet", "_default_message": "Internet"},
        "otherUtilities": {"_label": "expenseOptions.otherUtilities", "_default_message": "Other Utilities"},
        "heating": {"_label": "expenseOptions.heating", "_default_message": "Heating"},
        "mortgage": {"_label": "expenseOptions.mortgage", "_default_message": "Mortgage"},
        "propertyTax": {"_label": "expenseOptions.propertyTax", "_default_message": "Property Taxes"},
        "hoa": {"_label": "expenseOptions.hoa", "_default_message": "Homeowners or Condo Association Fees and Dues"},
        "homeownersInsurance": {
            "_label": "expenseOptions.homeownersInsurance",
            "_default_message": "Homeowners Insurance",
        },
        "medical": {"_label": "expenseOptions.medical", "_default_message": "Medical Insurance Premium &/or Bills"},
        "cooling": {"_label": "expenseOptions.cooling", "_default_message": "Cooling"},
        "childCare": {"_label": "expenseOptions.childCare", "_default_message": "Child Care"},
        "childSupport": {"_label": "expenseOptions.childSupport", "_default_message": "Child Support (Paid)"},
        "dependentCare": {"_label": "expenseOptions.dependentCare", "_default_message": "Dependent Care"},
    }

    condition_options = {
        "you": {
            "student": {
                "icon": {"_icon": "Student", "_classname": "option-card-icon"},
                "text": {
                    "_label": "conditionOptions.student",
                    "_default_message": "Student at a college, university, or other post-secondary institution like a job-training program",
                },
            },
            "pregnant": {
                "icon": {"_icon": "Pregnant", "_classname": "option-card-icon"},
                "text": {
                    "_label": "conditionOptions.pregnant",
                    "_default_message": "Pregnant",
                },
            },
            "blindOrVisuallyImpaired": {
                "icon": {"_icon": "BlindOrVisuallyImpaired", "_classname": "option-card-icon"},
                "text": {
                    "_label": "conditionOptions.blindOrVisuallyImpaired",
                    "_default_message": "Blind or visually impaired",
                },
            },
            "disabled": {
                "icon": {"_icon": "Disabled", "_classname": "option-card-icon"},
                "text": {
                    "_label": "conditionOptions.disabled",
                    "_default_message": "Currently have any disabilities that make you unable to work now or in the future",
                },
            },
            "longTermDisability": {
                "icon": {"_icon": "LongTermDisability", "_classname": "option-card-icon"},
                "text": {
                    "_label": "conditionOptions.longTermDisability",
                    "_default_message": "Any medical or developmental condition that has lasted, or is expected to last, more than 12 months",
                },
            },
        },
        "them": {
            "student": {
                "icon": {"_icon": "Student", "_classname": "option-card-icon"},
                "text": {
                    "_label": "conditionOptions.student",
                    "_default_message": "Student at a college, university, or other post-secondary institution like a job-training program",
                },
            },
            "pregnant": {
                "icon": {"_icon": "Pregnant", "_classname": "option-card-icon"},
                "text": {
                    "_label": "conditionOptions.pregnant",
                    "_default_message": "Pregnant",
                },
            },
            "blindOrVisuallyImpaired": {
                "icon": {"_icon": "BlindOrVisuallyImpaired", "_classname": "option-card-icon"},
                "text": {
                    "_label": "conditionOptions.blindOrVisuallyImpaired",
                    "_default_message": "Blind or visually impaired",
                },
            },
            "disabled": {
                "icon": {"_icon": "Disabled", "_classname": "option-card-icon"},
                "text": {
                    "_label": "conditionOptions.disabled.them",
                    "_default_message": "Currently have any disabilities that make them unable to work now or in the future",
                },
            },
            "longTermDisability": {
                "icon": {"_icon": "LongTermDisability", "_classname": "option-card-icon"},
                "text": {
                    "_label": "conditionOptions.longTermDisability",
                    "_default_message": "Any medical or developmental condition that has lasted, or is expected to last, more than 12 months",
                },
            },
        },
    }

    # NOTE: MA is city based for most of their benefits, so we ask for the city instead of the county.
    # SOURCE: https://docs.google.com/spreadsheets/d/12gh3m7HAdMiZ5VHnwYFEH49y1XWbgxRid7o_1lIu64I/edit?gid=602393352#gid=602393352
    counties_by_zipcode = {
        "01001": {"Agawam": "Agawam"},
        "01002": {"Amherst": "Amherst", "Shutesbury": "Shutesbury"},
        "01003": {"Amherst": "Amherst"},
        "01004": {"Amherst": "Amherst"},
        "01005": {"Barre": "Barre"},
        "01007": {"Belchertown": "Belchertown"},
        "01008": {"Blandford": "Blandford", "Otis": "Otis"},
        "01009": {"Palmer": "Palmer"},
        "01010": {"Warren": "Warren", "Brimfield": "Brimfield"},
        "01011": {"Middlefield": "Middlefield", "Chester": "Chester"},
        "01012": {"Chesterfield": "Chesterfield"},
        "01013": {"Chicopee": "Chicopee"},
        "01014": {"Chicopee": "Chicopee"},
        "01020": {"Chicopee": "Chicopee"},
        "01021": {"Chicopee": "Chicopee"},
        "01022": {"Chicopee": "Chicopee"},
        "01026": {"Cummington": "Cummington", "Windsor": "Windsor"},
        "01027": {"Westhampton": "Westhampton"},
        "01028": {"East Longmeadow": "East Longmeadow"},
        "01029": {"Otis": "Otis"},
        "01030": {"Agawam": "Agawam"},
        "01031": {"Hardwick": "Hardwick"},
        "01032": {"Goshen": "Goshen"},
        "01033": {"Granby": "Granby"},
        "01034": {"Granville": "Granville"},
        "01035": {"Hadley": "Hadley"},
        "01036": {"Hampden": "Hampden"},
        "01037": {"Hardwick": "Hardwick"},
        "01038": {"Hatfield": "Hatfield"},
        "01039": {"Williamsburg": "Williamsburg", "Whately": "Whately"},
        "01040": {"Holyoke": "Holyoke"},
        "01041": {"Holyoke": "Holyoke"},
        "01050": {"Chester": "Chester", "Huntington": "Huntington"},
        "01053": {"Northampton": "Northampton"},
        "01054": {"Leverett": "Leverett"},
        "01056": {"Ludlow": "Ludlow"},
        "01057": {"Monson": "Monson"},
        "01059": {"Amherst": "Amherst"},
        "01060": {"Northampton": "Northampton"},
        "01061": {"Northampton": "Northampton"},
        "01062": {"Northampton": "Northampton"},
        "01063": {"Northampton": "Northampton"},
        "01066": {"Hatfield": "Hatfield"},
        "01068": {"Oakham": "Oakham"},
        "01069": {"Palmer": "Palmer"},
        "01070": {"Plainfield": "Plainfield"},
        "01071": {"Russell": "Russell"},
        "01072": {"Shutesbury": "Shutesbury"},
        "01073": {"Southampton": "Southampton"},
        "01074": {"Barre": "Barre"},
        "01075": {"South Hadley": "South Hadley"},
        "01077": {"Southwick": "Southwick"},
        "01079": {"Palmer": "Palmer"},
        "01080": {"Palmer": "Palmer"},
        "01081": {"Wales": "Wales"},
        "01082": {"Hardwick": "Hardwick", "Ware": "Ware"},
        "01083": {"Warren": "Warren"},
        "01084": {"Chesterfield": "Chesterfield"},
        "01085": {"Westfield": "Westfield"},
        "01086": {"Westfield": "Westfield"},
        "01088": {"Hatfield": "Hatfield"},
        "01089": {"West Springfield": "West Springfield"},
        "01090": {"West Springfield": "West Springfield"},
        "01092": {"Warren": "Warren"},
        "01093": {"Whately": "Whately"},
        "01094": {"Hardwick": "Hardwick"},
        "01095": {"Wilbraham": "Wilbraham"},
        "01096": {"Ashfield": "Ashfield", "Williamsburg": "Williamsburg"},
        "01097": {"Russell": "Russell"},
        "01098": {"Worthington": "Worthington"},
        "01101": {"Springfield": "Springfield"},
        "01102": {"Springfield": "Springfield"},
        "01103": {"Springfield": "Springfield"},
        "01104": {"Springfield": "Springfield"},
        "01105": {"Springfield": "Springfield"},
        "01106": {"Longmeadow": "Longmeadow"},
        "01107": {"Springfield": "Springfield"},
        "01108": {"Springfield": "Springfield"},
        "01109": {"Springfield": "Springfield"},
        "01111": {"Springfield": "Springfield"},
        "01114": {"Springfield": "Springfield"},
        "01115": {"Springfield": "Springfield"},
        "01116": {"East Longmeadow": "East Longmeadow"},
        "01118": {"Springfield": "Springfield"},
        "01119": {"Springfield": "Springfield"},
        "01128": {"Springfield": "Springfield"},
        "01129": {"Springfield": "Springfield"},
        "01138": {"Springfield": "Springfield"},
        "01139": {"Springfield": "Springfield"},
        "01144": {"Springfield": "Springfield"},
        "01151": {"Springfield": "Springfield"},
        "01152": {"Springfield": "Springfield"},
        "01189": {"West Springfield": "West Springfield"},
        "01199": {"Springfield": "Springfield"},
        "01201": {"Pittsfield": "Pittsfield"},
        "01202": {"Pittsfield": "Pittsfield"},
        "01203": {"Pittsfield": "Pittsfield"},
        "01220": {"Adams": "Adams"},
        "01222": {"Sheffield": "Sheffield"},
        "01223": {"Becket": "Becket"},
        "01224": {"Lanesborough": "Lanesborough"},
        "01225": {"Cheshire": "Cheshire"},
        "01226": {"Dalton": "Dalton"},
        "01227": {"Dalton": "Dalton"},
        "01229": {"Stockbridge": "Stockbridge"},
        "01230": {"Great Barrington": "Great Barrington"},
        "01235": {"Peru": "Peru", "Middlefield": "Middlefield"},
        "01236": {"West Stockbridge": "West Stockbridge"},
        "01237": {"Lanesborough": "Lanesborough"},
        "01238": {"Lee": "Lee"},
        "01240": {"Lenox": "Lenox"},
        "01242": {"Lenox": "Lenox"},
        "01243": {"Middlefield": "Middlefield"},
        "01244": {"New Marlborough": "New Marlborough"},
        "01245": {"Monterey": "Monterey"},
        "01247": {"Monroe": "Monroe", "North Adams": "North Adams"},
        "01252": {"Egremont": "Egremont"},
        "01253": {"Otis": "Otis"},
        "01254": {"Richmond": "Richmond"},
        "01255": {"Sandisfield": "Sandisfield"},
        "01256": {"Savoy": "Savoy"},
        "01257": {"Sheffield": "Sheffield"},
        "01258": {"Mt Washington": "Mt Washington"},
        "01259": {"New Marlborough": "New Marlborough"},
        "01260": {"Lee": "Lee"},
        "01262": {"Stockbridge": "Stockbridge"},
        "01263": {"Stockbridge": "Stockbridge"},
        "01264": {"Tyringham": "Tyringham"},
        "01266": {"West Stockbridge": "West Stockbridge"},
        "01267": {"Williamstown": "Williamstown"},
        "01270": {"Windsor": "Windsor"},
        "01301": {"Greenfield": "Greenfield"},
        "01302": {"Greenfield": "Greenfield"},
        "01330": {"Ashfield": "Ashfield"},
        "01331": {"Athol": "Athol"},
        "01337": {"Bernardston": "Bernardston"},
        "01338": {"Buckland": "Buckland"},
        "01339": {"Hawley": "Hawley"},
        "01340": {"Colrain": "Colrain"},
        "01341": {"Conway": "Conway"},
        "01342": {"Deerfield": "Deerfield"},
        "01343": {"Florida": "Florida"},
        "01344": {"Erving": "Erving"},
        "01346": {"Heath": "Heath"},
        "01347": {"Montague": "Montague"},
        "01349": {"Montague": "Montague"},
        "01350": {"Monroe": "Monroe"},
        "01351": {"Montague": "Montague"},
        "01354": {"Gill": "Gill"},
        "01355": {"New Salem": "New Salem"},
        "01360": {"Northfield": "Northfield"},
        "01364": {"Orange": "Orange"},
        "01366": {"Petersham": "Petersham"},
        "01367": {"Rowe": "Rowe"},
        "01368": {"Royalston": "Royalston"},
        "01370": {"Shelburne": "Shelburne"},
        "01373": {"Whately": "Whately"},
        "01375": {"Sunderland": "Sunderland"},
        "01376": {"Montague": "Montague"},
        "01378": {"Warwick": "Warwick"},
        "01379": {"Wendell": "Wendell"},
        "01380": {"Wendell": "Wendell"},
        "01420": {"Fitchburg": "Fitchburg"},
        "01430": {"Ashburnham": "Ashburnham"},
        "01431": {"Ashby": "Ashby"},
        "01432": {"Ayer": "Ayer"},
        "01434": {"Harvard": "Harvard", "Ayer": "Ayer"},
        "01436": {"Templeton": "Templeton"},
        "01438": {"Templeton": "Templeton"},
        "01440": {"Gardner": "Gardner"},
        "01441": {"Westminster": "Westminster"},
        "01450": {"Groton": "Groton"},
        "01451": {"Harvard": "Harvard"},
        "01452": {"Hubbardston": "Hubbardston"},
        "01453": {"Leominster": "Leominster"},
        "01460": {"Littleton": "Littleton"},
        "01462": {"Lunenburg": "Lunenburg"},
        "01463": {"Pepperell": "Pepperell"},
        "01464": {"Shirley": "Shirley"},
        "01467": {"Harvard": "Harvard"},
        "01468": {"Templeton": "Templeton"},
        "01469": {"Townsend": "Townsend"},
        "01470": {"Groton": "Groton"},
        "01471": {"Groton": "Groton"},
        "01472": {"Groton": "Groton"},
        "01473": {"Westminster": "Westminster"},
        "01474": {"Townsend": "Townsend"},
        "01475": {"Winchendon": "Winchendon"},
        "01477": {"Winchendon": "Winchendon"},
        "01501": {"Auburn": "Auburn"},
        "01503": {"Berlin": "Berlin"},
        "01504": {"Blackstone": "Blackstone"},
        "01505": {"Boylston": "Boylston"},
        "01506": {"Brookfield": "Brookfield"},
        "01507": {"Charlton": "Charlton"},
        "01508": {"Charlton": "Charlton"},
        "01509": {"Charlton": "Charlton"},
        "01510": {"Clinton": "Clinton"},
        "01515": {"East Brookfield": "East Brookfield"},
        "01516": {"Douglas": "Douglas"},
        "01517": {"Princeton": "Princeton"},
        "01518": {"Sturbridge": "Sturbridge"},
        "01519": {"Grafton": "Grafton"},
        "01520": {"Holden": "Holden"},
        "01521": {"Holland": "Holland"},
        "01522": {"Holden": "Holden"},
        "01523": {"Lancaster": "Lancaster"},
        "01524": {"Leicester": "Leicester"},
        "01525": {"Northbridge": "Northbridge"},
        "01526": {"Sutton": "Sutton"},
        "01527": {"Millbury": "Millbury"},
        "01529": {"Millville": "Millville"},
        "01531": {"New Braintree": "New Braintree"},
        "01532": {"Northborough": "Northborough"},
        "01534": {"Northbridge": "Northbridge"},
        "01535": {"North Brookfield": "North Brookfield"},
        "01536": {"Grafton": "Grafton"},
        "01537": {"Oxford": "Oxford"},
        "01538": {"Uxbridge": "Uxbridge"},
        "01540": {"Oxford": "Oxford"},
        "01541": {"Princeton": "Princeton"},
        "01542": {"Leicester": "Leicester"},
        "01543": {"Rutland": "Rutland"},
        "01545": {"Shrewsbury": "Shrewsbury"},
        "01546": {"Shrewsbury": "Shrewsbury"},
        "01550": {"Southbridge": "Southbridge"},
        "01560": {"Grafton": "Grafton"},
        "01561": {"Lancaster": "Lancaster"},
        "01562": {"Spencer": "Spencer"},
        "01564": {"Sterling": "Sterling"},
        "01566": {"Sturbridge": "Sturbridge"},
        "01568": {"Upton": "Upton"},
        "01569": {"Uxbridge": "Uxbridge"},
        "01570": {"Webster": "Webster"},
        "01571": {"Dudley": "Dudley"},
        "01580": {"Westborough": "Westborough"},
        "01581": {"Westborough": "Westborough"},
        "01582": {"Westborough": "Westborough"},
        "01583": {"West Boylston": "West Boylston"},
        "01585": {"West Brookfield": "West Brookfield"},
        "01586": {"Millbury": "Millbury"},
        "01587": {"Upton": "Upton"},
        "01588": {"Northbridge": "Northbridge"},
        "01590": {"Sutton": "Sutton"},
        "01601": {"Worcester": "Worcester"},
        "01602": {"Worcester": "Worcester"},
        "01603": {"Worcester": "Worcester"},
        "01604": {"Worcester": "Worcester"},
        "01605": {"Worcester": "Worcester"},
        "01606": {"Worcester": "Worcester"},
        "01607": {"Worcester": "Worcester"},
        "01608": {"Worcester": "Worcester"},
        "01609": {"Worcester": "Worcester"},
        "01610": {"Worcester": "Worcester"},
        "01611": {"Leicester": "Leicester"},
        "01612": {"Paxton": "Paxton"},
        "01613": {"Worcester": "Worcester"},
        "01614": {"Worcester": "Worcester"},
        "01615": {"Worcester": "Worcester"},
        "01616": {"Worcester": "Worcester"},
        "01653": {"Worcester": "Worcester"},
        "01654": {"Worcester": "Worcester"},
        "01655": {"Worcester": "Worcester"},
        "01701": {"Framingham": "Framingham"},
        "01702": {"Framingham": "Framingham"},
        "01703": {"Framingham": "Framingham"},
        "01704": {"Framingham": "Framingham"},
        "01705": {"Framingham": "Framingham"},
        "01718": {"Acton": "Acton"},
        "01719": {"Boxborough": "Boxborough"},
        "01720": {"Acton": "Acton"},
        "01721": {"Ashland": "Ashland"},
        "01730": {"Bedford": "Bedford"},
        "01731": {"Lincoln": "Lincoln"},
        "01740": {"Bolton": "Bolton"},
        "01741": {"Carlisle": "Carlisle"},
        "01742": {"Concord": "Concord"},
        "01745": {"Southborough": "Southborough"},
        "01746": {"Holliston": "Holliston"},
        "01747": {"Hopedale": "Hopedale"},
        "01748": {"Hopkinton": "Hopkinton"},
        "01749": {"Hudson": "Hudson"},
        "01752": {"Marlborough": "Marlborough"},
        "01754": {"Maynard": "Maynard"},
        "01756": {"Mendon": "Mendon"},
        "01757": {"Milford": "Milford"},
        "01760": {"Natick": "Natick"},
        "01770": {"Sherborn": "Sherborn"},
        "01772": {"Southborough": "Southborough"},
        "01773": {"Lincoln": "Lincoln"},
        "01775": {"Stow": "Stow"},
        "01776": {"Sudbury": "Sudbury"},
        "01778": {"Wayland": "Wayland"},
        "01784": {"Hopkinton": "Hopkinton"},
        "01801": {"Woburn": "Woburn"},
        "01803": {"Burlington": "Burlington"},
        "01805": {"Burlington": "Burlington"},
        "01807": {"Woburn": "Woburn"},
        "01808": {"Woburn": "Woburn"},
        "01810": {"Andover": "Andover"},
        "01812": {"Andover": "Andover"},
        "01813": {"Woburn": "Woburn"},
        "01815": {"Woburn": "Woburn"},
        "01821": {"Billerica": "Billerica"},
        "01822": {"Billerica": "Billerica"},
        "01823": {"Haverhill": "Haverhill"},
        "01824": {"Chelmsford": "Chelmsford"},
        "01826": {"Dracut": "Dracut"},
        "01827": {"Dunstable": "Dunstable"},
        "01830": {"Haverhill": "Haverhill"},
        "01831": {"Haverhill": "Haverhill"},
        "01832": {"Haverhill": "Haverhill"},
        "01833": {"Georgetown": "Georgetown"},
        "01834": {"Groveland": "Groveland"},
        "01835": {"Haverhill": "Haverhill"},
        "01840": {"Lawrence": "Lawrence"},
        "01841": {"Lawrence": "Lawrence"},
        "01842": {"Lawrence": "Lawrence"},
        "01843": {"Lawrence": "Lawrence"},
        "01844": {"Methuen": "Methuen"},
        "01845": {"North Andover": "North Andover"},
        "01850": {"Lowell": "Lowell"},
        "01851": {"Lowell": "Lowell"},
        "01852": {"Lowell": "Lowell"},
        "01853": {"Lowell": "Lowell"},
        "01854": {"Lowell": "Lowell"},
        "01856": {"Lowell": "Lowell"},
        "01860": {"Merrimac": "Merrimac"},
        "01862": {"Billerica": "Billerica"},
        "01863": {"Chelmsford": "Chelmsford"},
        "01864": {"North Reading": "North Reading"},
        "01865": {"Billerica": "Billerica"},
        "01866": {"Billerica": "Billerica"},
        "01867": {"Reading": "Reading"},
        "01876": {"Tewksbury": "Tewksbury"},
        "01878": {"Tyngsborough": "Tyngsborough"},
        "01879": {"Tyngsborough": "Tyngsborough"},
        "01880": {"Wakefield": "Wakefield"},
        "01885": {"Boxford": "Boxford"},
        "01886": {"Westford": "Westford"},
        "01887": {"Wilmington": "Wilmington"},
        "01888": {"Woburn": "Woburn"},
        "01889": {"North Reading": "North Reading"},
        "01890": {"Winchester": "Winchester"},
        "01899": {"Andover": "Andover"},
        "01901": {"Lynn": "Lynn"},
        "01902": {"Lynn": "Lynn"},
        "01903": {"Lynn": "Lynn"},
        "01904": {"Lynn": "Lynn"},
        "01905": {"Lynn": "Lynn"},
        "01906": {"Saugus": "Saugus"},
        "01907": {"Swampscott": "Swampscott"},
        "01908": {"Nahant": "Nahant"},
        "01910": {"Lynn": "Lynn"},
        "01913": {"Amesbury": "Amesbury"},
        "01915": {"Beverly": "Beverly"},
        "01921": {"Boxford": "Boxford"},
        "01922": {"Newbury": "Newbury"},
        "01923": {"Danvers": "Danvers"},
        "01929": {"Essex": "Essex"},
        "01930": {"Gloucester": "Gloucester"},
        "01931": {"Gloucester": "Gloucester"},
        "01936": {"Hamilton": "Hamilton"},
        "01937": {"Danvers": "Danvers"},
        "01938": {"Ipswich": "Ipswich"},
        "01940": {"Lynnfield": "Lynnfield"},
        "01944": {"Manchester By The Sea": "Manchester By The Sea"},
        "01945": {"Marblehead": "Marblehead"},
        "01947": {"Salem": "Salem"},
        "01949": {"Middleton": "Middleton"},
        "01950": {"Newburyport": "Newburyport"},
        "01951": {"Newbury": "Newbury"},
        "01952": {"Salisbury": "Salisbury"},
        "01960": {"Peabody": "Peabody"},
        "01961": {"Peabody": "Peabody"},
        "01965": {"Beverly": "Beverly"},
        "01966": {"Rockport": "Rockport"},
        "01969": {"Rowley": "Rowley"},
        "01970": {"Salem": "Salem"},
        "01971": {"Salem": "Salem"},
        "01982": {"Hamilton": "Hamilton"},
        "01983": {"Topsfield": "Topsfield"},
        "01984": {"Wenham": "Wenham"},
        "01985": {"West Newbury": "West Newbury"},
        "02018": {"Hingham": "Hingham"},
        "02019": {"Bellingham": "Bellingham"},
        "02020": {"Marshfield": "Marshfield"},
        "02021": {"Canton": "Canton"},
        "02025": {"Cohasset": "Cohasset"},
        "02026": {"Dedham": "Dedham"},
        "02027": {"Dedham": "Dedham"},
        "02030": {"Dover": "Dover"},
        "02031": {"Mansfield": "Mansfield"},
        "02032": {"Walpole": "Walpole"},
        "02035": {"Foxborough": "Foxborough"},
        "02038": {"Franklin": "Franklin"},
        "02040": {"Scituate": "Scituate"},
        "02041": {"Marshfield": "Marshfield"},
        "02043": {"Hingham": "Hingham"},
        "02044": {"Hingham": "Hingham"},
        "02045": {"Hull": "Hull"},
        "02047": {"Scituate": "Scituate"},
        "02048": {"Mansfield": "Mansfield"},
        "02050": {"Marshfield": "Marshfield"},
        "02051": {"Marshfield": "Marshfield"},
        "02052": {"Medfield": "Medfield"},
        "02053": {"Medway": "Medway"},
        "02054": {"Millis": "Millis"},
        "02055": {"Scituate": "Scituate"},
        "02056": {"Norfolk": "Norfolk"},
        "02059": {"Marshfield": "Marshfield"},
        "02060": {"Scituate": "Scituate"},
        "02061": {"Norwell": "Norwell"},
        "02062": {"Norwood": "Norwood"},
        "02065": {"Marshfield": "Marshfield"},
        "02066": {"Scituate": "Scituate"},
        "02067": {"Sharon": "Sharon"},
        "02070": {"Wrentham": "Wrentham"},
        "02071": {"Walpole": "Walpole"},
        "02072": {"Stoughton": "Stoughton"},
        "02081": {"Walpole": "Walpole"},
        "02090": {"Westwood": "Westwood"},
        "02091": {"Bellingham": "Bellingham"},
        "02093": {"Wrentham": "Wrentham"},
        "02101": {"Boston": "Boston"},
        "02102": {"Boston": "Boston"},
        "02103": {"Boston": "Boston"},
        "02104": {"Boston": "Boston"},
        "02105": {"Boston": "Boston"},
        "02106": {"Boston": "Boston"},
        "02107": {"Boston": "Boston"},
        "02108": {"Boston": "Boston"},
        "02109": {"Boston": "Boston"},
        "02110": {"Boston": "Boston"},
        "02111": {"Boston": "Boston"},
        "02112": {"Boston": "Boston"},
        "02113": {"Boston": "Boston"},
        "02114": {"Boston": "Boston"},
        "02115": {"Boston": "Boston"},
        "02116": {"Boston": "Boston"},
        "02117": {"Boston": "Boston"},
        "02118": {"Boston": "Boston"},
        "02119": {"Boston": "Boston"},
        "02120": {"Boston": "Boston"},
        "02121": {"Boston": "Boston"},
        "02122": {"Boston": "Boston"},
        "02123": {"Boston": "Boston"},
        "02124": {"Boston": "Boston"},
        "02125": {"Boston": "Boston"},
        "02126": {"Boston": "Boston"},
        "02127": {"Boston": "Boston"},
        "02128": {"Boston": "Boston"},
        "02129": {"Boston": "Boston"},
        "02130": {"Boston": "Boston"},
        "02131": {"Boston": "Boston"},
        "02132": {"Boston": "Boston"},
        "02133": {"Boston": "Boston"},
        "02134": {"Boston": "Boston"},
        "02135": {"Boston": "Boston"},
        "02136": {"Boston": "Boston"},
        "02137": {"Boston": "Boston"},
        "02138": {"Cambridge": "Cambridge"},
        "02139": {"Cambridge": "Cambridge"},
        "02140": {"Cambridge": "Cambridge"},
        "02141": {"Cambridge": "Cambridge"},
        "02142": {"Cambridge": "Cambridge"},
        "02143": {"Somerville": "Somerville"},
        "02144": {"Somerville": "Somerville"},
        "02145": {"Somerville": "Somerville"},
        "02146": {"Brookline": "Brookline"},
        "02148": {"Malden": "Malden"},
        "02149": {"Everett": "Everett"},
        "02150": {"Chelsea": "Chelsea"},
        "02151": {"Revere": "Revere"},
        "02152": {"Winthrop": "Winthrop"},
        "02153": {"Medford": "Medford"},
        "02154": {"Waltham": "Waltham"},
        "02155": {"Medford": "Medford"},
        "02156": {"Medford": "Medford"},
        "02158": {"Newton": "Newton"},
        "02160": {"Newton": "Newton"},
        "02161": {"Newton": "Newton"},
        "02162": {"Newton": "Newton"},
        "02163": {"Boston": "Boston"},
        "02164": {"Newton": "Newton"},
        "02167": {"Newton": "Newton"},
        "02168": {"Newton": "Newton"},
        "02169": {"Quincy": "Quincy"},
        "02170": {"Quincy": "Quincy"},
        "02171": {"Quincy": "Quincy"},
        "02172": {"Watertown": "Watertown"},
        "02174": {"Arlington": "Arlington"},
        "02176": {"Melrose": "Melrose"},
        "02178": {"Belmont": "Belmont"},
        "02180": {"Stoneham": "Stoneham"},
        "02181": {"Wellesley": "Wellesley"},
        "02184": {"Braintree": "Braintree"},
        "02185": {"Braintree": "Braintree"},
        "02186": {"Milton": "Milton"},
        "02187": {"Milton": "Milton"},
        "02188": {"Weymouth": "Weymouth"},
        "02189": {"Weymouth": "Weymouth"},
        "02190": {"Weymouth": "Weymouth"},
        "02191": {"Weymouth": "Weymouth"},
        "02192": {"Needham": "Needham"},
        "02193": {"Weston": "Weston"},
        "02194": {"Needham": "Needham"},
        "02196": {"Boston": "Boston"},
        "02199": {"Boston": "Boston"},
        "02201": {"Boston": "Boston"},
        "02203": {"Boston": "Boston"},
        "02204": {"Boston": "Boston"},
        "02205": {"Boston": "Boston"},
        "02206": {"Boston": "Boston"},
        "02210": {"Boston": "Boston"},
        "02211": {"Boston": "Boston"},
        "02212": {"Boston": "Boston"},
        "02215": {"Boston": "Boston"},
        "02216": {"Boston": "Boston"},
        "02217": {"Boston": "Boston"},
        "02218": {"Boston": "Boston"},
        "02222": {"Boston": "Boston"},
        "02228": {"Boston": "Boston"},
        "02238": {"Cambridge": "Cambridge"},
        "02241": {"Boston": "Boston"},
        "02246": {"Brookline": "Brookline"},
        "02254": {"Nantucket": "Nantucket"},
        "02266": {"Boston": "Boston"},
        "02269": {"Quincy": "Quincy"},
        "02295": {"Boston": "Boston"},
        "02297": {"Boston": "Boston"},
        "02298": {"Boston": "Boston"},
        "02301": {"Brockton": "Brockton"},
        "02302": {"Brockton": "Brockton"},
        "02303": {"Brockton": "Brockton"},
        "02304": {"Brockton": "Brockton"},
        "02305": {"Brockton": "Brockton"},
        "02315": {"Boston": "Boston"},
        "02322": {"Avon": "Avon"},
        "02324": {"Bridgewater": "Bridgewater"},
        "02325": {"Bridgewater": "Bridgewater"},
        "02327": {"Pembroke": "Pembroke"},
        "02330": {"Carver": "Carver"},
        "02331": {"Duxbury": "Duxbury"},
        "02332": {"Duxbury": "Duxbury"},
        "02333": {"East Bridgewater": "East Bridgewater"},
        "02334": {"Easton": "Easton"},
        "02337": {"East Bridgewater": "East Bridgewater"},
        "02338": {"Halifax": "Halifax"},
        "02339": {"Hanover": "Hanover"},
        "02340": {"Hanover": "Hanover"},
        "02341": {"Hanson": "Hanson"},
        "02343": {"Holbrook": "Holbrook"},
        "02344": {"Easton": "Easton"},
        "02345": {"Plymouth": "Plymouth"},
        "02346": {"Middleborough": "Middleborough"},
        "02347": {"Lakeville": "Lakeville"},
        "02348": {"Lakeville": "Lakeville"},
        "02349": {"Middleborough": "Middleborough"},
        "02350": {"Hanson": "Hanson"},
        "02351": {"Abington": "Abington"},
        "02355": {"Carver": "Carver"},
        "02356": {"Easton": "Easton"},
        "02357": {"Easton": "Easton"},
        "02358": {"Pembroke": "Pembroke"},
        "02359": {"Pembroke": "Pembroke"},
        "02360": {"Plymouth": "Plymouth"},
        "02361": {"Plymouth": "Plymouth"},
        "02362": {"Plymouth": "Plymouth"},
        "02364": {"Kingston": "Kingston"},
        "02366": {"Carver": "Carver"},
        "02367": {"Plympton": "Plympton"},
        "02368": {"Randolph": "Randolph"},
        "02370": {"Rockland": "Rockland"},
        "02375": {"Easton": "Easton"},
        "02379": {"West Bridgewater": "West Bridgewater"},
        "02381": {"Plymouth": "Plymouth"},
        "02382": {"Whitman": "Whitman"},
        "02383": {"Whitman": "Whitman"},
        "02401": {"Brockton": "Brockton"},
        "02402": {"Brockton": "Brockton"},
        "02408": {"Boston": "Boston"},
        "02415": {"Waltham": "Waltham"},
        "02420": {"Lexington": "Lexington"},
        "02421": {"Lexington": "Lexington"},
        "02445": {"Brookline": "Brookline"},
        "02446": {"Brookline": "Brookline"},
        "02447": {"Brookline": "Brookline"},
        "02451": {"Waltham": "Waltham"},
        "02452": {"Waltham": "Waltham"},
        "02453": {"Waltham": "Waltham"},
        "02454": {"Waltham": "Waltham"},
        "02455": {"Waltham": "Waltham"},
        "02456": {"Newton": "Newton"},
        "02457": {"Wellesley": "Wellesley"},
        "02458": {"Newton": "Newton"},
        "02459": {"Newton": "Newton"},
        "02460": {"Newton": "Newton"},
        "02461": {"Newton": "Newton"},
        "02462": {"Newton": "Newton"},
        "02464": {"Newton": "Newton"},
        "02465": {"Newton": "Newton"},
        "02466": {"Newton": "Newton"},
        "02467": {"Brookline": "Brookline", "Boston": "Boston", "Newton": "Newton"},
        "02468": {"Newton": "Newton"},
        "02471": {"Watertown": "Watertown"},
        "02472": {"Watertown": "Watertown"},
        "02474": {"Arlington": "Arlington"},
        "02475": {"Arlington": "Arlington"},
        "02476": {"Arlington": "Arlington"},
        "02477": {"Watertown": "Watertown"},
        "02478": {"Belmont": "Belmont"},
        "02479": {"Belmont": "Belmont"},
        "02481": {"Wellesley": "Wellesley"},
        "02482": {"Wellesley": "Wellesley"},
        "02492": {"Needham": "Needham"},
        "02493": {"Weston": "Weston"},
        "02494": {"Needham": "Needham"},
        "02495": {"Newton": "Newton"},
        "02532": {"Wareham": "Wareham", "Bourne": "Bourne"},
        "02534": {"Bourne": "Bourne"},
        "02535": {"Chilmark": "Chilmark"},
        "02536": {"Falmouth": "Falmouth"},
        "02537": {"Sandwich": "Sandwich"},
        "02538": {"Wareham": "Wareham"},
        "02539": {"Edgartown": "Edgartown"},
        "02540": {"Falmouth": "Falmouth"},
        "02541": {"Falmouth": "Falmouth"},
        "02542": {"Sandwich": "Sandwich"},
        "02543": {"Falmouth": "Falmouth"},
        "02552": {"Chilmark": "Chilmark"},
        "02553": {"Bourne": "Bourne"},
        "02554": {"Nantucket": "Nantucket"},
        "02556": {"Falmouth": "Falmouth"},
        "02557": {"Oak Bluffs": "Oak Bluffs"},
        "02558": {"Wareham": "Wareham"},
        "02559": {"Bourne": "Bourne"},
        "02561": {"Bourne": "Bourne"},
        "02562": {"Bourne": "Bourne"},
        "02563": {"Sandwich": "Sandwich"},
        "02564": {"Nantucket": "Nantucket"},
        "02565": {"Falmouth": "Falmouth"},
        "02568": {"West Tisbury": "West Tisbury"},
        "02571": {"Wareham": "Wareham"},
        "02573": {"Tisbury": "Tisbury"},
        "02574": {"Falmouth": "Falmouth"},
        "02575": {"West Tisbury": "West Tisbury"},
        "02576": {"Wareham": "Wareham"},
        "02584": {"Nantucket": "Nantucket"},
        "02601": {"Barnstable": "Barnstable"},
        "02630": {"Barnstable": "Barnstable"},
        "02631": {"Brewster": "Brewster"},
        "02632": {"Barnstable": "Barnstable"},
        "02633": {"Chatham": "Chatham"},
        "02634": {"Barnstable": "Barnstable"},
        "02635": {"Barnstable": "Barnstable"},
        "02636": {"Barnstable": "Barnstable"},
        "02637": {"Barnstable": "Barnstable"},
        "02638": {"Dennis": "Dennis"},
        "02639": {"Dennis": "Dennis"},
        "02641": {"Dennis": "Dennis"},
        "02642": {"Eastham": "Eastham"},
        "02643": {"Orleans": "Orleans"},
        "02644": {"Sandwich": "Sandwich"},
        "02645": {"Harwich": "Harwich"},
        "02646": {"Harwich": "Harwich"},
        "02647": {"Barnstable": "Barnstable"},
        "02648": {"Barnstable": "Barnstable"},
        "02649": {"Mashpee": "Mashpee"},
        "02650": {"Chatham": "Chatham"},
        "02651": {"Eastham": "Eastham"},
        "02652": {"Truro": "Truro"},
        "02653": {"Orleans": "Orleans"},
        "02655": {"Barnstable": "Barnstable"},
        "02657": {"Provincetown": "Provincetown"},
        "02659": {"Chatham": "Chatham"},
        "02660": {"Dennis": "Dennis"},
        "02661": {"Harwich": "Harwich"},
        "02662": {"Brewster": "Brewster"},
        "02663": {"Wellfleet": "Wellfleet"},
        "02664": {"Yarmouth": "Yarmouth"},
        "02666": {"Truro": "Truro"},
        "02667": {"Wellfleet": "Wellfleet"},
        "02668": {"Barnstable": "Barnstable"},
        "02669": {"Chatham": "Chatham"},
        "02670": {"Dennis": "Dennis"},
        "02671": {"Harwich": "Harwich"},
        "02672": {"Barnstable": "Barnstable"},
        "02673": {"Yarmouth": "Yarmouth"},
        "02675": {"Yarmouth": "Yarmouth"},
        "02702": {"Freetown": "Freetown"},
        "02703": {"Attleboro": "Attleboro"},
        "02712": {"Norton": "Norton"},
        "02713": {"Gosnold": "Gosnold"},
        "02714": {"Dartmouth": "Dartmouth"},
        "02715": {"Dighton": "Dighton"},
        "02717": {"Freetown": "Freetown"},
        "02718": {"Taunton": "Taunton"},
        "02719": {"Fairhaven": "Fairhaven"},
        "02720": {"Fall River": "Fall River"},
        "02721": {"Fall River": "Fall River"},
        "02722": {"Fall River": "Fall River"},
        "02723": {"Fall River": "Fall River"},
        "02724": {"Fall River": "Fall River"},
        "02725": {"Somerset": "Somerset"},
        "02726": {"Somerset": "Somerset"},
        "02738": {"Marion": "Marion"},
        "02739": {"Mattapoisett": "Mattapoisett"},
        "02740": {"New Bedford": "New Bedford"},
        "02741": {"New Bedford": "New Bedford"},
        "02742": {"New Bedford": "New Bedford"},
        "02743": {"Acushnet": "Acushnet"},
        "02744": {"New Bedford": "New Bedford"},
        "02745": {"New Bedford": "New Bedford"},
        "02746": {"New Bedford": "New Bedford"},
        "02747": {"Dartmouth": "Dartmouth"},
        "02748": {"Dartmouth": "Dartmouth"},
        "02751": {"Wareham": "Wareham"},
        "02756": {"Wareham": "Wareham"},
        "02760": {"North Attleborough": "North Attleborough"},
        "02761": {"North Attleborough": "North Attleborough"},
        "02762": {"Plainville": "Plainville"},
        "02763": {"North Attleborough": "North Attleborough"},
        "02764": {"Dighton": "Dighton"},
        "02766": {"Norton": "Norton"},
        "02767": {"Raynham": "Raynham"},
        "02768": {"Raynham": "Raynham"},
        "02769": {"Rehoboth": "Rehoboth"},
        "02770": {"Rochester": "Rochester"},
        "02771": {"Seekonk": "Seekonk"},
        "02777": {"Swansea": "Swansea"},
        "02779": {"Berkley": "Berkley"},
        "02780": {"Taunton": "Taunton"},
        "02783": {"Taunton ": "Taunton "},
        "02790": {"Westport": "Westport"},
        "02791": {"Westport": "Westport"},
        "05501": {"Andover": "Andover"},
        "05544": {"Andover": "Andover"},
    }

    category_benefits = {
        "cash": {
            "benefits": {
                "tanf": {
                    "name": {
                        "_label": "cashAssistanceBenefits.ma_tanf",
                        "_default_message": "Transitional Aid to Families with Dependent Children (TAFDC): ",
                    },
                    "description": {
                        "_label": "cashAssistanceBenefits.ma_tanf_desc",
                        "_default_message": "Cash assistance and work support",
                    },
                },
                "ma_eaedc": {
                    "name": {
                        "_label": "cashAssistanceBenefits.ma_eaedc",
                        "_default_message": "Emergency Aid to Elderly, Disabled and Children (EAEDC): ",
                    },
                    "description": {
                        "_label": "cashAssistanceBenefits.ma_eaedc_desc",
                        "_default_message": "Cash assistance",
                    },
                },
                "ssi": {
                    "name": {
                        "_label": "cashAssistanceBenefits.ssi",
                        "_default_message": "Supplemental Security Income (SSI): ",
                    },
                    "description": {
                        "_label": "cashAssistanceBenefits.ssi_desc",
                        "_default_message": "Federal cash assistance for individuals who are disabled, blind, or 65 years of age or older",
                    },
                },
                "ma_ssp": {
                    "name": {
                        "_label": "cashAssistanceBenefits.ma_ssp",
                        "_default_message": "Massachusetts State Supplement Program (SSP): ",
                    },
                    "description": {
                        "_label": "cashAssistanceBenefits.ma_ssp_desc",
                        "_default_message": "State cash assistance for people with disabilities or 65 years of age or older",
                    },
                },
                "ssdi": {
                    "name": {
                        "_label": "cashAssistanceBenefits.ssdi",
                        "_default_message": "Social Security Disability Insurance (SSDI): ",
                    },
                    "description": {
                        "_label": "cashAssistanceBenefits.ssdi_desc",
                        "_default_message": "Social security benefit for people with disabilities",
                    },
                },
            },
            "category_name": {"_label": "cashAssistance", "_default_message": "Cash Assistance"},
        },
        "foodAndNutrition": {
            "benefits": {
                "snap": {
                    "name": {
                        "_label": "foodAndNutritionBenefits.snap",
                        "_default_message": "Supplemental Nutrition Assistance Program (SNAP): ",
                    },
                    "description": {
                        "_label": "foodAndNutritionBenefits.snap_desc",
                        "_default_message": "Food assistance",
                    },
                },
                "wic": {
                    "name": {
                        "_label": "foodAndNutritionBenefits.wic",
                        "_default_message": "Special Supplemental Nutrition Program for Women, Infants, and Children (WIC): ",
                    },
                    "description": {
                        "_label": "foodAndNutritionBenefits.wic_desc",
                        "_default_message": "Food and breastfeeding assistance",
                    },
                },
                "nslp": {
                    "name": {
                        "_label": "foodAndNutritionBenefits.nslp",
                        "_default_message": "National School Lunch Program: ",
                    },
                    "description": {
                        "_label": "foodAndNutritionBenefits.nslp_desc",
                        "_default_message": "Free school meals",
                    },
                },
                "csfp": {
                    "name": {
                        "_label": "foodAndNutritionBenefits.csfp",
                        "_default_message": "Commodity Supplemental Food Program: ",
                    },
                    "description": {
                        "_label": "foodAndNutritionBenefits.csfp_desc",
                        "_default_message": "Food support for people 60 years of age or older",
                    },
                },
            },
            "category_name": {"_label": "foodAndNutrition", "_default_message": "Food and Nutrition"},
        },
        "childCare": {
            "benefits": {
                "ccdf": {
                    "name": {
                        "_label": "childCareBenefits.ma_ccfa",
                        "_default_message": "Child Care Financial Assistance Program (CCFA): ",
                    },
                    "description": {
                        "_label": "childCareBenefits.ma_ccfa_desc",
                        "_default_message": "Help with child care costs",
                    },
                },
            },
            "category_name": {
                "_label": "childCareYouthAndEducation",
                "_default_message": "Child Care, Youth, and Education",
            },
        },
        "housingAndUtilities": {
            "benefits": {
                "lifeline": {
                    "name": {"_label": "housingAndUtilities.lifeline", "_default_message": "Lifeline: "},
                    "description": {
                        "_label": "housingAndUtilities.lifeline_desc",
                        "_default_message": "Phone or internet discount",
                    },
                },
            },
            "category_name": {"_label": "housingAndUtilities", "_default_message": "Housing and Utilities"},
        },
        "transportation": {
            "benefits": {
                "ma_mbta": {
                    "name": {
                        "_label": "transportationBenefits.ma_mbta",
                        "_default_message": "MBTA Reduced Fare Program: ",
                    },
                    "description": {
                        "_label": "transportationBenefits.ma_mbta_desc",
                        "_default_message": "Discounted MBTA fares",
                    },
                }
            },
            "category_name": {"_label": "transportation", "_default_message": "Transportation"},
        },
        "healthCare": {
            "benefits": {
                "aca": {
                    "name": {
                        "_label": "healthCareBenefits.aca.ma",
                        "_default_message": "Massachusetts Health Connector/Premium Tax Credit: ",
                    },
                    "description": {
                        "_label": "healthCareBenefits.aca_desc.ma",
                        "_default_message": "Health insurance marketplace premium tax credit",
                    },
                },
            },
            "category_name": {"_label": "healthCare", "_default_message": "Health Care"},
        },
        "taxCredits": {
            "benefits": {
                "eitc": {
                    "name": {
                        "_label": "taxCreditBenefits.eitc",
                        "_default_message": "Earned Income Tax Credit (EITC): ",
                    },
                    "description": {
                        "_label": "taxCreditBenefits.eitc_desc",
                        "_default_message": "Federal tax credit - earned income",
                    },
                },
                "ctc": {
                    "name": {"_label": "taxCreditBenefits.ctc", "_default_message": "Child Tax Credit (CTC): "},
                    "description": {"_label": "taxCreditBenefits.ctc_desc", "_default_message": "Federal tax credit"},
                },
                "ma_maeitc": {
                    "name": {
                        "_label": "taxCreditBenefits.ma_maeitc",
                        "_default_message": "Massachusetts Earned Income Tax Credit: ",
                    },
                    "description": {
                        "_label": "taxCreditBenefits.ma_maeitc_desc",
                        "_default_message": "State tax credit - earned income",
                    },
                },
                "ma_macfc": {
                    "name": {
                        "_label": "taxCreditBenefits.ma_macftc",
                        "_default_message": "Massachusetts Child and Family Tax Credit: ",
                    },
                    "description": {
                        "_label": "taxCreditBenefits.ma_macftc_desc",
                        "_default_message": "State tax credit",
                    },
                },
            },
            "category_name": {"_label": "taxCredits", "_default_message": "Tax Credits"},
        },
    }

    consent_to_contact = {
        "en-us": "https://www.myfriendben.org/terms-and-conditions/",
        "es": "https://www.myfriendben.org/terminos-condiciones/",
    }

    privacy_policy = {
        "en-us": "https://www.myfriendben.org/privacy-policy/",
        "es": "https://www.myfriendben.org/privacidad/",
    }

    referrer_data = {
        "theme": {"default": "default"},
        "logoSource": {
            "default": "MFB_MALogo",
        },
        "logoAlt": {
            "default": {"id": "referrerHook.logoAlts.default", "defaultMessage": "MyFriendBen home page button"},
        },
        "logoFooterSource": {"default": "MFB_Logo"},
        "logoFooterAlt": {
            "default": {"id": "footer.logo.alt", "defaultMessage": "MFB Logo"},
        },
        "logoClass": {"default": "logo"},
        "shareLink": {
            "default": "https://screener.myfriendben.org",
        },
        "stepDirectory": {
            "default": [
                "zipcode",
                # the hhSize and hhData have to be consecutive
                "householdSize",
                "householdData",
                "hasExpenses",
                "householdAssets",
                "hasBenefits",
                "acuteHHConditions",
                "referralSource",
                "signUpInfo",
            ],
        },
        "featureFlags": {"default": []},
        "noResultMessage": {
            "default": {
                "_label": "noResultMessage",
                "_default_message": "It looks like you may not qualify for benefits included in MyFriendBen at this time. If you indicated need for an immediate resource, please click on the “Near-Term Benefits” tab. For additional resources, please click the 'More Help' button below to get the resources you’re looking for.",
            },
        },
        "defaultLanguage": {"default": "en-us"},
    }

    footer_data = {
        "email": "hello@myfriendben.org",
    }

    feedback_links = {
        "email": "hello@myfriendben.org",
        "survey": "https://docs.google.com/forms/d/e/1FAIpQLSdnfqjvlVSBQkJuUMvhEDUp-t6oD-8tPQi67uRG2iNetXmSfA/viewform?usp=sf_link",
    }

    override_text = {
        # NOTE: MA uses cities instead of counties
        "questions.zipcode-a": {
            "_label": "questions.zipcode.city.question.ma",
            "_default_message": "Please select a city:",
        },
        "questions.zipcode-a-inputLabel": {
            "_label": "questions.zipcode.city.label.ma",
            "_default_message": "Select a city",
        },
        "questions.zipcode-a-disabledSelectMenuItemText": {
            "_label": "questions.zipcode.city.menuItemText.ma",
            "_default_message": "Select a city",
        },
        "errorMessage-county": {
            "_label": "questions.zipcode.city.error.ma",
            "_default_message": "Please Select a city",
        },
        # NOTE: Change the household size help text
        "questions.householdSize-helpText": {
            "_label": "questions.householdSize-helpText.ma",
            "_default_message": "This is usually family members whom you live with and share important resources with like food and bills. Your roommates / housemates typically do not count as part of your household. If other adults 18 or older in your household file their own tax return, ask them to complete this tool to determine if they qualify for benefits. But even if you and your spouse file taxes separately, include your spouse in the household.",
        },
    }
