from .base import ConfigurationData
from screener.models import WhiteLabel


class MaConfigurationData(ConfigurationData):
    @classmethod
    def get_white_label(self) -> WhiteLabel:
        return WhiteLabel.objects.get(code="ma")

    public_charge_rule = {"link": ""}  # TODO: add public charge link

    more_help_options = {  # TODO: add more help options for the bottom of the results page
        "moreHelpOptions": [
            {
                "name": {"_default_message": "", "_label": ""},
                "link": "",
                "phone": {"_default_message": "", "_label": ""},
            },
        ]
    }

    acute_condition_options = {  # TODO: add/remove urgent need options set to and empty list if none
        "food": {
            "icon": {"_name": "Food", "_classname": "option-card-icon"},
            "_label": "acuteConditionOptions.food",
            "_default_message": "Food or groceries",
        },
        "babySupplies": {
            "icon": {"_name": "Baby_supplies", "_classname": "option-card-icon"},
            "_label": "acuteConditionOptions.babySupplies",
            "_default_message": "Diapers and other baby supplies",
        },
        "housing": {
            "icon": {"_name": "Housing", "_classname": "option-card-icon"},
            "_label": "acuteConditionOptions.housing",
            "_default_message": "Help with managing your mortgage, rent, or utilities",
        },
        "support": {
            "icon": {"_name": "Support", "_classname": "option-card-icon"},
            "_label": "acuteConditionOptions.support",
            "_default_message": "A challenge you or your child would like to talk about",
        },
        "childDevelopment": {
            "icon": {"_name": "Child_development", "_classname": "option-card-icon"},
            "_label": "acuteConditionOptions.childDevelopment",
            "_default_message": "Concern about your child's development",
        },
        "familyPlanning": {
            "icon": {"_name": "Family_planning", "_classname": "option-card-icon"},
            "_label": "acuteConditionOptions.familyPlanning",
            "_default_message": "Family planning or birth control",
        },
        "jobResources": {
            "icon": {"_name": "Job_resources", "_classname": "option-card-icon"},
            "_label": "acuteConditionOptions.jobResources",
            "_default_message": "Finding a job",
        },
        "dentalCare": {
            "icon": {"_name": "Dental_care", "_classname": "option-card-icon"},
            "_label": "acuteConditionOptions.dentalCare",
            "_default_message": "Low-cost dental care",
        },
        "legalServices": {
            "icon": {"_name": "Legal_services", "_classname": "option-card-icon"},
            "_label": "acuteConditionOptions.legalServices",
            "_default_message": "Free or low-cost help with civil legal needs or IDs",
        },
    }

    sign_up_options = {  # TODO: add ways that the user can sign up for communication on the sign up page
        "sendUpdates": {
            "_label": "signUpOptions.sendUpdates",
            "_default_message": "Please notify me when new benefits become available to me that I am likely eligible for based on the information I have provided.",
        },
        "sendOffers": {
            "_label": "signUpOptions.sendOffers",
            "_default_message": "Please notify me when there are paid opportunities to provide feedback on MyFriendBen.",
        },
    }

    relationship_options = {  # TODO: add relationship options on the member page
        "child": {"_label": "relationshipOptions.child", "_default_message": "Child"},
        "fosterChild": {
            "_label": "relationshipOptions.fosterChildOrKinshipChild",
            "_default_message": "Foster Child / Kinship Care",
        },
        "stepChild": {"_label": "relationshipOptions.stepChild", "_default_message": "Step-child"},
        "grandChild": {"_label": "relationshipOptions.grandChild", "_default_message": "Grandchild"},
        "spouse": {"_label": "relationshipOptions.spouse", "_default_message": "Spouse"},
        "parent": {"_label": "relationshipOptions.parent", "_default_message": "Parent"},
        "fosterParent": {"_label": "relationshipOptions.fosterParent", "_default_message": "Foster Parent"},
        "stepParent": {"_label": "relationshipOptions.stepParent", "_default_message": "Step-parent"},
        "grandParent": {"_label": "relationshipOptions.grandParent", "_default_message": "Grandparent"},
        "sisterOrBrother": {"_label": "relationshipOptions.sisterOrBrother", "_default_message": "Sister/Brother"},
        "stepSisterOrBrother": {
            "_label": "relationshipOptions.stepSisterOrBrother",
            "_default_message": "Step-sister/Step-brother",
        },
        "boyfriendOrGirlfriend": {
            "_label": "relationshipOptions.boyfriendOrGirlfriend",
            "_default_message": "Boyfriend/Girlfriend",
        },
        "domesticPartner": {"_label": "relationshipOptions.domesticPartner", "_default_message": "Domestic Partner"},
        "relatedOther": {"_label": "relationshipOptions.relatedOther", "_default_message": "Related in some other way"},
    }

    referral_options = {  # TODO: add referreral options for the referrer question
        "other": {"_label": "referralOptions.other", "_default_message": "Other"},
        "testOrProspect": {
            "_label": "referralOptions.testOrProspect",
            "_default_message": "Test / Prospective Partner",
        },
    }

    language_options = {  # TODO: add/remove language options
        "en-us": "English",
        "es": "Español",
        "vi": "Tiếng Việt",
        "fr": "Français",
        "am": "አማርኛ",
        "so": "Soomaali",
        "ru": "Русский",
        "ne": "नेपाली",
        "my": "မြန်မာဘာသာစကား",
        "zh": "中文",
        "ar": "عربي",
        "sw": "Kiswahili",
    }

    income_options = {  # TODO: add types of income to collect on the income question
        "wages": {"_label": "incomeOptions.wages", "_default_message": "Wages, salaries, tips"},
        "selfEmployment": {
            "_label": "incomeOptions.selfEmployment",
            "_default_message": "Income from freelance, independent contractor, or self-employment work",
        },
        "sSDisability": {
            "_label": "incomeOptions.sSDisability",
            "_default_message": "Social Security Disability Benefits",
        },
        "sSRetirement": {
            "_label": "incomeOptions.sSRetirement",
            "_default_message": "Social Security Retirement Benefits",
        },
        "sSI": {"_label": "incomeOptions.sSI", "_default_message": "Supplemental Security Income (SSI)"},
        "childSupport": {"_label": "incomeOptions.childSupport", "_default_message": "Child Support (Received)"},
        "pension": {
            "_label": "incomeOptions.pension",
            "_default_message": "Military, Government, or Private Pension (including PERA)",
        },
        "veteran": {"_label": "incomeOptions.veteran", "_default_message": "Veteran's Pension or Benefits"},
        "sSSurvivor": {
            "_label": "incomeOptions.sSSurvivor",
            "_default_message": "Social Security Survivor's Benefits (Widow/Widower)",
        },
        "unemployment": {"_label": "incomeOptions.unemployment", "_default_message": "Unemployment Benefits"},
        "sSDependent": {
            "_label": "incomeOptions.sSDependent",
            "_default_message": "Social Security Dependent Benefits (retirement, disability, or survivors)",
        },
        "cashAssistance": {"_label": "incomeOptions.cashAssistance", "_default_message": "Cash Assistance Grant"},
        "gifts": {"_label": "incomeOptions.gifts", "_default_message": "Gifts/Contributions (Received)"},
        "investment": {
            "_label": "incomeOptions.investment",
            "_default_message": "Investment Income (interest, dividends, and profit from selling stocks)",
        },
        "cOSDisability": {
            "_label": "incomeOptions.cOSDisability",
            "_default_message": "Colorado State Disability Benefits",
        },
        "rental": {"_label": "incomeOptions.rental", "_default_message": "Rental Income"},
        "alimony": {"_label": "incomeOptions.alimony", "_default_message": "Alimony (Received)"},
        "deferredComp": {
            "_label": "incomeOptions.deferredComp",
            "_default_message": "Withdrawals from Deferred Compensation (IRA, Keogh, etc.)",
        },
        "workersComp": {"_label": "incomeOptions.workersComp", "_default_message": "Worker's Compensation"},
        "boarder": {"_label": "incomeOptions.boarder", "_default_message": "Boarder or Lodger"},
    }

    health_insurance_options = {  # TODO: add health insurance options on the member question
        "you": {
            "none": {
                "icon": {"_name": "None", "_classname": "option-card-icon"},
                "_label": "healthInsuranceOptions.none-dont-know-I",
                "_default_message": "I don't have or know if I have health insurance",
            },
            "employer": {
                "icon": {"_name": "Employer", "_classname": "option-card-icon"},
                "_label": "healthInsuranceOptions.employer",
                "_default_message": "Employer-provided health insurance",
            },
            "private": {
                "icon": {"_name": "PrivateInsurance", "_classname": "option-card-icon"},
                "_label": "healthInsuranceOptions.private",
                "_default_message": "Private (non-employer) health insurance",
            },
            "medicaid": {
                "icon": {"_name": "Medicaid", "_classname": "option-card-icon"},
                "_label": "healthInsuranceOptions.medicaid",
                "_default_message": "Health First Colorado (Full Medicaid)",
            },
            "medicare": {
                "icon": {"_name": "Medicare", "_classname": "option-card-icon"},
                "_label": "healthInsuranceOptions.medicare",
                "_default_message": "Medicare",
            },
            "chp": {
                "icon": {"_name": "Chp", "_classname": "option-card-icon"},
                "_label": "healthInsuranceOptions.chp",
                "_default_message": "Child Health Plan Plus (CHP+)",
            },
            "emergency_medicaid": {
                "icon": {"_name": "Emergency_medicaid", "_classname": "option-card-icon"},
                "_label": "healthInsuranceOptions.emergency_medicaid",
                "_default_message": "Emergency Medicaid / Reproductive Health",
            },
            "family_planning": {
                "icon": {"_name": "Family_planning", "_classname": "option-card-icon"},
                "_label": "healthInsuranceOptions.family_planning",
                "_default_message": "Family Planning Limited Medicaid",
            },
            "va": {
                "icon": {"_name": "VA", "_classname": "option-card-icon"},
                "_label": "healthInsuranceOptions.va",
                "_default_message": "VA health care benefits",
            },
        },
        "them": {
            "none": {
                "icon": {"_name": "None", "_classname": "option-card-icon"},
                "_label": "healthInsuranceOptions.none-dont-know-they",
                "_default_message": "They don't have or know if they have health insurance",
            },
            "employer": {
                "icon": {"_name": "Employer", "_classname": "option-card-icon"},
                "_label": "healthInsuranceOptions.employer",
                "_default_message": "Employer-provided health insurance",
            },
            "private": {
                "icon": {"_name": "PrivateInsurance", "_classname": "option-card-icon"},
                "_label": "healthInsuranceOptions.private",
                "_default_message": "Private (non-employer) health insurance",
            },
            "medicaid": {
                "icon": {"_name": "Medicaid", "_classname": "option-card-icon"},
                "_label": "healthInsuranceOptions.medicaid",
                "_default_message": "Health First Colorado (Full Medicaid)",
            },
            "medicare": {
                "icon": {"_name": "Medicare", "_classname": "option-card-icon"},
                "_label": "healthInsuranceOptions.medicare",
                "_default_message": "Medicare",
            },
            "chp": {
                "icon": {"_name": "Chp", "_classname": "option-card-icon"},
                "_label": "healthInsuranceOptions.chp",
                "_default_message": "Child Health Plan Plus (CHP+)",
            },
            "emergency_medicaid": {
                "icon": {"_name": "Emergency_medicaid", "_classname": "option-card-icon"},
                "_label": "healthInsuranceOptions.emergency_medicaid",
                "_default_message": "Emergency Medicaid / Reproductive Health",
            },
            "family_planning": {
                "icon": {"_name": "Family_planning", "_classname": "option-card-icon"},
                "_label": "healthInsuranceOptions.family_planning",
                "_default_message": "Family Planning Limited Medicaid",
            },
            "va": {
                "icon": {"_name": "VA", "_classname": "option-card-icon"},
                "_label": "healthInsuranceOptions.va",
                "_default_message": "VA health care benefits",
            },
        },
    }

    frequency_options = {  # TODO: add how frequency options to income question
        "weekly": {"_label": "frequencyOptions.weekly", "_default_message": "every week"},
        "biweekly": {"_label": "frequencyOptions.biweekly", "_default_message": "every 2 weeks"},
        "semimonthly": {"_label": "frequencyOptions.semimonthly", "_default_message": "twice a month"},
        "monthly": {"_label": "frequencyOptions.monthly", "_default_message": "every month"},
        "hourly": {"_label": "frequencyOptions.hourly", "_default_message": "hourly"},
    }

    expense_options = {  # TODO: add expense types to expense question
        "rent": {"_label": "expenseOptions.rent", "_default_message": "Rent"},
        "telephone": {"_label": "expenseOptions.telephone", "_default_message": "Telephone"},
        "internet": {"_label": "expenseOptions.internet", "_default_message": "Internet"},
        "auto": {"_label": "expenseOptions.auto", "_default_message": "Auto Insurance Premium &/or Payment"},
        "otherUtilities": {"_label": "expenseOptions.otherUtilities", "_default_message": "Other Utilities"},
        "heating": {"_label": "expenseOptions.heating", "_default_message": "Heating"},
        "creditCard": {"_label": "expenseOptions.creditCard", "_default_message": "Credit Card Debt"},
        "mortgage": {"_label": "expenseOptions.mortgage", "_default_message": "Mortgage"},
        "propertyTax": {"_label": "expenseOptions.propertyTax", "_default_message": "Property Taxes"},
        "hoa": {"_label": "expenseOptions.hoa", "_default_message": "Homeowners or Condo Association Fees and Dues"},
        "homeownersInsurance": {
            "_label": "expenseOptions.homeownersInsurance",
            "_default_message": "Homeowners Insurance",
        },
        "medical": {"_label": "expenseOptions.medical", "_default_message": "Medical Insurance Premium &/or Bills"},
        "personalLoan": {"_label": "expenseOptions.personalLoan", "_default_message": "Personal Loan"},
        "studentLoans": {"_label": "expenseOptions.studentLoans", "_default_message": "Student Loans"},
        "cooling": {"_label": "expenseOptions.cooling", "_default_message": "Cooling"},
        "childCare": {"_label": "expenseOptions.childCare", "_default_message": "Child Care"},
        "childSupport": {"_label": "expenseOptions.childSupport", "_default_message": "Child Support (Paid)"},
        "dependentCare": {"_label": "expenseOptions.dependentCare", "_default_message": "Dependent Care"},
    }

    condition_options = {  # TODO: add condition options to member question
        "you": {
            "student": {
                "icon": {"_name": "Student", "_classname": "option-card-icon"},
                "_label": "conditionOptions.student",
                "_default_message": "Student at a college, university, or other post-secondary institution like a job-training program",
            },
            "pregnant": {
                "icon": {"_name": "Pregnant", "_classname": "option-card-icon"},
                "_label": "conditionOptions.pregnant",
                "_default_message": "Pregnant",
            },
            "blindOrVisuallyImpaired": {
                "icon": {"_name": "BlindOrVisuallyImpaired", "_classname": "option-card-icon"},
                "_label": "conditionOptions.blindOrVisuallyImpaired",
                "_default_message": "Blind or visually impaired",
            },
            "disabled": {
                "icon": {"_name": "Disabled", "_classname": "option-card-icon"},
                "_label": "conditionOptions.disabled",
                "_default_message": "Have any disabilities that make you unable to work now or in the future",
            },
            "longTermDisability": {
                "icon": {"_name": "LongTermDisability", "_classname": "option-card-icon"},
                "_label": "conditionOptions.longTermDisability",
                "_default_message": "Any medical or developmental condition that has lasted, or is expected to last, more than 12 months",
            },
        },
        "them": {
            "student": {
                "icon": {"_name": "Student", "_classname": "option-card-icon"},
                "_label": "conditionOptions.student",
                "_default_message": "Student at a college, university, or other post-secondary institution like a job-training program",
            },
            "pregnant": {
                "icon": {"_name": "Pregnant", "_classname": "option-card-icon"},
                "_label": "conditionOptions.pregnant",
                "_default_message": "Pregnant",
            },
            "blindOrVisuallyImpaired": {
                "icon": {"_name": "BlindOrVisuallyImpaired", "_classname": "option-card-icon"},
                "_label": "conditionOptions.blindOrVisuallyImpaired",
                "_default_message": "Blind or visually impaired",
            },
            "disabled": {
                "icon": {"_name": "Disabled", "_classname": "option-card-icon"},
                "_label": "conditionOptions.disabled",
                "_default_message": "Have any disabilities that make you unable to work now or in the future",
            },
            "longTermDisability": {
                "icon": {"_name": "LongTermDisability", "_classname": "option-card-icon"},
                "_label": "conditionOptions.longTermDisability",
                "_default_message": "Any medical or developmental condition that has lasted, or is expected to last, more than 12 months",
            },
        },
    }

    counties_by_zipcode = {
        "01001": {"Hampden County": "Hampden County"},
        "01002": {"Hampshire County": "Hampshire County", "Franklin County": "Franklin County"},
        "01003": {"Hampshire County": "Hampshire County"},
        "01004": {"Hampshire County": "Hampshire County"},
        "01005": {"Worcester County": "Worcester County"},
        "01007": {"Hampshire County": "Hampshire County"},
        "01008": {"Hampden County": "Hampden County", "Berkshire County": "Berkshire County"},
        "01009": {"Hampden County": "Hampden County"},
        "01010": {"Worcester County": "Worcester County", "Hampden County": "Hampden County"},
        "01011": {"Hampshire County": "Hampshire County", "Hampden County": "Hampden County"},
        "01012": {"Hampshire County": "Hampshire County"},
        "01013": {"Hampden County": "Hampden County"},
        "01014": {"Hampden County": "Hampden County"},
        "01020": {"Hampden County": "Hampden County"},
        "01021": {"Hampden County": "Hampden County"},
        "01022": {"Hampden County": "Hampden County"},
        "01026": {"Hampshire County": "Hampshire County", "Berkshire County": "Berkshire County"},
        "01027": {"Hampshire County": "Hampshire County"},
        "01028": {"Hampden County": "Hampden County"},
        "01029": {"Berkshire County": "Berkshire County"},
        "01030": {"Hampden County": "Hampden County"},
        "01031": {"Worcester County": "Worcester County"},
        "01032": {"Hampshire County": "Hampshire County"},
        "01033": {"Hampshire County": "Hampshire County"},
        "01034": {"Hampden County": "Hampden County"},
        "01035": {"Hampshire County": "Hampshire County"},
        "01036": {"Hampden County": "Hampden County"},
        "01037": {"Worcester County": "Worcester County"},
        "01038": {"Hampshire County": "Hampshire County"},
        "01039": {"Hampshire County": "Hampshire County", "Franklin County": "Franklin County"},
        "01040": {"Hampden County": "Hampden County"},
        "01041": {"Hampden County": "Hampden County"},
        "01050": {"Hampden County": "Hampden County", "Hampshire County": "Hampshire County"},
        "01053": {"Hampshire County": "Hampshire County"},
        "01054": {"Franklin County": "Franklin County"},
        "01056": {"Hampden County": "Hampden County"},
        "01057": {"Hampden County": "Hampden County"},
        "01059": {"Hampshire County": "Hampshire County"},
        "01060": {"Hampshire County": "Hampshire County"},
        "01061": {"Hampshire County": "Hampshire County"},
        "01062": {"Hampshire County": "Hampshire County"},
        "01063": {"Hampshire County": "Hampshire County"},
        "01066": {"Hampshire County": "Hampshire County"},
        "01068": {"Worcester County": "Worcester County"},
        "01069": {"Hampden County": "Hampden County"},
        "01070": {"Hampshire County": "Hampshire County"},
        "01071": {"Hampden County": "Hampden County"},
        "01072": {"Franklin County": "Franklin County"},
        "01073": {"Hampshire County": "Hampshire County"},
        "01074": {"Worcester County": "Worcester County"},
        "01075": {"Hampshire County": "Hampshire County"},
        "01077": {"Hampden County": "Hampden County"},
        "01079": {"Hampden County": "Hampden County"},
        "01080": {"Hampden County": "Hampden County"},
        "01081": {"Hampden County": "Hampden County"},
        "01082": {"Worcester County": "Worcester County", "Hampshire County": "Hampshire County"},
        "01083": {"Worcester County": "Worcester County"},
        "01084": {"Hampshire County": "Hampshire County"},
        "01085": {"Hampden County": "Hampden County"},
        "01086": {"Hampden County": "Hampden County"},
        "01088": {"Hampshire County": "Hampshire County"},
        "01089": {"Hampden County": "Hampden County"},
        "01090": {"Hampden County": "Hampden County"},
        "01092": {"Worcester County": "Worcester County"},
        "01093": {"Franklin County": "Franklin County"},
        "01094": {"Worcester County": "Worcester County"},
        "01095": {"Hampden County": "Hampden County"},
        "01096": {"Franklin County": "Franklin County", "Hampshire County": "Hampshire County"},
        "01097": {"Hampden County": "Hampden County"},
        "01098": {"Hampshire County": "Hampshire County"},
        "01101": {"Hampden County": "Hampden County"},
        "01102": {"Hampden County": "Hampden County"},
        "01103": {"Hampden County": "Hampden County"},
        "01104": {"Hampden County": "Hampden County"},
        "01105": {"Hampden County": "Hampden County"},
        "01106": {"Hampden County": "Hampden County"},
        "01107": {"Hampden County": "Hampden County"},
        "01108": {"Hampden County": "Hampden County"},
        "01109": {"Hampden County": "Hampden County"},
        "01111": {"Hampden County": "Hampden County"},
        "01114": {"Hampden County": "Hampden County"},
        "01115": {"Hampden County": "Hampden County"},
        "01116": {"Hampden County": "Hampden County"},
        "01118": {"Hampden County": "Hampden County"},
        "01119": {"Hampden County": "Hampden County"},
        "01128": {"Hampden County": "Hampden County"},
        "01129": {"Hampden County": "Hampden County"},
        "01138": {"Hampden County": "Hampden County"},
        "01139": {"Hampden County": "Hampden County"},
        "01144": {"Hampden County": "Hampden County"},
        "01151": {"Hampden County": "Hampden County"},
        "01152": {"Hampden County": "Hampden County"},
        "01189": {"Hampden County": "Hampden County"},
        "01199": {"Hampden County": "Hampden County"},
        "01201": {"Berkshire County": "Berkshire County"},
        "01202": {"Berkshire County": "Berkshire County"},
        "01203": {"Berkshire County": "Berkshire County"},
        "01220": {"Berkshire County": "Berkshire County"},
        "01222": {"Berkshire County": "Berkshire County"},
        "01223": {"Berkshire County": "Berkshire County"},
        "01224": {"Berkshire County": "Berkshire County"},
        "01225": {"Berkshire County": "Berkshire County"},
        "01226": {"Berkshire County": "Berkshire County"},
        "01227": {"Berkshire County": "Berkshire County"},
        "01229": {"Berkshire County": "Berkshire County"},
        "01230": {"Berkshire County": "Berkshire County"},
        "01235": {"Berkshire County": "Berkshire County", "Hampshire County": "Hampshire County"},
        "01236": {"Berkshire County": "Berkshire County"},
        "01237": {"Berkshire County": "Berkshire County"},
        "01238": {"Berkshire County": "Berkshire County"},
        "01240": {"Berkshire County": "Berkshire County"},
        "01242": {"Berkshire County": "Berkshire County"},
        "01243": {"Hampshire County": "Hampshire County"},
        "01244": {"Berkshire County": "Berkshire County"},
        "01245": {"Berkshire County": "Berkshire County"},
        "01247": {"Franklin County": "Franklin County", "Berkshire County": "Berkshire County"},
        "01252": {"Berkshire County": "Berkshire County"},
        "01253": {"Berkshire County": "Berkshire County"},
        "01254": {"Berkshire County": "Berkshire County"},
        "01255": {"Berkshire County": "Berkshire County"},
        "01256": {"Berkshire County": "Berkshire County"},
        "01257": {"Berkshire County": "Berkshire County"},
        "01258": {"Berkshire County": "Berkshire County"},
        "01259": {"Berkshire County": "Berkshire County"},
        "01260": {"Berkshire County": "Berkshire County"},
        "01262": {"Berkshire County": "Berkshire County"},
        "01263": {"Berkshire County": "Berkshire County"},
        "01264": {"Berkshire County": "Berkshire County"},
        "01266": {"Berkshire County": "Berkshire County"},
        "01267": {"Berkshire County": "Berkshire County"},
        "01270": {"Berkshire County": "Berkshire County"},
        "01301": {"Franklin County": "Franklin County"},
        "01302": {"Franklin County": "Franklin County"},
        "01330": {"Franklin County": "Franklin County"},
        "01331": {"Worcester County": "Worcester County"},
        "01337": {"Franklin County": "Franklin County"},
        "01338": {"Franklin County": "Franklin County"},
        "01339": {"Franklin County": "Franklin County"},
        "01340": {"Franklin County": "Franklin County"},
        "01341": {"Franklin County": "Franklin County"},
        "01342": {"Franklin County": "Franklin County"},
        "01343": {"Berkshire County": "Berkshire County"},
        "01344": {"Franklin County": "Franklin County"},
        "01346": {"Franklin County": "Franklin County"},
        "01347": {"Franklin County": "Franklin County"},
        "01349": {"Franklin County": "Franklin County"},
        "01350": {"Franklin County": "Franklin County"},
        "01351": {"Franklin County": "Franklin County"},
        "01354": {"Franklin County": "Franklin County"},
        "01355": {"Franklin County": "Franklin County"},
        "01360": {"Franklin County": "Franklin County"},
        "01364": {"Franklin County": "Franklin County"},
        "01366": {"Worcester County": "Worcester County"},
        "01367": {"Franklin County": "Franklin County"},
        "01368": {"Worcester County": "Worcester County"},
        "01370": {"Franklin County": "Franklin County"},
        "01373": {"Franklin County": "Franklin County"},
        "01375": {"Franklin County": "Franklin County"},
        "01376": {"Franklin County": "Franklin County"},
        "01378": {"Franklin County": "Franklin County"},
        "01379": {"Franklin County": "Franklin County"},
        "01380": {"Franklin County": "Franklin County"},
        "01420": {"Worcester County": "Worcester County"},
        "01430": {"Worcester County": "Worcester County"},
        "01431": {"Middlesex County": "Middlesex County"},
        "01432": {"Middlesex County": "Middlesex County"},
        "01434": {"Worcester County": "Worcester County", "Middlesex County": "Middlesex County"},
        "01436": {"Worcester County": "Worcester County"},
        "01438": {"Worcester County": "Worcester County"},
        "01440": {"Worcester County": "Worcester County"},
        "01441": {"Worcester County": "Worcester County"},
        "01450": {"Middlesex County": "Middlesex County"},
        "01451": {"Worcester County": "Worcester County"},
        "01452": {"Worcester County": "Worcester County"},
        "01453": {"Worcester County": "Worcester County"},
        "01460": {"Middlesex County": "Middlesex County"},
        "01462": {"Worcester County": "Worcester County"},
        "01463": {"Middlesex County": "Middlesex County"},
        "01464": {"Middlesex County": "Middlesex County"},
        "01467": {"Worcester County": "Worcester County"},
        "01468": {"Worcester County": "Worcester County"},
        "01469": {"Middlesex County": "Middlesex County"},
        "01470": {"Middlesex County": "Middlesex County"},
        "01471": {"Middlesex County": "Middlesex County"},
        "01472": {"Middlesex County": "Middlesex County"},
        "01473": {"Worcester County": "Worcester County"},
        "01474": {"Middlesex County": "Middlesex County"},
        "01475": {"Worcester County": "Worcester County"},
        "01477": {"Worcester County": "Worcester County"},
        "01501": {"Worcester County": "Worcester County"},
        "01503": {"Worcester County": "Worcester County"},
        "01504": {"Worcester County": "Worcester County"},
        "01505": {"Worcester County": "Worcester County"},
        "01506": {"Worcester County": "Worcester County"},
        "01507": {"Worcester County": "Worcester County"},
        "01508": {"Worcester County": "Worcester County"},
        "01509": {"Worcester County": "Worcester County"},
        "01510": {"Worcester County": "Worcester County"},
        "01515": {"Worcester County": "Worcester County"},
        "01516": {"Worcester County": "Worcester County"},
        "01517": {"Worcester County": "Worcester County"},
        "01518": {"Worcester County": "Worcester County"},
        "01519": {"Worcester County": "Worcester County"},
        "01520": {"Worcester County": "Worcester County"},
        "01521": {"Hampden County": "Hampden County"},
        "01522": {"Worcester County": "Worcester County"},
        "01523": {"Worcester County": "Worcester County"},
        "01524": {"Worcester County": "Worcester County"},
        "01525": {"Worcester County": "Worcester County"},
        "01526": {"Worcester County": "Worcester County"},
        "01527": {"Worcester County": "Worcester County"},
        "01529": {"Worcester County": "Worcester County"},
        "01531": {"Worcester County": "Worcester County"},
        "01532": {"Worcester County": "Worcester County"},
        "01534": {"Worcester County": "Worcester County"},
        "01535": {"Worcester County": "Worcester County"},
        "01536": {"Worcester County": "Worcester County"},
        "01537": {"Worcester County": "Worcester County"},
        "01538": {"Worcester County": "Worcester County"},
        "01540": {"Worcester County": "Worcester County"},
        "01541": {"Worcester County": "Worcester County"},
        "01542": {"Worcester County": "Worcester County"},
        "01543": {"Worcester County": "Worcester County"},
        "01545": {"Worcester County": "Worcester County"},
        "01546": {"Worcester County": "Worcester County"},
        "01550": {"Worcester County": "Worcester County"},
        "01560": {"Worcester County": "Worcester County"},
        "01561": {"Worcester County": "Worcester County"},
        "01562": {"Worcester County": "Worcester County"},
        "01564": {"Worcester County": "Worcester County"},
        "01566": {"Worcester County": "Worcester County"},
        "01568": {"Worcester County": "Worcester County"},
        "01569": {"Worcester County": "Worcester County"},
        "01570": {"Worcester County": "Worcester County"},
        "01571": {"Worcester County": "Worcester County"},
        "01580": {"Worcester County": "Worcester County"},
        "01581": {"Worcester County": "Worcester County"},
        "01582": {"Worcester County": "Worcester County"},
        "01583": {"Worcester County": "Worcester County"},
        "01585": {"Worcester County": "Worcester County"},
        "01586": {"Worcester County": "Worcester County"},
        "01587": {"Worcester County": "Worcester County"},
        "01588": {"Worcester County": "Worcester County"},
        "01590": {"Worcester County": "Worcester County"},
        "01601": {"Worcester County": "Worcester County"},
        "01602": {"Worcester County": "Worcester County"},
        "01603": {"Worcester County": "Worcester County"},
        "01604": {"Worcester County": "Worcester County"},
        "01605": {"Worcester County": "Worcester County"},
        "01606": {"Worcester County": "Worcester County"},
        "01607": {"Worcester County": "Worcester County"},
        "01608": {"Worcester County": "Worcester County"},
        "01609": {"Worcester County": "Worcester County"},
        "01610": {"Worcester County": "Worcester County"},
        "01611": {"Worcester County": "Worcester County"},
        "01612": {"Worcester County": "Worcester County"},
        "01613": {"Worcester County": "Worcester County"},
        "01614": {"Worcester County": "Worcester County"},
        "01615": {"Worcester County": "Worcester County"},
        "01616": {"Worcester County": "Worcester County"},
        "01653": {"Worcester County": "Worcester County"},
        "01654": {"Worcester County": "Worcester County"},
        "01655": {"Worcester County": "Worcester County"},
        "01701": {"Middlesex County": "Middlesex County"},
        "01702": {"Middlesex County": "Middlesex County"},
        "01703": {"Middlesex County": "Middlesex County"},
        "01704": {"Middlesex County": "Middlesex County"},
        "01705": {"Middlesex County": "Middlesex County"},
        "01718": {"Middlesex County": "Middlesex County"},
        "01719": {"Middlesex County": "Middlesex County"},
        "01720": {"Middlesex County": "Middlesex County"},
        "01721": {"Middlesex County": "Middlesex County"},
        "01730": {"Middlesex County": "Middlesex County"},
        "01731": {"Middlesex County": "Middlesex County"},
        "01740": {"Worcester County": "Worcester County"},
        "01741": {"Middlesex County": "Middlesex County"},
        "01742": {"Middlesex County": "Middlesex County"},
        "01745": {"Worcester County": "Worcester County"},
        "01746": {"Middlesex County": "Middlesex County"},
        "01747": {"Worcester County": "Worcester County"},
        "01748": {"Middlesex County": "Middlesex County"},
        "01749": {"Middlesex County": "Middlesex County"},
        "01752": {"Middlesex County": "Middlesex County"},
        "01754": {"Middlesex County": "Middlesex County"},
        "01756": {"Worcester County": "Worcester County"},
        "01757": {"Worcester County": "Worcester County"},
        "01760": {"Middlesex County": "Middlesex County"},
        "01770": {"Middlesex County": "Middlesex County"},
        "01772": {"Worcester County": "Worcester County"},
        "01773": {"Middlesex County": "Middlesex County"},
        "01775": {"Middlesex County": "Middlesex County"},
        "01776": {"Middlesex County": "Middlesex County"},
        "01778": {"Middlesex County": "Middlesex County"},
        "01784": {"Middlesex County": "Middlesex County"},
        "01801": {"Middlesex County": "Middlesex County"},
        "01803": {"Middlesex County": "Middlesex County"},
        "01805": {"Middlesex County": "Middlesex County"},
        "01807": {"Middlesex County": "Middlesex County"},
        "01808": {"Middlesex County": "Middlesex County"},
        "01810": {"Essex County": "Essex County"},
        "01812": {"Essex County": "Essex County"},
        "01813": {"Middlesex County": "Middlesex County"},
        "01815": {"Middlesex County": "Middlesex County"},
        "01821": {"Middlesex County": "Middlesex County"},
        "01822": {"Middlesex County": "Middlesex County"},
        "01823": {"Essex County": "Essex County"},
        "01824": {"Middlesex County": "Middlesex County"},
        "01826": {"Middlesex County": "Middlesex County"},
        "01827": {"Middlesex County": "Middlesex County"},
        "01830": {"Essex County": "Essex County"},
        "01831": {"Essex County": "Essex County"},
        "01832": {"Essex County": "Essex County"},
        "01833": {"Essex County": "Essex County"},
        "01834": {"Essex County": "Essex County"},
        "01835": {"Essex County": "Essex County"},
        "01840": {"Essex County": "Essex County"},
        "01841": {"Essex County": "Essex County"},
        "01842": {"Essex County": "Essex County"},
        "01843": {"Essex County": "Essex County"},
        "01844": {"Essex County": "Essex County"},
        "01845": {"Essex County": "Essex County"},
        "01850": {"Middlesex County": "Middlesex County"},
        "01851": {"Middlesex County": "Middlesex County"},
        "01852": {"Middlesex County": "Middlesex County"},
        "01853": {"Middlesex County": "Middlesex County"},
        "01854": {"Middlesex County": "Middlesex County"},
        "01856": {"Middlesex County": "Middlesex County"},
        "01860": {"Essex County": "Essex County"},
        "01862": {"Middlesex County": "Middlesex County"},
        "01863": {"Middlesex County": "Middlesex County"},
        "01864": {"Middlesex County": "Middlesex County"},
        "01865": {"Middlesex County": "Middlesex County"},
        "01866": {"Middlesex County": "Middlesex County"},
        "01867": {"Middlesex County": "Middlesex County"},
        "01876": {"Middlesex County": "Middlesex County"},
        "01878": {"Middlesex County": "Middlesex County"},
        "01879": {"Middlesex County": "Middlesex County"},
        "01880": {"Middlesex County": "Middlesex County"},
        "01885": {"Essex County": "Essex County"},
        "01886": {"Middlesex County": "Middlesex County"},
        "01887": {"Middlesex County": "Middlesex County"},
        "01888": {"Middlesex County": "Middlesex County"},
        "01889": {"Middlesex County": "Middlesex County"},
        "01890": {"Middlesex County": "Middlesex County"},
        "01899": {"Essex County": "Essex County"},
        "01901": {"Essex County": "Essex County"},
        "01902": {"Essex County": "Essex County"},
        "01903": {"Essex County": "Essex County"},
        "01904": {"Essex County": "Essex County"},
        "01905": {"Essex County": "Essex County"},
        "01906": {"Essex County": "Essex County"},
        "01907": {"Essex County": "Essex County"},
        "01908": {"Essex County": "Essex County"},
        "01910": {"Essex County": "Essex County"},
        "01913": {"Essex County": "Essex County"},
        "01915": {"Essex County": "Essex County"},
        "01921": {"Essex County": "Essex County"},
        "01922": {"Essex County": "Essex County"},
        "01923": {"Essex County": "Essex County"},
        "01929": {"Essex County": "Essex County"},
        "01930": {"Essex County": "Essex County"},
        "01931": {"Essex County": "Essex County"},
        "01936": {"Essex County": "Essex County"},
        "01937": {"Essex County": "Essex County"},
        "01938": {"Essex County": "Essex County"},
        "01940": {"Essex County": "Essex County"},
        "01944": {"Essex County": "Essex County"},
        "01945": {"Essex County": "Essex County"},
        "01947": {"Essex County": "Essex County"},
        "01949": {"Essex County": "Essex County"},
        "01950": {"Essex County": "Essex County"},
        "01951": {"Essex County": "Essex County"},
        "01952": {"Essex County": "Essex County"},
        "01960": {"Essex County": "Essex County"},
        "01961": {"Essex County": "Essex County"},
        "01965": {"Essex County": "Essex County"},
        "01966": {"Essex County": "Essex County"},
        "01969": {"Essex County": "Essex County"},
        "01970": {"Essex County": "Essex County"},
        "01971": {"Essex County": "Essex County"},
        "01982": {"Essex County": "Essex County"},
        "01983": {"Essex County": "Essex County"},
        "01984": {"Essex County": "Essex County"},
        "01985": {"Essex County": "Essex County"},
        "02018": {"Plymouth County": "Plymouth County"},
        "02019": {"Norfolk County": "Norfolk County"},
        "02020": {"Plymouth County": "Plymouth County"},
        "02021": {"Norfolk County": "Norfolk County"},
        "02025": {"Norfolk County": "Norfolk County"},
        "02026": {"Norfolk County": "Norfolk County"},
        "02027": {"Norfolk County": "Norfolk County"},
        "02030": {"Norfolk County": "Norfolk County"},
        "02031": {"Bristol County": "Bristol County"},
        "02032": {"Norfolk County": "Norfolk County"},
        "02035": {"Norfolk County": "Norfolk County"},
        "02038": {"Norfolk County": "Norfolk County"},
        "02040": {"Plymouth County": "Plymouth County"},
        "02041": {"Plymouth County": "Plymouth County"},
        "02043": {"Plymouth County": "Plymouth County"},
        "02044": {"Plymouth County": "Plymouth County"},
        "02045": {"Plymouth County": "Plymouth County"},
        "02047": {"Plymouth County": "Plymouth County"},
        "02048": {"Bristol County": "Bristol County"},
        "02050": {"Plymouth County": "Plymouth County"},
        "02051": {"Plymouth County": "Plymouth County"},
        "02052": {"Norfolk County": "Norfolk County"},
        "02053": {"Norfolk County": "Norfolk County"},
        "02054": {"Norfolk County": "Norfolk County"},
        "02055": {"Plymouth County": "Plymouth County"},
        "02056": {"Norfolk County": "Norfolk County"},
        "02059": {"Plymouth County": "Plymouth County"},
        "02060": {"Plymouth County": "Plymouth County"},
        "02061": {"Plymouth County": "Plymouth County"},
        "02062": {"Norfolk County": "Norfolk County"},
        "02065": {"Plymouth County": "Plymouth County"},
        "02066": {"Plymouth County": "Plymouth County"},
        "02067": {"Norfolk County": "Norfolk County"},
        "02070": {"Norfolk County": "Norfolk County"},
        "02071": {"Norfolk County": "Norfolk County"},
        "02072": {"Norfolk County": "Norfolk County"},
        "02081": {"Norfolk County": "Norfolk County"},
        "02090": {"Norfolk County": "Norfolk County"},
        "02091": {"Norfolk County": "Norfolk County"},
        "02093": {"Norfolk County": "Norfolk County"},
        "02101": {"Suffolk County": "Suffolk County"},
        "02102": {"Suffolk County": "Suffolk County"},
        "02103": {"Suffolk County": "Suffolk County"},
        "02104": {"Suffolk County": "Suffolk County"},
        "02105": {"Suffolk County": "Suffolk County"},
        "02106": {"Suffolk County": "Suffolk County"},
        "02107": {"Suffolk County": "Suffolk County"},
        "02108": {"Suffolk County": "Suffolk County"},
        "02109": {"Suffolk County": "Suffolk County"},
        "02110": {"Suffolk County": "Suffolk County"},
        "02111": {"Suffolk County": "Suffolk County"},
        "02112": {"Suffolk County": "Suffolk County"},
        "02113": {"Suffolk County": "Suffolk County"},
        "02114": {"Suffolk County": "Suffolk County"},
        "02115": {"Suffolk County": "Suffolk County"},
        "02116": {"Suffolk County": "Suffolk County"},
        "02117": {"Suffolk County": "Suffolk County"},
        "02118": {"Suffolk County": "Suffolk County"},
        "02119": {"Suffolk County": "Suffolk County"},
        "02120": {"Suffolk County": "Suffolk County"},
        "02121": {"Suffolk County": "Suffolk County"},
        "02122": {"Suffolk County": "Suffolk County"},
        "02123": {"Suffolk County": "Suffolk County"},
        "02124": {"Suffolk County": "Suffolk County"},
        "02125": {"Suffolk County": "Suffolk County"},
        "02126": {"Suffolk County": "Suffolk County"},
        "02127": {"Suffolk County": "Suffolk County"},
        "02128": {"Suffolk County": "Suffolk County"},
        "02129": {"Suffolk County": "Suffolk County"},
        "02130": {"Suffolk County": "Suffolk County"},
        "02131": {"Suffolk County": "Suffolk County"},
        "02132": {"Suffolk County": "Suffolk County"},
        "02133": {"Suffolk County": "Suffolk County"},
        "02134": {"Suffolk County": "Suffolk County"},
        "02135": {"Suffolk County": "Suffolk County"},
        "02136": {"Suffolk County": "Suffolk County"},
        "02137": {"Suffolk County": "Suffolk County"},
        "02138": {"Middlesex County": "Middlesex County"},
        "02139": {"Middlesex County": "Middlesex County"},
        "02140": {"Middlesex County": "Middlesex County"},
        "02141": {"Middlesex County": "Middlesex County"},
        "02142": {"Middlesex County": "Middlesex County"},
        "02143": {"Middlesex County": "Middlesex County"},
        "02144": {"Middlesex County": "Middlesex County"},
        "02145": {"Middlesex County": "Middlesex County"},
        "02146": {"Norfolk County": "Norfolk County"},
        "02148": {"Middlesex County": "Middlesex County"},
        "02149": {"Middlesex County": "Middlesex County"},
        "02150": {"Suffolk County": "Suffolk County"},
        "02151": {"Suffolk County": "Suffolk County"},
        "02152": {"Suffolk County": "Suffolk County"},
        "02153": {"Middlesex County": "Middlesex County"},
        "02154": {"Middlesex County": "Middlesex County"},
        "02155": {"Middlesex County": "Middlesex County"},
        "02156": {"Middlesex County": "Middlesex County"},
        "02158": {"Middlesex County": "Middlesex County"},
        "02160": {"Middlesex County": "Middlesex County"},
        "02161": {"Middlesex County": "Middlesex County"},
        "02162": {"Middlesex County": "Middlesex County"},
        "02163": {"Suffolk County": "Suffolk County"},
        "02164": {"Middlesex County": "Middlesex County"},
        "02167": {"Middlesex County": "Middlesex County"},
        "02168": {"Middlesex County": "Middlesex County"},
        "02169": {"Norfolk County": "Norfolk County"},
        "02170": {"Norfolk County": "Norfolk County"},
        "02171": {"Norfolk County": "Norfolk County"},
        "02172": {"Middlesex County": "Middlesex County"},
        "02174": {"Middlesex County": "Middlesex County"},
        "02176": {"Middlesex County": "Middlesex County"},
        "02178": {"Middlesex County": "Middlesex County"},
        "02180": {"Middlesex County": "Middlesex County"},
        "02181": {"Norfolk County": "Norfolk County"},
        "02184": {"Norfolk County": "Norfolk County"},
        "02185": {"Norfolk County": "Norfolk County"},
        "02186": {"Norfolk County": "Norfolk County"},
        "02187": {"Norfolk County": "Norfolk County"},
        "02188": {"Norfolk County": "Norfolk County"},
        "02189": {"Norfolk County": "Norfolk County"},
        "02190": {"Norfolk County": "Norfolk County"},
        "02191": {"Norfolk County": "Norfolk County"},
        "02192": {"Norfolk County": "Norfolk County"},
        "02193": {"Middlesex County": "Middlesex County"},
        "02194": {"Norfolk County": "Norfolk County"},
        "02196": {"Suffolk County": "Suffolk County"},
        "02199": {"Suffolk County": "Suffolk County"},
        "02201": {"Suffolk County": "Suffolk County"},
        "02203": {"Suffolk County": "Suffolk County"},
        "02204": {"Suffolk County": "Suffolk County"},
        "02205": {"Suffolk County": "Suffolk County"},
        "02206": {"Suffolk County": "Suffolk County"},
        "02210": {"Suffolk County": "Suffolk County"},
        "02211": {"Suffolk County": "Suffolk County"},
        "02212": {"Suffolk County": "Suffolk County"},
        "02215": {"Suffolk County": "Suffolk County"},
        "02216": {"Suffolk County": "Suffolk County"},
        "02217": {"Suffolk County": "Suffolk County"},
        "02218": {"Suffolk County": "Suffolk County"},
        "02222": {"Suffolk County": "Suffolk County"},
        "02228": {"Suffolk County": "Suffolk County"},
        "02238": {"Middlesex County": "Middlesex County"},
        "02241": {"Suffolk County": "Suffolk County"},
        "02246": {"Norfolk County": "Norfolk County"},
        "02254": {"Nantucket County": "Nantucket County"},
        "02266": {"Suffolk County": "Suffolk County"},
        "02269": {"Norfolk County": "Norfolk County"},
        "02295": {"Suffolk County": "Suffolk County"},
        "02297": {"Suffolk County": "Suffolk County"},
        "02298": {"Suffolk County": "Suffolk County"},
        "02301": {"Plymouth County": "Plymouth County"},
        "02302": {"Plymouth County": "Plymouth County"},
        "02303": {"Plymouth County": "Plymouth County"},
        "02304": {"Plymouth County": "Plymouth County"},
        "02305": {"Plymouth County": "Plymouth County"},
        "02315": {"Suffolk County": "Suffolk County"},
        "02322": {"Norfolk County": "Norfolk County"},
        "02324": {"Plymouth County": "Plymouth County"},
        "02325": {"Plymouth County": "Plymouth County"},
        "02327": {"Plymouth County": "Plymouth County"},
        "02330": {"Plymouth County": "Plymouth County"},
        "02331": {"Plymouth County": "Plymouth County"},
        "02332": {"Plymouth County": "Plymouth County"},
        "02333": {"Plymouth County": "Plymouth County"},
        "02334": {"Bristol County": "Bristol County"},
        "02337": {"Plymouth County": "Plymouth County"},
        "02338": {"Plymouth County": "Plymouth County"},
        "02339": {"Plymouth County": "Plymouth County"},
        "02340": {"Plymouth County": "Plymouth County"},
        "02341": {"Plymouth County": "Plymouth County"},
        "02343": {"Norfolk County": "Norfolk County"},
        "02344": {"Bristol County": "Bristol County"},
        "02345": {"Plymouth County": "Plymouth County"},
        "02346": {"Plymouth County": "Plymouth County"},
        "02347": {"Plymouth County": "Plymouth County"},
        "02348": {"Plymouth County": "Plymouth County"},
        "02349": {"Plymouth County": "Plymouth County"},
        "02350": {"Plymouth County": "Plymouth County"},
        "02351": {"Plymouth County": "Plymouth County"},
        "02355": {"Plymouth County": "Plymouth County"},
        "02356": {"Bristol County": "Bristol County"},
        "02357": {"Bristol County": "Bristol County"},
        "02358": {"Plymouth County": "Plymouth County"},
        "02359": {"Plymouth County": "Plymouth County"},
        "02360": {"Plymouth County": "Plymouth County"},
        "02361": {"Plymouth County": "Plymouth County"},
        "02362": {"Plymouth County": "Plymouth County"},
        "02364": {"Plymouth County": "Plymouth County"},
        "02366": {"Plymouth County": "Plymouth County"},
        "02367": {"Plymouth County": "Plymouth County"},
        "02368": {"Norfolk County": "Norfolk County"},
        "02370": {"Plymouth County": "Plymouth County"},
        "02375": {"Bristol County": "Bristol County"},
        "02379": {"Plymouth County": "Plymouth County"},
        "02381": {"Plymouth County": "Plymouth County"},
        "02382": {"Plymouth County": "Plymouth County"},
        "02383": {"Plymouth County": "Plymouth County"},
        "02401": {"Plymouth County": "Plymouth County"},
        "02402": {"Plymouth County": "Plymouth County"},
        "02408": {"Suffolk County": "Suffolk County"},
        "02415": {"Middlesex County": "Middlesex County"},
        "02420": {"Middlesex County": "Middlesex County"},
        "02421": {"Middlesex County": "Middlesex County"},
        "02445": {"Norfolk County": "Norfolk County"},
        "02446": {"Norfolk County": "Norfolk County"},
        "02447": {"Norfolk County": "Norfolk County"},
        "02451": {"Middlesex County": "Middlesex County"},
        "02452": {"Middlesex County": "Middlesex County"},
        "02453": {"Middlesex County": "Middlesex County"},
        "02454": {"Middlesex County": "Middlesex County"},
        "02455": {"Middlesex County": "Middlesex County"},
        "02456": {"Middlesex County": "Middlesex County"},
        "02457": {"Norfolk County": "Norfolk County"},
        "02458": {"Middlesex County": "Middlesex County"},
        "02459": {"Middlesex County": "Middlesex County"},
        "02460": {"Middlesex County": "Middlesex County"},
        "02461": {"Middlesex County": "Middlesex County"},
        "02462": {"Middlesex County": "Middlesex County"},
        "02464": {"Middlesex County": "Middlesex County"},
        "02465": {"Middlesex County": "Middlesex County"},
        "02466": {"Middlesex County": "Middlesex County"},
        "02467": {
            "Norfolk County": "Norfolk County",
            "Suffolk County": "Suffolk County",
            "Middlesex County": "Middlesex County",
        },
        "02468": {"Middlesex County": "Middlesex County"},
        "02471": {"Middlesex County": "Middlesex County"},
        "02472": {"Middlesex County": "Middlesex County"},
        "02474": {"Middlesex County": "Middlesex County"},
        "02475": {"Middlesex County": "Middlesex County"},
        "02476": {"Middlesex County": "Middlesex County"},
        "02477": {"Middlesex County": "Middlesex County"},
        "02478": {"Middlesex County": "Middlesex County"},
        "02479": {"Middlesex County": "Middlesex County"},
        "02481": {"Norfolk County": "Norfolk County"},
        "02482": {"Norfolk County": "Norfolk County"},
        "02492": {"Norfolk County": "Norfolk County"},
        "02493": {"Middlesex County": "Middlesex County"},
        "02494": {"Norfolk County": "Norfolk County"},
        "02495": {"Middlesex County": "Middlesex County"},
        "02532": {"Plymouth County": "Plymouth County", "Barnstable County": "Barnstable County"},
        "02534": {"Barnstable County": "Barnstable County"},
        "02535": {"Dukes County": "Dukes County"},
        "02536": {"Barnstable County": "Barnstable County"},
        "02537": {"Barnstable County": "Barnstable County"},
        "02538": {"Plymouth County": "Plymouth County"},
        "02539": {"Dukes County": "Dukes County"},
        "02540": {"Barnstable County": "Barnstable County"},
        "02541": {"Barnstable County": "Barnstable County"},
        "02542": {"Barnstable County": "Barnstable County"},
        "02543": {"Barnstable County": "Barnstable County"},
        "02552": {"Dukes County": "Dukes County"},
        "02553": {"Barnstable County": "Barnstable County"},
        "02554": {"Nantucket County": "Nantucket County"},
        "02556": {"Barnstable County": "Barnstable County"},
        "02557": {"Dukes County": "Dukes County"},
        "02558": {"Plymouth County": "Plymouth County"},
        "02559": {"Barnstable County": "Barnstable County"},
        "02561": {"Barnstable County": "Barnstable County"},
        "02562": {"Barnstable County": "Barnstable County"},
        "02563": {"Barnstable County": "Barnstable County"},
        "02564": {"Nantucket County": "Nantucket County"},
        "02565": {"Barnstable County": "Barnstable County"},
        "02568": {"Dukes County": "Dukes County"},
        "02571": {"Plymouth County": "Plymouth County"},
        "02573": {"Dukes County": "Dukes County"},
        "02574": {"Barnstable County": "Barnstable County"},
        "02575": {"Dukes County": "Dukes County"},
        "02576": {"Plymouth County": "Plymouth County"},
        "02584": {"Nantucket County": "Nantucket County"},
        "02601": {"Barnstable County": "Barnstable County"},
        "02630": {"Barnstable County": "Barnstable County"},
        "02631": {"Barnstable County": "Barnstable County"},
        "02632": {"Barnstable County": "Barnstable County"},
        "02633": {"Barnstable County": "Barnstable County"},
        "02634": {"Barnstable County": "Barnstable County"},
        "02635": {"Barnstable County": "Barnstable County"},
        "02636": {"Barnstable County": "Barnstable County"},
        "02637": {"Barnstable County": "Barnstable County"},
        "02638": {"Barnstable County": "Barnstable County"},
        "02639": {"Barnstable County": "Barnstable County"},
        "02641": {"Barnstable County": "Barnstable County"},
        "02642": {"Barnstable County": "Barnstable County"},
        "02643": {"Barnstable County": "Barnstable County"},
        "02644": {"Barnstable County": "Barnstable County"},
        "02645": {"Barnstable County": "Barnstable County"},
        "02646": {"Barnstable County": "Barnstable County"},
        "02647": {"Barnstable County": "Barnstable County"},
        "02648": {"Barnstable County": "Barnstable County"},
        "02649": {"Barnstable County": "Barnstable County"},
        "02650": {"Barnstable County": "Barnstable County"},
        "02651": {"Barnstable County": "Barnstable County"},
        "02652": {"Barnstable County": "Barnstable County"},
        "02653": {"Barnstable County": "Barnstable County"},
        "02655": {"Barnstable County": "Barnstable County"},
        "02657": {"Barnstable County": "Barnstable County"},
        "02659": {"Barnstable County": "Barnstable County"},
        "02660": {"Barnstable County": "Barnstable County"},
        "02661": {"Barnstable County": "Barnstable County"},
        "02662": {"Barnstable County": "Barnstable County"},
        "02663": {"Barnstable County": "Barnstable County"},
        "02664": {"Barnstable County": "Barnstable County"},
        "02666": {"Barnstable County": "Barnstable County"},
        "02667": {"Barnstable County": "Barnstable County"},
        "02668": {"Barnstable County": "Barnstable County"},
        "02669": {"Barnstable County": "Barnstable County"},
        "02670": {"Barnstable County": "Barnstable County"},
        "02671": {"Barnstable County": "Barnstable County"},
        "02672": {"Barnstable County": "Barnstable County"},
        "02673": {"Barnstable County": "Barnstable County"},
        "02675": {"Barnstable County": "Barnstable County"},
        "02702": {"Bristol County": "Bristol County"},
        "02703": {"Bristol County": "Bristol County"},
        "02712": {"Bristol County": "Bristol County"},
        "02713": {"Dukes County": "Dukes County"},
        "02714": {"Bristol County": "Bristol County"},
        "02715": {"Bristol County": "Bristol County"},
        "02717": {"Bristol County": "Bristol County"},
        "02718": {"Bristol County": "Bristol County"},
        "02719": {"Bristol County": "Bristol County"},
        "02720": {"Bristol County": "Bristol County"},
        "02721": {"Bristol County": "Bristol County"},
        "02722": {"Bristol County": "Bristol County"},
        "02723": {"Bristol County": "Bristol County"},
        "02724": {"Bristol County": "Bristol County"},
        "02725": {"Bristol County": "Bristol County"},
        "02726": {"Bristol County": "Bristol County"},
        "02738": {"Plymouth County": "Plymouth County"},
        "02739": {"Plymouth County": "Plymouth County"},
        "02740": {"Bristol County": "Bristol County"},
        "02741": {"Bristol County": "Bristol County"},
        "02742": {"Bristol County": "Bristol County"},
        "02743": {"Bristol County": "Bristol County"},
        "02744": {"Bristol County": "Bristol County"},
        "02745": {"Bristol County": "Bristol County"},
        "02746": {"Bristol County": "Bristol County"},
        "02747": {"Bristol County": "Bristol County"},
        "02748": {"Bristol County": "Bristol County"},
        "02751": {"Plymouth County": "Plymouth County"},
        "02756": {"Plymouth County": "Plymouth County"},
        "02760": {"Bristol County": "Bristol County"},
        "02761": {"Bristol County": "Bristol County"},
        "02762": {"Norfolk County": "Norfolk County"},
        "02763": {"Bristol County": "Bristol County"},
        "02764": {"Bristol County": "Bristol County"},
        "02766": {"Bristol County": "Bristol County"},
        "02767": {"Bristol County": "Bristol County"},
        "02768": {"Bristol County": "Bristol County"},
        "02769": {"Bristol County": "Bristol County"},
        "02770": {"Plymouth County": "Plymouth County"},
        "02771": {"Bristol County": "Bristol County"},
        "02777": {"Bristol County": "Bristol County"},
        "02779": {"Bristol County": "Bristol County"},
        "02780": {"Bristol County": "Bristol County"},
        "02783": {"Bristol County": "Bristol County"},
        "02790": {"Bristol County": "Bristol County"},
        "02791": {"Bristol County": "Bristol County"},
        "05501": {"Essex County": "Essex County"},
        "05544": {"Essex County": "Essex County"},
    }

    category_benefits = {  # TODO: add benefits and benefit categories to the already has benefits step
        "[REPLACE_ME]": {
            "benefits": {
                "[REPLACE_ME]": {
                    "name": {
                        "_label": "",
                        "_default_message": "",
                    },
                    "description": {
                        "_label": "",
                        "_default_message": "",
                    },
                },
            },
            "category_name": {"_label": "", "_default_message": ""},
        },
    }

    consent_to_contact = {  # TODO: add consent to contact links
        "en-us": "",
        "[REPLACE_ME]": "",
    }

    privacy_policy = {  # TODO: add privacy policy links
        "en-us": "",
        "[REPLACE_ME]": "",
    }

    referrer_data = {
        "theme": {"default": "default"},
        "logoSource": {
            "default": "MFB_MALogo",
        },
        "logoAlt": {
            "default": {"id": "referrerHook.logoAlts.default", "defaultMessage": "MyFriendBen home page button"},
        },
        "logoFooterSource": {"default": "MFB_Logo"},
        "logoFooterAlt": {
            "default": {"id": "footer.logo.alt", "defaultMessage": "MFB Logo"},
        },
        "logoClass": {"default": "logo"},
        "shareLink": {  # TODO: change share link based on referrer
            "default": "",
        },
        "stepDirectory": {
            "default": [
                "zipcode",
                # the hhSize and hhData have to be consecutive
                # "householdSize",
                # "householdData",  # TODO: set up the household data config
                "hasExpenses",
                "householdAssets",
                "hasBenefits",
                "acuteHHConditions",
                "referralSource",
                "signUpInfo",
            ],
        },
        "featureFlags": {"default": []},
        "noResultMessage": {
            "default": {
                "_label": "noResultMessage",
                "_default_message": "It looks like you may not qualify for benefits included in MyFriendBen at this time. If you indicated need for an immediate resource, please click on the “Near-Term Benefits” tab. For additional resources, please click the 'More Help' button below to get the resources you’re looking for.",
            },
        },
    }

    footer_data = {  # TODO: add footer information
        "address_one": "",
        "address_two": "",
        "city": "",
        "state": "",
        "zip_code": "",
        "email": "",
        "privacy_policy_link": "",
    }

    feedback_links = {  # TODO: add links where the user can provide feedback
        "email": "",
        "survey": "",
    }
