from .base import ConfigurationData
from screener.models import WhiteLabel


class MoConfigurationData(ConfigurationData):
    @classmethod
    def get_white_label(self) -> WhiteLabel:
        return WhiteLabel.objects.get(code="mo")

    # ==========================================================================================
    # BASIC INFORMATION
    # ==========================================================================================

    # Reachable at /mo and offered to the 2-1-1 referrers, but not yet in the public dropdown.
    publicly_launched = False

    state = {"name": "Missouri"}

    public_charge_rule = {
        "link": "https://www.uscis.gov/green-card/green-card-processes-and-procedures/public-charge",
        "text": {
            "_label": "landingPage.publicChargeLinkMO",
            "_default_message": "U.S. Citizenship and Immigration Services",
        },
    }

    more_help_options = {
        "moreHelpOptions": [
            {
                "name": {
                    "_default_message": "Missouri 211 (United Way)",
                    "_label": "moreHelp.211.name.mo",
                },
                "link": "https://search.211helps.org/",
                "phone": {
                    "_default_message": "Dial 2-1-1",
                    "_label": "moreHelp.211.phone.mo",
                },
            },
            {
                "name": {
                    "_default_message": "United Way 211 (Greater St. Louis)",
                    "_label": "moreHelp.211.name.mo.stLouis",
                },
                "description": {
                    "_default_message": "Serving the St. Louis region and southern Illinois.",
                    "_label": "moreHelp.211.description.mo.stLouis",
                },
                "link": "https://helpingpeople.org/united-way-2-1-1/",
                "phone": {
                    "_default_message": "Dial 2-1-1",
                    "_label": "moreHelp.211.phone.mo.stLouis",
                },
            },
        ]
    }

    # ==========================================================================================
    # IMMEDIATE NEED OPTIONS
    # Base options plus three tiles the base set doesn't offer:
    #   freeLowCostMedicalCare - base only has dental care, leaving community health centers
    #                            with nowhere to surface
    #   savings                - reuses Screen.needs_college_savings (as CO does), but labelled
    #                            broadly rather than CO's college-specific wording
    #   transportation         - new Screen.needs_transportation field
    # ==========================================================================================

    acute_condition_options = {
        **ConfigurationData.acute_condition_options,
        "freeLowCostMedicalCare": {
            "icon": {"_icon": "Health_care", "_classname": "option-card-icon"},
            "text": {
                "_label": "acuteConditionOptions.freeLowCostMedicalCare",
                "_default_message": "Free or lower cost health care",
            },
        },
        "savings": {
            "icon": {"_icon": "Savings", "_classname": "option-card-icon"},
            "text": {
                "_label": "acuteConditionOptions.savings.mo",
                "_default_message": "Savings",
            },
        },
        "transportation": {
            "icon": {"_icon": "Transportation", "_classname": "option-card-icon"},
            "text": {
                "_label": "acuteConditionOptions.transportation",
                "_default_message": "Transportation",
            },
        },
    }

    # ==========================================================================================
    # HEALTH INSURANCE OPTIONS
    # Missouri Medicaid is branded "MO HealthNet"
    # ==========================================================================================

    health_insurance_options = {
        "you": {
            **ConfigurationData.health_insurance_options["you"],
            "medicaid": {
                "icon": {"_icon": "Medicaid", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.medicaid.mo",
                    "_default_message": "MO HealthNet (Medicaid)",
                },
            },
            "chp": {
                "icon": {"_icon": "Chp", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.chp.mo",
                    "_default_message": "MO HealthNet for Kids (CHIP)",
                },
            },
        },
        "them": {
            **ConfigurationData.health_insurance_options["them"],
            "medicaid": {
                "icon": {"_icon": "Medicaid", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.medicaid.mo",
                    "_default_message": "MO HealthNet (Medicaid)",
                },
            },
            "chp": {
                "icon": {"_icon": "Chp", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.chp.mo",
                    "_default_message": "MO HealthNet for Kids (CHIP)",
                },
            },
        },
    }

    # ==========================================================================================
    # COUNTIES BY ZIPCODE
    # Full statewide mapping generated from the HUD USPS ZIP-County crosswalk (state "MO").
    # Each ZIP is assigned to the county with the highest TOT_RATIO from that crosswalk.
    # ==========================================================================================

    counties_by_zipcode = {
        # Adair County
        "63501": {"Adair County": "Adair County"},
        "63533": {"Adair County": "Adair County"},
        "63540": {"Adair County": "Adair County"},
        "63546": {"Adair County": "Adair County"},
        "63559": {"Adair County": "Adair County"},
        # Andrew County
        "64421": {"Andrew County": "Andrew County"},
        "64427": {"Andrew County": "Andrew County"},
        "64436": {"Andrew County": "Andrew County"},
        "64449": {"Andrew County": "Andrew County"},
        "64459": {"Andrew County": "Andrew County"},
        "64480": {"Andrew County": "Andrew County"},
        "64483": {"Andrew County": "Andrew County"},
        "64485": {"Andrew County": "Andrew County"},
        # Atchison County
        "64446": {"Atchison County": "Atchison County"},
        "64482": {"Atchison County": "Atchison County"},
        "64491": {"Atchison County": "Atchison County"},
        "64496": {"Atchison County": "Atchison County"},
        "64498": {"Atchison County": "Atchison County"},
        # Audrain County
        "63345": {"Audrain County": "Audrain County"},
        "63352": {"Audrain County": "Audrain County"},
        "63382": {"Audrain County": "Audrain County"},
        "65232": {"Audrain County": "Audrain County"},
        "65264": {"Audrain County": "Audrain County"},
        "65265": {"Audrain County": "Audrain County"},
        "65280": {"Audrain County": "Audrain County"},
        "65285": {"Audrain County": "Audrain County"},
        # Barry County
        "64874": {"Barry County": "Barry County"},
        "65623": {"Barry County": "Barry County"},
        "65625": {"Barry County": "Barry County"},
        "65641": {"Barry County": "Barry County"},
        "65647": {"Barry County": "Barry County"},
        "65658": {"Barry County": "Barry County"},
        "65708": {"Barry County": "Barry County"},
        "65734": {"Barry County": "Barry County"},
        "65745": {"Barry County": "Barry County"},
        "65747": {"Barry County": "Barry County"},
        "65772": {"Barry County": "Barry County"},
        # Barton County
        "64748": {"Barton County": "Barton County"},
        "64759": {"Barton County": "Barton County"},
        "64762": {"Barton County": "Barton County"},
        "64769": {"Barton County": "Barton County"},
        # Bates County
        "64720": {"Bates County": "Bates County"},
        "64722": {"Bates County": "Bates County"},
        "64723": {"Bates County": "Bates County"},
        "64730": {"Bates County": "Bates County"},
        "64745": {"Bates County": "Bates County"},
        "64752": {"Bates County": "Bates County"},
        "64779": {"Bates County": "Bates County"},
        "64780": {"Bates County": "Bates County"},
        # Benton County
        "65325": {"Benton County": "Benton County"},
        "65326": {"Benton County": "Benton County"},
        "65335": {"Benton County": "Benton County"},
        "65338": {"Benton County": "Benton County"},
        "65355": {"Benton County": "Benton County"},
        # Bollinger County
        "63662": {"Bollinger County": "Bollinger County"},
        "63750": {"Bollinger County": "Bollinger County"},
        "63751": {"Bollinger County": "Bollinger County"},
        "63760": {"Bollinger County": "Bollinger County"},
        "63764": {"Bollinger County": "Bollinger County"},
        "63781": {"Bollinger County": "Bollinger County"},
        "63782": {"Bollinger County": "Bollinger County"},
        "63787": {"Bollinger County": "Bollinger County"},
        # Boone County
        "65010": {"Boone County": "Boone County"},
        "65039": {"Boone County": "Boone County"},
        "65201": {"Boone County": "Boone County"},
        "65202": {"Boone County": "Boone County"},
        "65203": {"Boone County": "Boone County"},
        "65205": {"Boone County": "Boone County"},
        "65211": {"Boone County": "Boone County"},
        "65212": {"Boone County": "Boone County"},
        "65215": {"Boone County": "Boone County"},
        "65216": {"Boone County": "Boone County"},
        "65217": {"Boone County": "Boone County"},
        "65218": {"Boone County": "Boone County"},
        "65240": {"Boone County": "Boone County"},
        "65255": {"Boone County": "Boone County"},
        "65256": {"Boone County": "Boone County"},
        "65279": {"Boone County": "Boone County"},
        "65284": {"Boone County": "Boone County"},
        "65299": {"Boone County": "Boone County"},
        # Buchanan County
        "64401": {"Buchanan County": "Buchanan County"},
        "64440": {"Buchanan County": "Buchanan County"},
        "64443": {"Buchanan County": "Buchanan County"},
        "64448": {"Buchanan County": "Buchanan County"},
        "64484": {"Buchanan County": "Buchanan County"},
        "64501": {"Buchanan County": "Buchanan County"},
        "64502": {"Buchanan County": "Buchanan County"},
        "64503": {"Buchanan County": "Buchanan County"},
        "64504": {"Buchanan County": "Buchanan County"},
        "64505": {"Buchanan County": "Buchanan County"},
        "64506": {"Buchanan County": "Buchanan County"},
        "64507": {"Buchanan County": "Buchanan County"},
        "64508": {"Buchanan County": "Buchanan County"},
        # Butler County
        "63901": {"Butler County": "Butler County"},
        "63902": {"Butler County": "Butler County"},
        "63932": {"Butler County": "Butler County"},
        "63940": {"Butler County": "Butler County"},
        "63945": {"Butler County": "Butler County"},
        "63954": {"Butler County": "Butler County"},
        "63961": {"Butler County": "Butler County"},
        "63962": {"Butler County": "Butler County"},
        "63967": {"Butler County": "Butler County"},
        # Caldwell County
        "64624": {"Caldwell County": "Caldwell County"},
        "64625": {"Caldwell County": "Caldwell County"},
        "64637": {"Caldwell County": "Caldwell County"},
        "64644": {"Caldwell County": "Caldwell County"},
        "64649": {"Caldwell County": "Caldwell County"},
        "64650": {"Caldwell County": "Caldwell County"},
        "64671": {"Caldwell County": "Caldwell County"},
        # Callaway County
        "63388": {"Callaway County": "Callaway County"},
        "65043": {"Callaway County": "Callaway County"},
        "65059": {"Callaway County": "Callaway County"},
        "65063": {"Callaway County": "Callaway County"},
        "65067": {"Callaway County": "Callaway County"},
        "65077": {"Callaway County": "Callaway County"},
        "65080": {"Callaway County": "Callaway County"},
        "65231": {"Callaway County": "Callaway County"},
        "65251": {"Callaway County": "Callaway County"},
        "65262": {"Callaway County": "Callaway County"},
        # Camden County
        "65020": {"Camden County": "Camden County"},
        "65049": {"Camden County": "Camden County"},
        "65052": {"Camden County": "Camden County"},
        "65065": {"Camden County": "Camden County"},
        "65079": {"Camden County": "Camden County"},
        "65324": {"Camden County": "Camden County"},
        "65567": {"Camden County": "Camden County"},
        "65591": {"Camden County": "Camden County"},
        "65786": {"Camden County": "Camden County"},
        "65787": {"Camden County": "Camden County"},
        # Cape Girardeau County
        "63701": {"Cape Girardeau County": "Cape Girardeau County"},
        "63702": {"Cape Girardeau County": "Cape Girardeau County"},
        "63703": {"Cape Girardeau County": "Cape Girardeau County"},
        "63739": {"Cape Girardeau County": "Cape Girardeau County"},
        "63743": {"Cape Girardeau County": "Cape Girardeau County"},
        "63744": {"Cape Girardeau County": "Cape Girardeau County"},
        "63745": {"Cape Girardeau County": "Cape Girardeau County"},
        "63747": {"Cape Girardeau County": "Cape Girardeau County"},
        "63752": {"Cape Girardeau County": "Cape Girardeau County"},
        "63755": {"Cape Girardeau County": "Cape Girardeau County"},
        "63766": {"Cape Girardeau County": "Cape Girardeau County"},
        "63769": {"Cape Girardeau County": "Cape Girardeau County"},
        "63779": {"Cape Girardeau County": "Cape Girardeau County"},
        "63785": {"Cape Girardeau County": "Cape Girardeau County"},
        # Carroll County
        "64622": {"Carroll County": "Carroll County"},
        "64623": {"Carroll County": "Carroll County"},
        "64633": {"Carroll County": "Carroll County"},
        "64639": {"Carroll County": "Carroll County"},
        "64643": {"Carroll County": "Carroll County"},
        "64668": {"Carroll County": "Carroll County"},
        "64680": {"Carroll County": "Carroll County"},
        "64682": {"Carroll County": "Carroll County"},
        # Carter County
        "63937": {"Carter County": "Carter County"},
        "63941": {"Carter County": "Carter County"},
        "63943": {"Carter County": "Carter County"},
        "63965": {"Carter County": "Carter County"},
        # Cass County
        "64012": {"Cass County": "Cass County"},
        "64078": {"Cass County": "Cass County"},
        "64080": {"Cass County": "Cass County"},
        "64083": {"Cass County": "Cass County"},
        "64090": {"Cass County": "Cass County"},
        "64701": {"Cass County": "Cass County"},
        "64725": {"Cass County": "Cass County"},
        "64734": {"Cass County": "Cass County"},
        "64739": {"Cass County": "Cass County"},
        "64742": {"Cass County": "Cass County"},
        "64743": {"Cass County": "Cass County"},
        "64746": {"Cass County": "Cass County"},
        "64747": {"Cass County": "Cass County"},
        # Cedar County
        "64744": {"Cedar County": "Cedar County"},
        "64756": {"Cedar County": "Cedar County"},
        "65607": {"Cedar County": "Cedar County"},
        "65785": {"Cedar County": "Cedar County"},
        # Chariton County
        "64660": {"Chariton County": "Chariton County"},
        "64676": {"Chariton County": "Chariton County"},
        "64681": {"Chariton County": "Chariton County"},
        "65236": {"Chariton County": "Chariton County"},
        "65246": {"Chariton County": "Chariton County"},
        "65261": {"Chariton County": "Chariton County"},
        "65281": {"Chariton County": "Chariton County"},
        "65286": {"Chariton County": "Chariton County"},
        # Christian County
        "65610": {"Christian County": "Christian County"},
        "65620": {"Christian County": "Christian County"},
        "65629": {"Christian County": "Christian County"},
        "65630": {"Christian County": "Christian County"},
        "65631": {"Christian County": "Christian County"},
        "65657": {"Christian County": "Christian County"},
        "65669": {"Christian County": "Christian County"},
        "65714": {"Christian County": "Christian County"},
        "65720": {"Christian County": "Christian County"},
        "65721": {"Christian County": "Christian County"},
        "65753": {"Christian County": "Christian County"},
        "65754": {"Christian County": "Christian County"},
        # Clark County
        "63430": {"Clark County": "Clark County"},
        "63445": {"Clark County": "Clark County"},
        "63453": {"Clark County": "Clark County"},
        "63465": {"Clark County": "Clark County"},
        "63466": {"Clark County": "Clark County"},
        "63472": {"Clark County": "Clark County"},
        "63474": {"Clark County": "Clark County"},
        # Clay County
        "64024": {"Clay County": "Clay County"},
        "64048": {"Clay County": "Clay County"},
        "64060": {"Clay County": "Clay County"},
        "64068": {"Clay County": "Clay County"},
        "64069": {"Clay County": "Clay County"},
        "64072": {"Clay County": "Clay County"},
        "64073": {"Clay County": "Clay County"},
        "64089": {"Clay County": "Clay County"},
        "64116": {"Clay County": "Clay County"},
        "64117": {"Clay County": "Clay County"},
        "64118": {"Clay County": "Clay County"},
        "64119": {"Clay County": "Clay County"},
        "64144": {"Clay County": "Clay County"},
        "64155": {"Clay County": "Clay County"},
        "64156": {"Clay County": "Clay County"},
        "64157": {"Clay County": "Clay County"},
        "64158": {"Clay County": "Clay County"},
        "64161": {"Clay County": "Clay County"},
        "64162": {"Clay County": "Clay County"},
        "64165": {"Clay County": "Clay County"},
        "64166": {"Clay County": "Clay County"},
        "64167": {"Clay County": "Clay County"},
        "64188": {"Clay County": "Clay County"},
        # Clinton County
        "64429": {"Clinton County": "Clinton County"},
        "64454": {"Clinton County": "Clinton County"},
        "64465": {"Clinton County": "Clinton County"},
        "64477": {"Clinton County": "Clinton County"},
        "64492": {"Clinton County": "Clinton County"},
        "64493": {"Clinton County": "Clinton County"},
        # Cole County
        "65023": {"Cole County": "Cole County"},
        "65032": {"Cole County": "Cole County"},
        "65040": {"Cole County": "Cole County"},
        "65053": {"Cole County": "Cole County"},
        "65074": {"Cole County": "Cole County"},
        "65076": {"Cole County": "Cole County"},
        "65101": {"Cole County": "Cole County"},
        "65102": {"Cole County": "Cole County"},
        "65103": {"Cole County": "Cole County"},
        "65104": {"Cole County": "Cole County"},
        "65105": {"Cole County": "Cole County"},
        "65109": {"Cole County": "Cole County"},
        "65110": {"Cole County": "Cole County"},
        "65111": {"Cole County": "Cole County"},
        # Cooper County
        "65068": {"Cooper County": "Cooper County"},
        "65233": {"Cooper County": "Cooper County"},
        "65237": {"Cooper County": "Cooper County"},
        "65276": {"Cooper County": "Cooper County"},
        "65287": {"Cooper County": "Cooper County"},
        "65322": {"Cooper County": "Cooper County"},
        "65348": {"Cooper County": "Cooper County"},
        # Crawford County
        "65441": {"Crawford County": "Crawford County"},
        "65446": {"Crawford County": "Crawford County"},
        "65449": {"Crawford County": "Crawford County"},
        "65453": {"Crawford County": "Crawford County"},
        "65456": {"Crawford County": "Crawford County"},
        "65535": {"Crawford County": "Crawford County"},
        "65565": {"Crawford County": "Crawford County"},
        "65586": {"Crawford County": "Crawford County"},
        # Dade County
        "65603": {"Dade County": "Dade County"},
        "65635": {"Dade County": "Dade County"},
        "65646": {"Dade County": "Dade County"},
        "65661": {"Dade County": "Dade County"},
        "65682": {"Dade County": "Dade County"},
        "65752": {"Dade County": "Dade County"},
        # Dallas County
        "65590": {"Dallas County": "Dallas County"},
        "65622": {"Dallas County": "Dallas County"},
        "65644": {"Dallas County": "Dallas County"},
        "65685": {"Dallas County": "Dallas County"},
        "65764": {"Dallas County": "Dallas County"},
        "65767": {"Dallas County": "Dallas County"},
        "65783": {"Dallas County": "Dallas County"},
        # Daviess County
        "64620": {"Daviess County": "Daviess County"},
        "64636": {"Daviess County": "Daviess County"},
        "64640": {"Daviess County": "Daviess County"},
        "64647": {"Daviess County": "Daviess County"},
        "64648": {"Daviess County": "Daviess County"},
        "64654": {"Daviess County": "Daviess County"},
        "64670": {"Daviess County": "Daviess County"},
        "64689": {"Daviess County": "Daviess County"},
        # DeKalb County
        "64422": {"DeKalb County": "DeKalb County"},
        "64430": {"DeKalb County": "DeKalb County"},
        "64469": {"DeKalb County": "DeKalb County"},
        "64474": {"DeKalb County": "DeKalb County"},
        "64490": {"DeKalb County": "DeKalb County"},
        "64494": {"DeKalb County": "DeKalb County"},
        "64497": {"DeKalb County": "DeKalb County"},
        # Dent County
        "65440": {"Dent County": "Dent County"},
        "65501": {"Dent County": "Dent County"},
        "65532": {"Dent County": "Dent County"},
        "65541": {"Dent County": "Dent County"},
        "65560": {"Dent County": "Dent County"},
        # Douglas County
        "65638": {"Douglas County": "Douglas County"},
        "65755": {"Douglas County": "Douglas County"},
        "65768": {"Douglas County": "Douglas County"},
        # Dunklin County
        "63821": {"Dunklin County": "Dunklin County"},
        "63829": {"Dunklin County": "Dunklin County"},
        "63837": {"Dunklin County": "Dunklin County"},
        "63847": {"Dunklin County": "Dunklin County"},
        "63849": {"Dunklin County": "Dunklin County"},
        "63852": {"Dunklin County": "Dunklin County"},
        "63855": {"Dunklin County": "Dunklin County"},
        "63857": {"Dunklin County": "Dunklin County"},
        "63863": {"Dunklin County": "Dunklin County"},
        "63875": {"Dunklin County": "Dunklin County"},
        "63876": {"Dunklin County": "Dunklin County"},
        "63880": {"Dunklin County": "Dunklin County"},
        "63933": {"Dunklin County": "Dunklin County"},
        # Franklin County
        "63013": {"Franklin County": "Franklin County"},
        "63014": {"Franklin County": "Franklin County"},
        "63015": {"Franklin County": "Franklin County"},
        "63037": {"Franklin County": "Franklin County"},
        "63039": {"Franklin County": "Franklin County"},
        "63041": {"Franklin County": "Franklin County"},
        "63055": {"Franklin County": "Franklin County"},
        "63056": {"Franklin County": "Franklin County"},
        "63060": {"Franklin County": "Franklin County"},
        "63061": {"Franklin County": "Franklin County"},
        "63068": {"Franklin County": "Franklin County"},
        "63069": {"Franklin County": "Franklin County"},
        "63072": {"Franklin County": "Franklin County"},
        "63073": {"Franklin County": "Franklin County"},
        "63077": {"Franklin County": "Franklin County"},
        "63079": {"Franklin County": "Franklin County"},
        "63080": {"Franklin County": "Franklin County"},
        "63084": {"Franklin County": "Franklin County"},
        "63089": {"Franklin County": "Franklin County"},
        "63090": {"Franklin County": "Franklin County"},
        # Gasconade County
        "63091": {"Gasconade County": "Gasconade County"},
        "65014": {"Gasconade County": "Gasconade County"},
        "65041": {"Gasconade County": "Gasconade County"},
        "65061": {"Gasconade County": "Gasconade County"},
        "65062": {"Gasconade County": "Gasconade County"},
        "65066": {"Gasconade County": "Gasconade County"},
        # Gentry County
        "64402": {"Gentry County": "Gentry County"},
        "64438": {"Gentry County": "Gentry County"},
        "64453": {"Gentry County": "Gentry County"},
        "64463": {"Gentry County": "Gentry County"},
        "64489": {"Gentry County": "Gentry County"},
        "64657": {"Gentry County": "Gentry County"},
        # Greene County
        "65604": {"Greene County": "Greene County"},
        "65612": {"Greene County": "Greene County"},
        "65619": {"Greene County": "Greene County"},
        "65648": {"Greene County": "Greene County"},
        "65738": {"Greene County": "Greene County"},
        "65757": {"Greene County": "Greene County"},
        "65765": {"Greene County": "Greene County"},
        "65770": {"Greene County": "Greene County"},
        "65781": {"Greene County": "Greene County"},
        "65801": {"Greene County": "Greene County"},
        "65802": {"Greene County": "Greene County"},
        "65803": {"Greene County": "Greene County"},
        "65804": {"Greene County": "Greene County"},
        "65805": {"Greene County": "Greene County"},
        "65806": {"Greene County": "Greene County"},
        "65807": {"Greene County": "Greene County"},
        "65808": {"Greene County": "Greene County"},
        "65809": {"Greene County": "Greene County"},
        "65810": {"Greene County": "Greene County"},
        "65814": {"Greene County": "Greene County"},
        "65890": {"Greene County": "Greene County"},
        "65897": {"Greene County": "Greene County"},
        "65898": {"Greene County": "Greene County"},
        "65899": {"Greene County": "Greene County"},
        # Grundy County
        "64641": {"Grundy County": "Grundy County"},
        "64652": {"Grundy County": "Grundy County"},
        "64679": {"Grundy County": "Grundy County"},
        "64683": {"Grundy County": "Grundy County"},
        # Harrison County
        "64424": {"Harrison County": "Harrison County"},
        "64426": {"Harrison County": "Harrison County"},
        "64442": {"Harrison County": "Harrison County"},
        "64458": {"Harrison County": "Harrison County"},
        "64467": {"Harrison County": "Harrison County"},
        "64471": {"Harrison County": "Harrison County"},
        "64481": {"Harrison County": "Harrison County"},
        "64632": {"Harrison County": "Harrison County"},
        "64642": {"Harrison County": "Harrison County"},
        # Henry County
        "64726": {"Henry County": "Henry County"},
        "64735": {"Henry County": "Henry County"},
        "64740": {"Henry County": "Henry County"},
        "64770": {"Henry County": "Henry County"},
        "64788": {"Henry County": "Henry County"},
        "65323": {"Henry County": "Henry County"},
        "65360": {"Henry County": "Henry County"},
        # Hickory County
        "65634": {"Hickory County": "Hickory County"},
        "65668": {"Hickory County": "Hickory County"},
        "65724": {"Hickory County": "Hickory County"},
        "65732": {"Hickory County": "Hickory County"},
        "65735": {"Hickory County": "Hickory County"},
        "65774": {"Hickory County": "Hickory County"},
        "65779": {"Hickory County": "Hickory County"},
        # Holt County
        "64437": {"Holt County": "Holt County"},
        "64451": {"Holt County": "Holt County"},
        "64466": {"Holt County": "Holt County"},
        "64470": {"Holt County": "Holt County"},
        "64473": {"Holt County": "Holt County"},
        # Howard County
        "65230": {"Howard County": "Howard County"},
        "65248": {"Howard County": "Howard County"},
        "65250": {"Howard County": "Howard County"},
        "65254": {"Howard County": "Howard County"},
        "65274": {"Howard County": "Howard County"},
        # Howell County
        "65548": {"Howell County": "Howell County"},
        "65626": {"Howell County": "Howell County"},
        "65688": {"Howell County": "Howell County"},
        "65775": {"Howell County": "Howell County"},
        "65777": {"Howell County": "Howell County"},
        "65788": {"Howell County": "Howell County"},
        "65789": {"Howell County": "Howell County"},
        "65790": {"Howell County": "Howell County"},
        "65793": {"Howell County": "Howell County"},
        # Iron County
        "63620": {"Iron County": "Iron County"},
        "63621": {"Iron County": "Iron County"},
        "63623": {"Iron County": "Iron County"},
        "63636": {"Iron County": "Iron County"},
        "63650": {"Iron County": "Iron County"},
        "63656": {"Iron County": "Iron County"},
        "63663": {"Iron County": "Iron County"},
        "63675": {"Iron County": "Iron County"},
        "65439": {"Iron County": "Iron County"},
        "65566": {"Iron County": "Iron County"},
        # Jackson County
        "64002": {"Jackson County": "Jackson County"},
        "64013": {"Jackson County": "Jackson County"},
        "64014": {"Jackson County": "Jackson County"},
        "64015": {"Jackson County": "Jackson County"},
        "64016": {"Jackson County": "Jackson County"},
        "64029": {"Jackson County": "Jackson County"},
        "64030": {"Jackson County": "Jackson County"},
        "64034": {"Jackson County": "Jackson County"},
        "64050": {"Jackson County": "Jackson County"},
        "64051": {"Jackson County": "Jackson County"},
        "64052": {"Jackson County": "Jackson County"},
        "64053": {"Jackson County": "Jackson County"},
        "64054": {"Jackson County": "Jackson County"},
        "64055": {"Jackson County": "Jackson County"},
        "64056": {"Jackson County": "Jackson County"},
        "64057": {"Jackson County": "Jackson County"},
        "64058": {"Jackson County": "Jackson County"},
        "64063": {"Jackson County": "Jackson County"},
        "64064": {"Jackson County": "Jackson County"},
        "64065": {"Jackson County": "Jackson County"},
        "64066": {"Jackson County": "Jackson County"},
        "64070": {"Jackson County": "Jackson County"},
        "64075": {"Jackson County": "Jackson County"},
        "64081": {"Jackson County": "Jackson County"},
        "64082": {"Jackson County": "Jackson County"},
        "64086": {"Jackson County": "Jackson County"},
        "64088": {"Jackson County": "Jackson County"},
        "64101": {"Jackson County": "Jackson County"},
        "64102": {"Jackson County": "Jackson County"},
        "64105": {"Jackson County": "Jackson County"},
        "64106": {"Jackson County": "Jackson County"},
        "64108": {"Jackson County": "Jackson County"},
        "64109": {"Jackson County": "Jackson County"},
        "64110": {"Jackson County": "Jackson County"},
        "64111": {"Jackson County": "Jackson County"},
        "64112": {"Jackson County": "Jackson County"},
        "64113": {"Jackson County": "Jackson County"},
        "64114": {"Jackson County": "Jackson County"},
        "64120": {"Jackson County": "Jackson County"},
        "64121": {"Jackson County": "Jackson County"},
        "64123": {"Jackson County": "Jackson County"},
        "64124": {"Jackson County": "Jackson County"},
        "64125": {"Jackson County": "Jackson County"},
        "64126": {"Jackson County": "Jackson County"},
        "64127": {"Jackson County": "Jackson County"},
        "64128": {"Jackson County": "Jackson County"},
        "64129": {"Jackson County": "Jackson County"},
        "64130": {"Jackson County": "Jackson County"},
        "64131": {"Jackson County": "Jackson County"},
        "64132": {"Jackson County": "Jackson County"},
        "64133": {"Jackson County": "Jackson County"},
        "64134": {"Jackson County": "Jackson County"},
        "64136": {"Jackson County": "Jackson County"},
        "64137": {"Jackson County": "Jackson County"},
        "64138": {"Jackson County": "Jackson County"},
        "64139": {"Jackson County": "Jackson County"},
        "64141": {"Jackson County": "Jackson County"},
        "64145": {"Jackson County": "Jackson County"},
        "64146": {"Jackson County": "Jackson County"},
        "64147": {"Jackson County": "Jackson County"},
        "64148": {"Jackson County": "Jackson County"},
        "64149": {"Jackson County": "Jackson County"},
        "64170": {"Jackson County": "Jackson County"},
        "64171": {"Jackson County": "Jackson County"},
        "64197": {"Jackson County": "Jackson County"},
        "64198": {"Jackson County": "Jackson County"},
        "64199": {"Jackson County": "Jackson County"},
        "64999": {"Jackson County": "Jackson County"},
        # Jasper County
        "64755": {"Jasper County": "Jasper County"},
        "64801": {"Jasper County": "Jasper County"},
        "64802": {"Jasper County": "Jasper County"},
        "64803": {"Jasper County": "Jasper County"},
        "64804": {"Jasper County": "Jasper County"},
        "64830": {"Jasper County": "Jasper County"},
        "64832": {"Jasper County": "Jasper County"},
        "64833": {"Jasper County": "Jasper County"},
        "64834": {"Jasper County": "Jasper County"},
        "64835": {"Jasper County": "Jasper County"},
        "64836": {"Jasper County": "Jasper County"},
        "64841": {"Jasper County": "Jasper County"},
        "64849": {"Jasper County": "Jasper County"},
        "64855": {"Jasper County": "Jasper County"},
        "64857": {"Jasper County": "Jasper County"},
        "64859": {"Jasper County": "Jasper County"},
        "64862": {"Jasper County": "Jasper County"},
        "64870": {"Jasper County": "Jasper County"},
        # Jefferson County
        "63010": {"Jefferson County": "Jefferson County"},
        "63012": {"Jefferson County": "Jefferson County"},
        "63016": {"Jefferson County": "Jefferson County"},
        "63019": {"Jefferson County": "Jefferson County"},
        "63020": {"Jefferson County": "Jefferson County"},
        "63023": {"Jefferson County": "Jefferson County"},
        "63028": {"Jefferson County": "Jefferson County"},
        "63047": {"Jefferson County": "Jefferson County"},
        "63048": {"Jefferson County": "Jefferson County"},
        "63049": {"Jefferson County": "Jefferson County"},
        "63050": {"Jefferson County": "Jefferson County"},
        "63051": {"Jefferson County": "Jefferson County"},
        "63052": {"Jefferson County": "Jefferson County"},
        "63053": {"Jefferson County": "Jefferson County"},
        "63057": {"Jefferson County": "Jefferson County"},
        "63065": {"Jefferson County": "Jefferson County"},
        "63066": {"Jefferson County": "Jefferson County"},
        "63070": {"Jefferson County": "Jefferson County"},
        # Johnson County
        "64019": {"Johnson County": "Johnson County"},
        "64040": {"Johnson County": "Johnson County"},
        "64061": {"Johnson County": "Johnson County"},
        "64093": {"Johnson County": "Johnson County"},
        "64733": {"Johnson County": "Johnson County"},
        "64761": {"Johnson County": "Johnson County"},
        "65305": {"Johnson County": "Johnson County"},
        "65336": {"Johnson County": "Johnson County"},
        # Knox County
        "63446": {"Knox County": "Knox County"},
        "63458": {"Knox County": "Knox County"},
        "63460": {"Knox County": "Knox County"},
        "63531": {"Knox County": "Knox County"},
        "63537": {"Knox County": "Knox County"},
        "63547": {"Knox County": "Knox County"},
        # Laclede County
        "65463": {"Laclede County": "Laclede County"},
        "65470": {"Laclede County": "Laclede County"},
        "65536": {"Laclede County": "Laclede County"},
        "65543": {"Laclede County": "Laclede County"},
        "65632": {"Laclede County": "Laclede County"},
        "65722": {"Laclede County": "Laclede County"},
        # Lafayette County
        "64001": {"Lafayette County": "Lafayette County"},
        "64011": {"Lafayette County": "Lafayette County"},
        "64020": {"Lafayette County": "Lafayette County"},
        "64021": {"Lafayette County": "Lafayette County"},
        "64022": {"Lafayette County": "Lafayette County"},
        "64037": {"Lafayette County": "Lafayette County"},
        "64067": {"Lafayette County": "Lafayette County"},
        "64071": {"Lafayette County": "Lafayette County"},
        "64074": {"Lafayette County": "Lafayette County"},
        "64076": {"Lafayette County": "Lafayette County"},
        "64096": {"Lafayette County": "Lafayette County"},
        "64097": {"Lafayette County": "Lafayette County"},
        # Lawrence County
        "64848": {"Lawrence County": "Lawrence County"},
        "64873": {"Lawrence County": "Lawrence County"},
        "65605": {"Lawrence County": "Lawrence County"},
        "65654": {"Lawrence County": "Lawrence County"},
        "65664": {"Lawrence County": "Lawrence County"},
        "65705": {"Lawrence County": "Lawrence County"},
        "65707": {"Lawrence County": "Lawrence County"},
        "65712": {"Lawrence County": "Lawrence County"},
        "65723": {"Lawrence County": "Lawrence County"},
        "65756": {"Lawrence County": "Lawrence County"},
        "65769": {"Lawrence County": "Lawrence County"},
        # Lewis County
        "63435": {"Lewis County": "Lewis County"},
        "63438": {"Lewis County": "Lewis County"},
        "63440": {"Lewis County": "Lewis County"},
        "63447": {"Lewis County": "Lewis County"},
        "63448": {"Lewis County": "Lewis County"},
        "63452": {"Lewis County": "Lewis County"},
        "63457": {"Lewis County": "Lewis County"},
        "63473": {"Lewis County": "Lewis County"},
        # Lincoln County
        "63343": {"Lincoln County": "Lincoln County"},
        "63347": {"Lincoln County": "Lincoln County"},
        "63349": {"Lincoln County": "Lincoln County"},
        "63362": {"Lincoln County": "Lincoln County"},
        "63369": {"Lincoln County": "Lincoln County"},
        "63377": {"Lincoln County": "Lincoln County"},
        "63379": {"Lincoln County": "Lincoln County"},
        "63381": {"Lincoln County": "Lincoln County"},
        "63387": {"Lincoln County": "Lincoln County"},
        "63389": {"Lincoln County": "Lincoln County"},
        # Linn County
        "63557": {"Linn County": "Linn County"},
        "64628": {"Linn County": "Linn County"},
        "64630": {"Linn County": "Linn County"},
        "64631": {"Linn County": "Linn County"},
        "64651": {"Linn County": "Linn County"},
        "64653": {"Linn County": "Linn County"},
        "64658": {"Linn County": "Linn County"},
        "64659": {"Linn County": "Linn County"},
        "64674": {"Linn County": "Linn County"},
        # Livingston County
        "64601": {"Livingston County": "Livingston County"},
        "64635": {"Livingston County": "Livingston County"},
        "64638": {"Livingston County": "Livingston County"},
        "64656": {"Livingston County": "Livingston County"},
        "64664": {"Livingston County": "Livingston County"},
        "64686": {"Livingston County": "Livingston County"},
        "64688": {"Livingston County": "Livingston County"},
        # Macon County
        "63431": {"Macon County": "Macon County"},
        "63530": {"Macon County": "Macon County"},
        "63532": {"Macon County": "Macon County"},
        "63534": {"Macon County": "Macon County"},
        "63538": {"Macon County": "Macon County"},
        "63539": {"Macon County": "Macon County"},
        "63549": {"Macon County": "Macon County"},
        "63552": {"Macon County": "Macon County"},
        "63558": {"Macon County": "Macon County"},
        "65247": {"Macon County": "Macon County"},
        # Madison County
        "63645": {"Madison County": "Madison County"},
        "63655": {"Madison County": "Madison County"},
        # Maries County
        "65013": {"Maries County": "Maries County"},
        "65058": {"Maries County": "Maries County"},
        "65443": {"Maries County": "Maries County"},
        "65580": {"Maries County": "Maries County"},
        "65582": {"Maries County": "Maries County"},
        # Marion County
        "63401": {"Marion County": "Marion County"},
        "63454": {"Marion County": "Marion County"},
        "63461": {"Marion County": "Marion County"},
        "63463": {"Marion County": "Marion County"},
        "63471": {"Marion County": "Marion County"},
        # McDonald County
        "64831": {"McDonald County": "McDonald County"},
        "64843": {"McDonald County": "McDonald County"},
        "64847": {"McDonald County": "McDonald County"},
        "64854": {"McDonald County": "McDonald County"},
        "64856": {"McDonald County": "McDonald County"},
        "64861": {"McDonald County": "McDonald County"},
        "64863": {"McDonald County": "McDonald County"},
        "64867": {"McDonald County": "McDonald County"},
        "64868": {"McDonald County": "McDonald County"},
        "65730": {"McDonald County": "McDonald County"},
        # Mercer County
        "64661": {"Mercer County": "Mercer County"},
        "64673": {"Mercer County": "Mercer County"},
        # Miller County
        "65017": {"Miller County": "Miller County"},
        "65026": {"Miller County": "Miller County"},
        "65047": {"Miller County": "Miller County"},
        "65064": {"Miller County": "Miller County"},
        "65075": {"Miller County": "Miller County"},
        "65082": {"Miller County": "Miller County"},
        "65083": {"Miller County": "Miller County"},
        "65486": {"Miller County": "Miller County"},
        # Mississippi County
        "63820": {"Mississippi County": "Mississippi County"},
        "63823": {"Mississippi County": "Mississippi County"},
        "63834": {"Mississippi County": "Mississippi County"},
        "63845": {"Mississippi County": "Mississippi County"},
        "63881": {"Mississippi County": "Mississippi County"},
        "63882": {"Mississippi County": "Mississippi County"},
        # Moniteau County
        "65018": {"Moniteau County": "Moniteau County"},
        "65025": {"Moniteau County": "Moniteau County"},
        "65042": {"Moniteau County": "Moniteau County"},
        "65046": {"Moniteau County": "Moniteau County"},
        "65050": {"Moniteau County": "Moniteau County"},
        "65055": {"Moniteau County": "Moniteau County"},
        "65081": {"Moniteau County": "Moniteau County"},
        # Monroe County
        "63456": {"Monroe County": "Monroe County"},
        "65258": {"Monroe County": "Monroe County"},
        "65263": {"Monroe County": "Monroe County"},
        "65275": {"Monroe County": "Monroe County"},
        "65282": {"Monroe County": "Monroe County"},
        "65283": {"Monroe County": "Monroe County"},
        # Montgomery County
        "63333": {"Montgomery County": "Montgomery County"},
        "63350": {"Montgomery County": "Montgomery County"},
        "63351": {"Montgomery County": "Montgomery County"},
        "63359": {"Montgomery County": "Montgomery County"},
        "63361": {"Montgomery County": "Montgomery County"},
        "63363": {"Montgomery County": "Montgomery County"},
        "63384": {"Montgomery County": "Montgomery County"},
        "65069": {"Montgomery County": "Montgomery County"},
        # Morgan County
        "65011": {"Morgan County": "Morgan County"},
        "65034": {"Morgan County": "Morgan County"},
        "65037": {"Morgan County": "Morgan County"},
        "65038": {"Morgan County": "Morgan County"},
        "65072": {"Morgan County": "Morgan County"},
        "65078": {"Morgan County": "Morgan County"},
        "65084": {"Morgan County": "Morgan County"},
        "65329": {"Morgan County": "Morgan County"},
        "65354": {"Morgan County": "Morgan County"},
        # New Madrid County
        "63828": {"New Madrid County": "New Madrid County"},
        "63833": {"New Madrid County": "New Madrid County"},
        "63848": {"New Madrid County": "New Madrid County"},
        "63860": {"New Madrid County": "New Madrid County"},
        "63862": {"New Madrid County": "New Madrid County"},
        "63866": {"New Madrid County": "New Madrid County"},
        "63867": {"New Madrid County": "New Madrid County"},
        "63868": {"New Madrid County": "New Madrid County"},
        "63869": {"New Madrid County": "New Madrid County"},
        "63870": {"New Madrid County": "New Madrid County"},
        "63873": {"New Madrid County": "New Madrid County"},
        "63874": {"New Madrid County": "New Madrid County"},
        "63878": {"New Madrid County": "New Madrid County"},
        # Newton County
        "64840": {"Newton County": "Newton County"},
        "64842": {"Newton County": "Newton County"},
        "64844": {"Newton County": "Newton County"},
        "64850": {"Newton County": "Newton County"},
        "64858": {"Newton County": "Newton County"},
        "64864": {"Newton County": "Newton County"},
        "64865": {"Newton County": "Newton County"},
        "64866": {"Newton County": "Newton County"},
        # Nodaway County
        "64423": {"Nodaway County": "Nodaway County"},
        "64428": {"Nodaway County": "Nodaway County"},
        "64431": {"Nodaway County": "Nodaway County"},
        "64432": {"Nodaway County": "Nodaway County"},
        "64433": {"Nodaway County": "Nodaway County"},
        "64434": {"Nodaway County": "Nodaway County"},
        "64445": {"Nodaway County": "Nodaway County"},
        "64455": {"Nodaway County": "Nodaway County"},
        "64457": {"Nodaway County": "Nodaway County"},
        "64461": {"Nodaway County": "Nodaway County"},
        "64468": {"Nodaway County": "Nodaway County"},
        "64475": {"Nodaway County": "Nodaway County"},
        "64476": {"Nodaway County": "Nodaway County"},
        "64479": {"Nodaway County": "Nodaway County"},
        "64487": {"Nodaway County": "Nodaway County"},
        # Oregon County
        "65606": {"Oregon County": "Oregon County"},
        "65690": {"Oregon County": "Oregon County"},
        "65692": {"Oregon County": "Oregon County"},
        "65778": {"Oregon County": "Oregon County"},
        "65791": {"Oregon County": "Oregon County"},
        # Osage County
        "65001": {"Osage County": "Osage County"},
        "65016": {"Osage County": "Osage County"},
        "65024": {"Osage County": "Osage County"},
        "65035": {"Osage County": "Osage County"},
        "65048": {"Osage County": "Osage County"},
        "65051": {"Osage County": "Osage County"},
        "65054": {"Osage County": "Osage County"},
        "65085": {"Osage County": "Osage County"},
        # Ozark County
        "65609": {"Ozark County": "Ozark County"},
        "65618": {"Ozark County": "Ozark County"},
        "65637": {"Ozark County": "Ozark County"},
        "65655": {"Ozark County": "Ozark County"},
        "65666": {"Ozark County": "Ozark County"},
        "65676": {"Ozark County": "Ozark County"},
        "65715": {"Ozark County": "Ozark County"},
        "65729": {"Ozark County": "Ozark County"},
        "65741": {"Ozark County": "Ozark County"},
        "65760": {"Ozark County": "Ozark County"},
        "65761": {"Ozark County": "Ozark County"},
        "65762": {"Ozark County": "Ozark County"},
        "65766": {"Ozark County": "Ozark County"},
        "65773": {"Ozark County": "Ozark County"},
        "65784": {"Ozark County": "Ozark County"},
        # Pemiscot County
        "63826": {"Pemiscot County": "Pemiscot County"},
        "63827": {"Pemiscot County": "Pemiscot County"},
        "63830": {"Pemiscot County": "Pemiscot County"},
        "63839": {"Pemiscot County": "Pemiscot County"},
        "63840": {"Pemiscot County": "Pemiscot County"},
        "63851": {"Pemiscot County": "Pemiscot County"},
        "63853": {"Pemiscot County": "Pemiscot County"},
        "63877": {"Pemiscot County": "Pemiscot County"},
        "63879": {"Pemiscot County": "Pemiscot County"},
        # Perry County
        "63732": {"Perry County": "Perry County"},
        "63737": {"Perry County": "Perry County"},
        "63746": {"Perry County": "Perry County"},
        "63748": {"Perry County": "Perry County"},
        "63770": {"Perry County": "Perry County"},
        "63775": {"Perry County": "Perry County"},
        "63776": {"Perry County": "Perry County"},
        "63783": {"Perry County": "Perry County"},
        # Pettis County
        "65301": {"Pettis County": "Pettis County"},
        "65302": {"Pettis County": "Pettis County"},
        "65332": {"Pettis County": "Pettis County"},
        "65333": {"Pettis County": "Pettis County"},
        "65334": {"Pettis County": "Pettis County"},
        "65337": {"Pettis County": "Pettis County"},
        "65345": {"Pettis County": "Pettis County"},
        "65350": {"Pettis County": "Pettis County"},
        # Phelps County
        "65401": {"Phelps County": "Phelps County"},
        "65402": {"Phelps County": "Phelps County"},
        "65409": {"Phelps County": "Phelps County"},
        "65436": {"Phelps County": "Phelps County"},
        "65461": {"Phelps County": "Phelps County"},
        "65462": {"Phelps County": "Phelps County"},
        "65529": {"Phelps County": "Phelps County"},
        "65550": {"Phelps County": "Phelps County"},
        "65559": {"Phelps County": "Phelps County"},
        # Pike County
        "63330": {"Pike County": "Pike County"},
        "63334": {"Pike County": "Pike County"},
        "63336": {"Pike County": "Pike County"},
        "63339": {"Pike County": "Pike County"},
        "63344": {"Pike County": "Pike County"},
        "63353": {"Pike County": "Pike County"},
        "63433": {"Pike County": "Pike County"},
        "63441": {"Pike County": "Pike County"},
        # Platte County
        "64018": {"Platte County": "Platte County"},
        "64028": {"Platte County": "Platte County"},
        "64079": {"Platte County": "Platte County"},
        "64092": {"Platte County": "Platte County"},
        "64098": {"Platte County": "Platte County"},
        "64150": {"Platte County": "Platte County"},
        "64151": {"Platte County": "Platte County"},
        "64152": {"Platte County": "Platte County"},
        "64153": {"Platte County": "Platte County"},
        "64154": {"Platte County": "Platte County"},
        "64163": {"Platte County": "Platte County"},
        "64164": {"Platte County": "Platte County"},
        "64168": {"Platte County": "Platte County"},
        "64190": {"Platte County": "Platte County"},
        "64439": {"Platte County": "Platte County"},
        "64444": {"Platte County": "Platte County"},
        # Polk County
        "65601": {"Polk County": "Polk County"},
        "65613": {"Polk County": "Polk County"},
        "65617": {"Polk County": "Polk County"},
        "65640": {"Polk County": "Polk County"},
        "65649": {"Polk County": "Polk County"},
        "65650": {"Polk County": "Polk County"},
        "65663": {"Polk County": "Polk County"},
        "65674": {"Polk County": "Polk County"},
        "65710": {"Polk County": "Polk County"},
        "65725": {"Polk County": "Polk County"},
        "65727": {"Polk County": "Polk County"},
        # Pulaski County
        "65452": {"Pulaski County": "Pulaski County"},
        "65457": {"Pulaski County": "Pulaski County"},
        "65459": {"Pulaski County": "Pulaski County"},
        "65473": {"Pulaski County": "Pulaski County"},
        "65534": {"Pulaski County": "Pulaski County"},
        "65556": {"Pulaski County": "Pulaski County"},
        "65583": {"Pulaski County": "Pulaski County"},
        "65584": {"Pulaski County": "Pulaski County"},
        # Putnam County
        "63551": {"Putnam County": "Putnam County"},
        "63565": {"Putnam County": "Putnam County"},
        "63567": {"Putnam County": "Putnam County"},
        "64655": {"Putnam County": "Putnam County"},
        "64672": {"Putnam County": "Putnam County"},
        # Ralls County
        "63436": {"Ralls County": "Ralls County"},
        "63459": {"Ralls County": "Ralls County"},
        "63462": {"Ralls County": "Ralls County"},
        "63467": {"Ralls County": "Ralls County"},
        # Randolph County
        "65239": {"Randolph County": "Randolph County"},
        "65243": {"Randolph County": "Randolph County"},
        "65244": {"Randolph County": "Randolph County"},
        "65257": {"Randolph County": "Randolph County"},
        "65259": {"Randolph County": "Randolph County"},
        "65260": {"Randolph County": "Randolph County"},
        "65270": {"Randolph County": "Randolph County"},
        "65278": {"Randolph County": "Randolph County"},
        # Ray County
        "64017": {"Ray County": "Ray County"},
        "64035": {"Ray County": "Ray County"},
        "64036": {"Ray County": "Ray County"},
        "64062": {"Ray County": "Ray County"},
        "64077": {"Ray County": "Ray County"},
        "64084": {"Ray County": "Ray County"},
        "64085": {"Ray County": "Ray County"},
        # Reynolds County
        "63625": {"Reynolds County": "Reynolds County"},
        "63629": {"Reynolds County": "Reynolds County"},
        "63633": {"Reynolds County": "Reynolds County"},
        "63638": {"Reynolds County": "Reynolds County"},
        "63654": {"Reynolds County": "Reynolds County"},
        "63665": {"Reynolds County": "Reynolds County"},
        "63666": {"Reynolds County": "Reynolds County"},
        # Ripley County
        "63931": {"Ripley County": "Ripley County"},
        "63935": {"Ripley County": "Ripley County"},
        "63939": {"Ripley County": "Ripley County"},
        "63942": {"Ripley County": "Ripley County"},
        "63953": {"Ripley County": "Ripley County"},
        "63955": {"Ripley County": "Ripley County"},
        # Saline County
        "65320": {"Saline County": "Saline County"},
        "65321": {"Saline County": "Saline County"},
        "65327": {"Saline County": "Saline County"},
        "65330": {"Saline County": "Saline County"},
        "65339": {"Saline County": "Saline County"},
        "65340": {"Saline County": "Saline County"},
        "65344": {"Saline County": "Saline County"},
        "65347": {"Saline County": "Saline County"},
        "65349": {"Saline County": "Saline County"},
        "65351": {"Saline County": "Saline County"},
        # Schuyler County
        "63535": {"Schuyler County": "Schuyler County"},
        "63536": {"Schuyler County": "Schuyler County"},
        "63541": {"Schuyler County": "Schuyler County"},
        "63548": {"Schuyler County": "Schuyler County"},
        "63561": {"Schuyler County": "Schuyler County"},
        # Scotland County
        "63432": {"Scotland County": "Scotland County"},
        "63442": {"Scotland County": "Scotland County"},
        "63543": {"Scotland County": "Scotland County"},
        "63555": {"Scotland County": "Scotland County"},
        "63563": {"Scotland County": "Scotland County"},
        # Scott County
        "63736": {"Scott County": "Scott County"},
        "63740": {"Scott County": "Scott County"},
        "63742": {"Scott County": "Scott County"},
        "63758": {"Scott County": "Scott County"},
        "63767": {"Scott County": "Scott County"},
        "63771": {"Scott County": "Scott County"},
        "63774": {"Scott County": "Scott County"},
        "63780": {"Scott County": "Scott County"},
        "63784": {"Scott County": "Scott County"},
        "63801": {"Scott County": "Scott County"},
        "63824": {"Scott County": "Scott County"},
        # Shannon County
        "65438": {"Shannon County": "Shannon County"},
        "65466": {"Shannon County": "Shannon County"},
        "65546": {"Shannon County": "Shannon County"},
        "65588": {"Shannon County": "Shannon County"},
        # Shelby County
        "63434": {"Shelby County": "Shelby County"},
        "63437": {"Shelby County": "Shelby County"},
        "63439": {"Shelby County": "Shelby County"},
        "63443": {"Shelby County": "Shelby County"},
        "63450": {"Shelby County": "Shelby County"},
        "63451": {"Shelby County": "Shelby County"},
        "63468": {"Shelby County": "Shelby County"},
        "63469": {"Shelby County": "Shelby County"},
        # St. Charles County
        "63301": {"St. Charles County": "St. Charles County"},
        "63302": {"St. Charles County": "St. Charles County"},
        "63303": {"St. Charles County": "St. Charles County"},
        "63304": {"St. Charles County": "St. Charles County"},
        "63332": {"St. Charles County": "St. Charles County"},
        "63338": {"St. Charles County": "St. Charles County"},
        "63341": {"St. Charles County": "St. Charles County"},
        "63346": {"St. Charles County": "St. Charles County"},
        "63348": {"St. Charles County": "St. Charles County"},
        "63365": {"St. Charles County": "St. Charles County"},
        "63366": {"St. Charles County": "St. Charles County"},
        "63367": {"St. Charles County": "St. Charles County"},
        "63368": {"St. Charles County": "St. Charles County"},
        "63373": {"St. Charles County": "St. Charles County"},
        "63376": {"St. Charles County": "St. Charles County"},
        "63385": {"St. Charles County": "St. Charles County"},
        "63386": {"St. Charles County": "St. Charles County"},
        # St. Clair County
        "64724": {"St. Clair County": "St. Clair County"},
        "64738": {"St. Clair County": "St. Clair County"},
        "64763": {"St. Clair County": "St. Clair County"},
        "64776": {"St. Clair County": "St. Clair County"},
        "64781": {"St. Clair County": "St. Clair County"},
        # St. Francois County
        "63036": {"St. Francois County": "St. Francois County"},
        "63087": {"St. Francois County": "St. Francois County"},
        "63601": {"St. Francois County": "St. Francois County"},
        "63624": {"St. Francois County": "St. Francois County"},
        "63628": {"St. Francois County": "St. Francois County"},
        "63637": {"St. Francois County": "St. Francois County"},
        "63640": {"St. Francois County": "St. Francois County"},
        "63651": {"St. Francois County": "St. Francois County"},
        "63653": {"St. Francois County": "St. Francois County"},
        # St. Louis City
        "63101": {"St. Louis City": "St. Louis City"},
        "63102": {"St. Louis City": "St. Louis City"},
        "63103": {"St. Louis City": "St. Louis City"},
        "63104": {"St. Louis City": "St. Louis City"},
        "63106": {"St. Louis City": "St. Louis City"},
        "63107": {"St. Louis City": "St. Louis City"},
        "63108": {"St. Louis City": "St. Louis City"},
        "63109": {"St. Louis City": "St. Louis City"},
        "63110": {"St. Louis City": "St. Louis City"},
        "63111": {"St. Louis City": "St. Louis City"},
        "63112": {"St. Louis City": "St. Louis City"},
        "63113": {"St. Louis City": "St. Louis City"},
        "63115": {"St. Louis City": "St. Louis City"},
        "63116": {"St. Louis City": "St. Louis City"},
        "63118": {"St. Louis City": "St. Louis City"},
        "63120": {"St. Louis City": "St. Louis City"},
        "63139": {"St. Louis City": "St. Louis City"},
        "63147": {"St. Louis City": "St. Louis City"},
        "63150": {"St. Louis City": "St. Louis City"},
        "63155": {"St. Louis City": "St. Louis City"},
        "63156": {"St. Louis City": "St. Louis City"},
        "63160": {"St. Louis City": "St. Louis City"},
        "63164": {"St. Louis City": "St. Louis City"},
        "63166": {"St. Louis City": "St. Louis City"},
        "63177": {"St. Louis City": "St. Louis City"},
        "63178": {"St. Louis City": "St. Louis City"},
        "63180": {"St. Louis City": "St. Louis City"},
        # St. Louis County
        "63005": {"St. Louis County": "St. Louis County"},
        "63006": {"St. Louis County": "St. Louis County"},
        "63011": {"St. Louis County": "St. Louis County"},
        "63017": {"St. Louis County": "St. Louis County"},
        "63021": {"St. Louis County": "St. Louis County"},
        "63022": {"St. Louis County": "St. Louis County"},
        "63024": {"St. Louis County": "St. Louis County"},
        "63025": {"St. Louis County": "St. Louis County"},
        "63026": {"St. Louis County": "St. Louis County"},
        "63031": {"St. Louis County": "St. Louis County"},
        "63032": {"St. Louis County": "St. Louis County"},
        "63033": {"St. Louis County": "St. Louis County"},
        "63034": {"St. Louis County": "St. Louis County"},
        "63038": {"St. Louis County": "St. Louis County"},
        "63040": {"St. Louis County": "St. Louis County"},
        "63042": {"St. Louis County": "St. Louis County"},
        "63043": {"St. Louis County": "St. Louis County"},
        "63044": {"St. Louis County": "St. Louis County"},
        "63045": {"St. Louis County": "St. Louis County"},
        "63074": {"St. Louis County": "St. Louis County"},
        "63088": {"St. Louis County": "St. Louis County"},
        "63105": {"St. Louis County": "St. Louis County"},
        "63114": {"St. Louis County": "St. Louis County"},
        "63117": {"St. Louis County": "St. Louis County"},
        "63119": {"St. Louis County": "St. Louis County"},
        "63121": {"St. Louis County": "St. Louis County"},
        "63122": {"St. Louis County": "St. Louis County"},
        "63123": {"St. Louis County": "St. Louis County"},
        "63124": {"St. Louis County": "St. Louis County"},
        "63125": {"St. Louis County": "St. Louis County"},
        "63126": {"St. Louis County": "St. Louis County"},
        "63127": {"St. Louis County": "St. Louis County"},
        "63128": {"St. Louis County": "St. Louis County"},
        "63129": {"St. Louis County": "St. Louis County"},
        "63130": {"St. Louis County": "St. Louis County"},
        "63131": {"St. Louis County": "St. Louis County"},
        "63132": {"St. Louis County": "St. Louis County"},
        "63133": {"St. Louis County": "St. Louis County"},
        "63134": {"St. Louis County": "St. Louis County"},
        "63135": {"St. Louis County": "St. Louis County"},
        "63136": {"St. Louis County": "St. Louis County"},
        "63137": {"St. Louis County": "St. Louis County"},
        "63138": {"St. Louis County": "St. Louis County"},
        "63140": {"St. Louis County": "St. Louis County"},
        "63141": {"St. Louis County": "St. Louis County"},
        "63143": {"St. Louis County": "St. Louis County"},
        "63144": {"St. Louis County": "St. Louis County"},
        "63145": {"St. Louis County": "St. Louis County"},
        "63146": {"St. Louis County": "St. Louis County"},
        "63151": {"St. Louis County": "St. Louis County"},
        "63167": {"St. Louis County": "St. Louis County"},
        "63171": {"St. Louis County": "St. Louis County"},
        # Ste. Genevieve County
        "63627": {"Ste. Genevieve County": "Ste. Genevieve County"},
        "63670": {"Ste. Genevieve County": "Ste. Genevieve County"},
        "63673": {"Ste. Genevieve County": "Ste. Genevieve County"},
        # Stoddard County
        "63730": {"Stoddard County": "Stoddard County"},
        "63735": {"Stoddard County": "Stoddard County"},
        "63738": {"Stoddard County": "Stoddard County"},
        "63822": {"Stoddard County": "Stoddard County"},
        "63825": {"Stoddard County": "Stoddard County"},
        "63841": {"Stoddard County": "Stoddard County"},
        "63846": {"Stoddard County": "Stoddard County"},
        "63850": {"Stoddard County": "Stoddard County"},
        "63936": {"Stoddard County": "Stoddard County"},
        "63960": {"Stoddard County": "Stoddard County"},
        # Stone County
        "65611": {"Stone County": "Stone County"},
        "65624": {"Stone County": "Stone County"},
        "65633": {"Stone County": "Stone County"},
        "65656": {"Stone County": "Stone County"},
        "65675": {"Stone County": "Stone County"},
        "65681": {"Stone County": "Stone County"},
        "65686": {"Stone County": "Stone County"},
        "65728": {"Stone County": "Stone County"},
        "65737": {"Stone County": "Stone County"},
        # Sullivan County
        "63544": {"Sullivan County": "Sullivan County"},
        "63545": {"Sullivan County": "Sullivan County"},
        "63556": {"Sullivan County": "Sullivan County"},
        "63560": {"Sullivan County": "Sullivan County"},
        "63566": {"Sullivan County": "Sullivan County"},
        "64645": {"Sullivan County": "Sullivan County"},
        "64646": {"Sullivan County": "Sullivan County"},
        "64667": {"Sullivan County": "Sullivan County"},
        # Taney County
        "65608": {"Taney County": "Taney County"},
        "65614": {"Taney County": "Taney County"},
        "65615": {"Taney County": "Taney County"},
        "65616": {"Taney County": "Taney County"},
        "65627": {"Taney County": "Taney County"},
        "65653": {"Taney County": "Taney County"},
        "65672": {"Taney County": "Taney County"},
        "65673": {"Taney County": "Taney County"},
        "65679": {"Taney County": "Taney County"},
        "65680": {"Taney County": "Taney County"},
        "65726": {"Taney County": "Taney County"},
        "65731": {"Taney County": "Taney County"},
        "65733": {"Taney County": "Taney County"},
        "65739": {"Taney County": "Taney County"},
        "65740": {"Taney County": "Taney County"},
        "65744": {"Taney County": "Taney County"},
        "65759": {"Taney County": "Taney County"},
        "65771": {"Taney County": "Taney County"},
        # Texas County
        "65444": {"Texas County": "Texas County"},
        "65464": {"Texas County": "Texas County"},
        "65468": {"Texas County": "Texas County"},
        "65479": {"Texas County": "Texas County"},
        "65483": {"Texas County": "Texas County"},
        "65484": {"Texas County": "Texas County"},
        "65542": {"Texas County": "Texas County"},
        "65552": {"Texas County": "Texas County"},
        "65555": {"Texas County": "Texas County"},
        "65557": {"Texas County": "Texas County"},
        "65564": {"Texas County": "Texas County"},
        "65570": {"Texas County": "Texas County"},
        "65571": {"Texas County": "Texas County"},
        "65589": {"Texas County": "Texas County"},
        "65689": {"Texas County": "Texas County"},
        # Vernon County
        "64728": {"Vernon County": "Vernon County"},
        "64741": {"Vernon County": "Vernon County"},
        "64750": {"Vernon County": "Vernon County"},
        "64765": {"Vernon County": "Vernon County"},
        "64767": {"Vernon County": "Vernon County"},
        "64771": {"Vernon County": "Vernon County"},
        "64772": {"Vernon County": "Vernon County"},
        "64778": {"Vernon County": "Vernon County"},
        "64783": {"Vernon County": "Vernon County"},
        "64784": {"Vernon County": "Vernon County"},
        "64790": {"Vernon County": "Vernon County"},
        # Warren County
        "63342": {"Warren County": "Warren County"},
        "63357": {"Warren County": "Warren County"},
        "63378": {"Warren County": "Warren County"},
        "63380": {"Warren County": "Warren County"},
        "63383": {"Warren County": "Warren County"},
        "63390": {"Warren County": "Warren County"},
        # Washington County
        "63030": {"Washington County": "Washington County"},
        "63071": {"Washington County": "Washington County"},
        "63622": {"Washington County": "Washington County"},
        "63626": {"Washington County": "Washington County"},
        "63630": {"Washington County": "Washington County"},
        "63631": {"Washington County": "Washington County"},
        "63648": {"Washington County": "Washington County"},
        "63660": {"Washington County": "Washington County"},
        "63664": {"Washington County": "Washington County"},
        "63674": {"Washington County": "Washington County"},
        # Wayne County
        "63763": {"Wayne County": "Wayne County"},
        "63934": {"Wayne County": "Wayne County"},
        "63944": {"Wayne County": "Wayne County"},
        "63950": {"Wayne County": "Wayne County"},
        "63951": {"Wayne County": "Wayne County"},
        "63952": {"Wayne County": "Wayne County"},
        "63956": {"Wayne County": "Wayne County"},
        "63957": {"Wayne County": "Wayne County"},
        "63964": {"Wayne County": "Wayne County"},
        "63966": {"Wayne County": "Wayne County"},
        # Webster County
        "65636": {"Webster County": "Webster County"},
        "65652": {"Webster County": "Webster County"},
        "65706": {"Webster County": "Webster County"},
        "65713": {"Webster County": "Webster County"},
        "65742": {"Webster County": "Webster County"},
        "65746": {"Webster County": "Webster County"},
        # Worth County
        "64420": {"Worth County": "Worth County"},
        "64441": {"Worth County": "Worth County"},
        "64456": {"Worth County": "Worth County"},
        "64486": {"Worth County": "Worth County"},
        "64499": {"Worth County": "Worth County"},
        # Wright County
        "65660": {"Wright County": "Wright County"},
        "65662": {"Wright County": "Wright County"},
        "65667": {"Wright County": "Wright County"},
        "65702": {"Wright County": "Wright County"},
        "65704": {"Wright County": "Wright County"},
        "65711": {"Wright County": "Wright County"},
        "65717": {"Wright County": "Wright County"},
    }

    # ==========================================================================================
    # CATEGORY BENEFITS
    # Benefits shown on the "Do you already have any benefits?" step.
    # ==========================================================================================

    category_benefits = {
        "foodAndNutrition": {
            "benefits": {
                "snap": {
                    "name": {
                        "_label": "foodAndNutritionBenefits.snap",
                        "_default_message": "Supplemental Nutrition Assistance Program (SNAP): ",
                    },
                    "description": {
                        "_label": "foodAndNutritionBenefits.snap_desc",
                        "_default_message": "Food assistance",
                    },
                },
                "wic": {
                    "name": {
                        "_label": "foodAndNutritionBenefits.wic",
                        "_default_message": "Special Supplemental Nutrition Program for Women, Infants, and Children (WIC): ",
                    },
                    "description": {
                        "_label": "foodAndNutritionBenefits.wic_desc",
                        "_default_message": "Food and breastfeeding assistance",
                    },
                },
                "nslp": {
                    "name": {
                        "_label": "foodAndNutritionBenefits.nslp",
                        "_default_message": "National School Lunch Program: ",
                    },
                    "description": {
                        "_label": "foodAndNutritionBenefits.nslp_desc",
                        "_default_message": "Free school meals",
                    },
                },
            },
            "category_name": {
                "_label": "foodAndNutrition",
                "_default_message": "Food and Nutrition",
            },
        },
        "cash": {
            "benefits": {
                "ssdi": {
                    "name": {
                        "_label": "cashAssistanceBenefits.ssdi",
                        "_default_message": "Social Security Disability Insurance (SSDI): ",
                    },
                    "description": {
                        "_label": "cashAssistanceBenefits.ssdi_desc",
                        "_default_message": "Social security benefit for people with disabilities",
                    },
                },
                "ssi": {
                    "name": {
                        "_label": "cashAssistanceBenefits.ssi",
                        "_default_message": "Supplemental Security Income (SSI): ",
                    },
                    "description": {
                        "_label": "cashAssistanceBenefits.ssi_desc",
                        "_default_message": "Federal cash assistance for individuals who are disabled, blind, or 65 years of age or older",
                    },
                },
                "tanf": {
                    "name": {
                        "_label": "cashAssistanceBenefits.tanf",
                        "_default_message": "Temporary Assistance for Needy Families (TANF): ",
                    },
                    "description": {
                        "_label": "cashAssistanceBenefits.tanf_desc",
                        "_default_message": "Cash assistance for families with children",
                    },
                },
            },
            "category_name": {
                "_label": "cashAssistance",
                "_default_message": "Cash Assistance",
            },
        },
        "healthCare": {
            "benefits": {
                "medicaid": {
                    "name": {
                        "_label": "healthCareBenefits.medicaid.mo",
                        "_default_message": "MO HealthNet (Medicaid): ",
                    },
                    "description": {
                        "_label": "healthCareBenefits.medicaid_desc",
                        "_default_message": "Free or low-cost health coverage",
                    },
                },
                "medicare_savings": {
                    "name": {
                        "_label": "healthCareBenefits.medicare_savings",
                        "_default_message": "Medicare Savings Program: ",
                    },
                    "description": {
                        "_label": "healthCareBenefits.medicare_savings_desc",
                        "_default_message": "Help paying Medicare premiums and costs",
                    },
                },
            },
            "category_name": {
                "_label": "healthCare",
                "_default_message": "Health Care",
            },
        },
    }

    # ==========================================================================================
    # REFERRER DATA
    # ==========================================================================================

    # MO uses generic MFB branding and the default step directory, so it inherits
    # everything from base and overrides only the values that are MO-specific:
    # the share link, the state name, and the Kansas City metro referrer.
    referrer_data = {
        **ConfigurationData.referrer_data,
        # "uwgkc" is United Way of Greater Kansas City, whose 2-1-1 covers the metro on both sides
        # of the state line. The same referrer code is configured identically in ks.py, since each
        # state path loads its own config.
        "theme": {"default": "default", "uwgkc": "uwgkc"},
        "logoSource": {"default": "MFB_Logo", "uwgkc": "MO211_MFBLogo"},
        "logoAlt": {
            "default": {
                "id": "referrerHook.logoAlts.default",
                "defaultMessage": "MyFriendBen home page button",
            },
            "uwgkc": {
                "id": "referrerHook.logoAlts.mo211",
                "defaultMessage": "211 Missouri and MyFriendBen home page button",
            },
        },
        # The co-branded logo's MyFriendBen wordmark is dark navy, which would disappear against
        # the theme's dark blue header, so this referrer gets the white header treatment.
        "uiOptions": {"default": [], "uwgkc": ["white_header"]},
        "logoClass": {"default": "logo", "uwgkc": "uwgkc-logo-size"},
        "shareLink": {
            "default": "https://screener.myfriendben.org/mo/step-1",
            "uwgkc": "https://screener.myfriendben.org/mo/step-1?referrer=uwgkc",
        },
        "stateOptions": {"default": [], "uwgkc": ["ks", "mo"]},
        # Blank for uwgkc: its logo already carries "Missouri", so the header's separate state name
        # would repeat it underneath the artwork.
        "stateName": {"default": "Missouri", "uwgkc": ""},
    }
