from .base import ConfigurationData
from screener.models import WhiteLabel


class WaConfigurationData(ConfigurationData):
    @classmethod
    def get_white_label(self) -> WhiteLabel:
        return WhiteLabel.objects.get(code="wa")

    # ==========================================================================================
    # BASIC INFORMATION
    # ==========================================================================================

    # Live in production and offered in the public state dropdown.
    publicly_launched = True

    state = {"name": "Washington"}

    public_charge_rule = {
        "link": "https://www.dshs.wa.gov/esa/csd-office-refugee-and-immigration-assistance/public-charge-information",
        "text": {
            "_label": "landingPage.publicChargeLinkWA",
            "_default_message": "Washington State Department of Social and Health Services",
        },
    }

    more_help_options = {
        "moreHelpOptions": [
            {
                "name": {
                    "_default_message": "211 Washington",
                    "_label": "moreHelp.211.name.wa",
                },
                "link": "https://wa211.org/",
                "phone": {
                    "_default_message": "Dial 2-1-1",
                    "_label": "moreHelp.211.phone.wa",
                },
            },
        ]
    }

    # ==========================================================================================
    # ADDITIONAL RESOURCES (Acute conditions step)
    # ==========================================================================================

    acute_condition_options = {
        **ConfigurationData.acute_condition_options,
        "agingResources": {
            "icon": {"_icon": "Aging", "_classname": "option-card-icon"},
            "text": {
                "_label": "acuteConditionOptions.agingResources",
                "_default_message": "Aging Community Resources",
            },
        },
    }

    # ==========================================================================================
    # HEALTH INSURANCE OPTIONS
    # Washington Medicaid is "Apple Health"; CHIP equivalent is "Apple Health for Kids"
    # ==========================================================================================

    health_insurance_options = {
        "you": {
            **ConfigurationData.health_insurance_options["you"],
            "medicaid": {
                "icon": {"_icon": "Medicaid", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.medicaid.wa",
                    "_default_message": "Apple Health (Medicaid)",
                },
            },
            "chp": {
                "icon": {"_icon": "Chp", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.chp.wa",
                    "_default_message": "Apple Health for Kids",
                },
            },
        },
        "them": {
            **ConfigurationData.health_insurance_options["them"],
            "medicaid": {
                "icon": {"_icon": "Medicaid", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.medicaid.wa",
                    "_default_message": "Apple Health (Medicaid)",
                },
            },
            "chp": {
                "icon": {"_icon": "Chp", "_classname": "option-card-icon"},
                "text": {
                    "_label": "healthInsuranceOptions.chp.wa",
                    "_default_message": "Apple Health for Kids",
                },
            },
        },
    }

    # ==========================================================================================
    # COUNTIES BY ZIPCODE
    # Download the latest ZIP-County crosswalk file from:
    #   https://www.huduser.gov/apps/public/uspscrosswalk/login
    # Select "ZIP-County" and state "WA", then parse into this dictionary.
    # ==========================================================================================

    counties_by_zipcode = {
        "98001": {
            "King County": "King County",
            "Pierce County": "Pierce County",
        },
        "98002": {"King County": "King County"},
        "98003": {"King County": "King County"},
        "98004": {"King County": "King County"},
        "98005": {"King County": "King County"},
        "98006": {"King County": "King County"},
        "98007": {"King County": "King County"},
        "98008": {"King County": "King County"},
        "98009": {"King County": "King County"},
        "98010": {"King County": "King County"},
        "98011": {
            "King County": "King County",
            "Snohomish County": "Snohomish County",
        },
        "98012": {"Snohomish County": "Snohomish County"},
        "98014": {"King County": "King County"},
        "98015": {"King County": "King County"},
        "98019": {
            "King County": "King County",
            "Snohomish County": "Snohomish County",
        },
        "98020": {"Snohomish County": "Snohomish County"},
        "98021": {"Snohomish County": "Snohomish County"},
        "98022": {
            "King County": "King County",
            "Pierce County": "Pierce County",
        },
        "98023": {
            "King County": "King County",
            "Pierce County": "Pierce County",
        },
        "98024": {"King County": "King County"},
        "98025": {"King County": "King County"},
        "98026": {"Snohomish County": "Snohomish County"},
        "98027": {"King County": "King County"},
        "98028": {
            "King County": "King County",
            "Snohomish County": "Snohomish County",
        },
        "98029": {"King County": "King County"},
        "98030": {"King County": "King County"},
        "98031": {"King County": "King County"},
        "98032": {"King County": "King County"},
        "98033": {"King County": "King County"},
        "98034": {"King County": "King County"},
        "98035": {"King County": "King County"},
        "98036": {
            "King County": "King County",
            "Snohomish County": "Snohomish County",
        },
        "98037": {"Snohomish County": "Snohomish County"},
        "98038": {"King County": "King County"},
        "98039": {"King County": "King County"},
        "98040": {"King County": "King County"},
        "98041": {"King County": "King County"},
        "98042": {"King County": "King County"},
        "98043": {
            "King County": "King County",
            "Snohomish County": "Snohomish County",
        },
        "98045": {"King County": "King County"},
        "98046": {"Snohomish County": "Snohomish County"},
        "98047": {
            "King County": "King County",
            "Pierce County": "Pierce County",
        },
        "98050": {"King County": "King County"},
        "98051": {"King County": "King County"},
        "98052": {"King County": "King County"},
        "98053": {"King County": "King County"},
        "98055": {"King County": "King County"},
        "98056": {"King County": "King County"},
        "98057": {"King County": "King County"},
        "98058": {"King County": "King County"},
        "98059": {"King County": "King County"},
        "98061": {"Kitsap County": "Kitsap County"},
        "98062": {"King County": "King County"},
        "98063": {"King County": "King County"},
        "98064": {"King County": "King County"},
        "98065": {"King County": "King County"},
        "98068": {
            "King County": "King County",
            "Kittitas County": "Kittitas County",
        },
        "98070": {"King County": "King County"},
        "98071": {"King County": "King County"},
        "98072": {
            "King County": "King County",
            "Snohomish County": "Snohomish County",
        },
        "98073": {"King County": "King County"},
        "98074": {"King County": "King County"},
        "98075": {"King County": "King County"},
        "98077": {
            "King County": "King County",
            "Snohomish County": "Snohomish County",
        },
        "98082": {"Snohomish County": "Snohomish County"},
        "98083": {"King County": "King County"},
        "98087": {"Snohomish County": "Snohomish County"},
        "98089": {"King County": "King County"},
        "98092": {
            "King County": "King County",
            "Pierce County": "Pierce County",
        },
        "98093": {"King County": "King County"},
        "98101": {"King County": "King County"},
        "98102": {"King County": "King County"},
        "98103": {"King County": "King County"},
        "98104": {"King County": "King County"},
        "98105": {"King County": "King County"},
        "98106": {"King County": "King County"},
        "98107": {"King County": "King County"},
        "98108": {"King County": "King County"},
        "98109": {"King County": "King County"},
        "98110": {
            "King County": "King County",
            "Kitsap County": "Kitsap County",
        },
        "98111": {"King County": "King County"},
        "98112": {"King County": "King County"},
        "98113": {"King County": "King County"},
        "98114": {"King County": "King County"},
        "98115": {"King County": "King County"},
        "98116": {"King County": "King County"},
        "98117": {"King County": "King County"},
        "98118": {"King County": "King County"},
        "98119": {"King County": "King County"},
        "98121": {"King County": "King County"},
        "98122": {"King County": "King County"},
        "98124": {"King County": "King County"},
        "98125": {"King County": "King County"},
        "98126": {"King County": "King County"},
        "98127": {"King County": "King County"},
        "98129": {"King County": "King County"},
        "98131": {"King County": "King County"},
        "98133": {"King County": "King County"},
        "98134": {"King County": "King County"},
        "98136": {"King County": "King County"},
        "98138": {"King County": "King County"},
        "98139": {"King County": "King County"},
        "98144": {"King County": "King County"},
        "98145": {"King County": "King County"},
        "98146": {"King County": "King County"},
        "98148": {"King County": "King County"},
        "98154": {"King County": "King County"},
        "98155": {"King County": "King County"},
        "98158": {"King County": "King County"},
        "98161": {"King County": "King County"},
        "98164": {"King County": "King County"},
        "98165": {"King County": "King County"},
        "98166": {"King County": "King County"},
        "98168": {"King County": "King County"},
        "98170": {"King County": "King County"},
        "98174": {"King County": "King County"},
        "98175": {"King County": "King County"},
        "98177": {
            "King County": "King County",
            "Snohomish County": "Snohomish County",
        },
        "98178": {"King County": "King County"},
        "98181": {"King County": "King County"},
        "98185": {"King County": "King County"},
        "98188": {"King County": "King County"},
        "98191": {"King County": "King County"},
        "98194": {"King County": "King County"},
        "98195": {"King County": "King County"},
        "98198": {"King County": "King County"},
        "98199": {"King County": "King County"},
        "98201": {"Snohomish County": "Snohomish County"},
        "98203": {"Snohomish County": "Snohomish County"},
        "98204": {"Snohomish County": "Snohomish County"},
        "98206": {"Snohomish County": "Snohomish County"},
        "98207": {"Snohomish County": "Snohomish County"},
        "98208": {"Snohomish County": "Snohomish County"},
        "98213": {"Snohomish County": "Snohomish County"},
        "98220": {"Whatcom County": "Whatcom County"},
        "98221": {
            "San Juan County": "San Juan County",
            "Skagit County": "Skagit County",
        },
        "98222": {"San Juan County": "San Juan County"},
        "98223": {"Snohomish County": "Snohomish County"},
        "98224": {"King County": "King County"},
        "98225": {"Whatcom County": "Whatcom County"},
        "98226": {"Whatcom County": "Whatcom County"},
        "98227": {"Whatcom County": "Whatcom County"},
        "98228": {"Whatcom County": "Whatcom County"},
        "98229": {
            "Skagit County": "Skagit County",
            "Whatcom County": "Whatcom County",
        },
        "98230": {"Whatcom County": "Whatcom County"},
        "98231": {"Whatcom County": "Whatcom County"},
        "98232": {"Skagit County": "Skagit County"},
        "98233": {"Skagit County": "Skagit County"},
        "98235": {"Skagit County": "Skagit County"},
        "98236": {"Island County": "Island County"},
        "98237": {
            "Skagit County": "Skagit County",
            "Whatcom County": "Whatcom County",
        },
        "98238": {"Skagit County": "Skagit County"},
        "98239": {"Island County": "Island County"},
        "98240": {"Whatcom County": "Whatcom County"},
        "98241": {
            "Skagit County": "Skagit County",
            "Snohomish County": "Snohomish County",
        },
        "98243": {"San Juan County": "San Juan County"},
        "98244": {"Whatcom County": "Whatcom County"},
        "98245": {"San Juan County": "San Juan County"},
        "98247": {"Whatcom County": "Whatcom County"},
        "98248": {"Whatcom County": "Whatcom County"},
        "98249": {"Island County": "Island County"},
        "98250": {"San Juan County": "San Juan County"},
        "98251": {
            "King County": "King County",
            "Snohomish County": "Snohomish County",
        },
        "98252": {"Snohomish County": "Snohomish County"},
        "98253": {"Island County": "Island County"},
        "98255": {"Skagit County": "Skagit County"},
        "98256": {"Snohomish County": "Snohomish County"},
        "98257": {"Skagit County": "Skagit County"},
        "98258": {"Snohomish County": "Snohomish County"},
        "98259": {"Snohomish County": "Snohomish County"},
        "98260": {"Island County": "Island County"},
        "98261": {"San Juan County": "San Juan County"},
        "98262": {"Whatcom County": "Whatcom County"},
        "98263": {"Skagit County": "Skagit County"},
        "98264": {"Whatcom County": "Whatcom County"},
        "98266": {"Whatcom County": "Whatcom County"},
        "98267": {"Skagit County": "Skagit County"},
        "98270": {"Snohomish County": "Snohomish County"},
        "98271": {"Snohomish County": "Snohomish County"},
        "98272": {"Snohomish County": "Snohomish County"},
        "98273": {"Skagit County": "Skagit County"},
        "98274": {"Skagit County": "Skagit County"},
        "98275": {"Snohomish County": "Snohomish County"},
        "98276": {"Whatcom County": "Whatcom County"},
        "98277": {"Island County": "Island County"},
        "98278": {"Island County": "Island County"},
        "98279": {"San Juan County": "San Juan County"},
        "98280": {"San Juan County": "San Juan County"},
        "98281": {"Whatcom County": "Whatcom County"},
        "98282": {
            "Island County": "Island County",
            "Snohomish County": "Snohomish County",
        },
        "98283": {
            "Skagit County": "Skagit County",
            "Whatcom County": "Whatcom County",
        },
        "98284": {
            "Skagit County": "Skagit County",
            "Whatcom County": "Whatcom County",
        },
        "98286": {"San Juan County": "San Juan County"},
        "98287": {"Snohomish County": "Snohomish County"},
        "98288": {"King County": "King County"},
        "98290": {"Snohomish County": "Snohomish County"},
        "98291": {"Snohomish County": "Snohomish County"},
        "98292": {
            "Skagit County": "Skagit County",
            "Snohomish County": "Snohomish County",
        },
        "98293": {"Snohomish County": "Snohomish County"},
        "98294": {"Snohomish County": "Snohomish County"},
        "98295": {"Whatcom County": "Whatcom County"},
        "98296": {"Snohomish County": "Snohomish County"},
        "98297": {"San Juan County": "San Juan County"},
        "98303": {"Pierce County": "Pierce County"},
        "98304": {
            "Lewis County": "Lewis County",
            "Pierce County": "Pierce County",
        },
        "98305": {"Clallam County": "Clallam County"},
        "98310": {"Kitsap County": "Kitsap County"},
        "98311": {"Kitsap County": "Kitsap County"},
        "98312": {
            "Kitsap County": "Kitsap County",
            "Mason County": "Mason County",
        },
        "98314": {"Kitsap County": "Kitsap County"},
        "98315": {"Kitsap County": "Kitsap County"},
        "98320": {"Jefferson County": "Jefferson County"},
        "98321": {"Pierce County": "Pierce County"},
        "98322": {"Kitsap County": "Kitsap County"},
        "98323": {"Pierce County": "Pierce County"},
        "98324": {"Clallam County": "Clallam County"},
        "98325": {"Jefferson County": "Jefferson County"},
        "98326": {"Clallam County": "Clallam County"},
        "98327": {"Pierce County": "Pierce County"},
        "98328": {"Pierce County": "Pierce County"},
        "98329": {
            "Kitsap County": "Kitsap County",
            "Pierce County": "Pierce County",
        },
        "98330": {
            "Lewis County": "Lewis County",
            "Pierce County": "Pierce County",
        },
        "98331": {
            "Clallam County": "Clallam County",
            "Jefferson County": "Jefferson County",
        },
        "98332": {"Pierce County": "Pierce County"},
        "98333": {"Pierce County": "Pierce County"},
        "98335": {"Pierce County": "Pierce County"},
        "98336": {"Lewis County": "Lewis County"},
        "98337": {"Kitsap County": "Kitsap County"},
        "98338": {"Pierce County": "Pierce County"},
        "98339": {"Jefferson County": "Jefferson County"},
        "98340": {"Kitsap County": "Kitsap County"},
        "98342": {"Kitsap County": "Kitsap County"},
        "98343": {"Clallam County": "Clallam County"},
        "98344": {"Pierce County": "Pierce County"},
        "98345": {"Kitsap County": "Kitsap County"},
        "98346": {"Kitsap County": "Kitsap County"},
        "98348": {"Pierce County": "Pierce County"},
        "98349": {"Pierce County": "Pierce County"},
        "98350": {"Clallam County": "Clallam County"},
        "98351": {"Pierce County": "Pierce County"},
        "98352": {"Pierce County": "Pierce County"},
        "98353": {"Kitsap County": "Kitsap County"},
        "98354": {
            "King County": "King County",
            "Pierce County": "Pierce County",
        },
        "98355": {"Lewis County": "Lewis County"},
        "98356": {"Lewis County": "Lewis County"},
        "98357": {"Clallam County": "Clallam County"},
        "98358": {"Jefferson County": "Jefferson County"},
        "98359": {
            "Kitsap County": "Kitsap County",
            "Pierce County": "Pierce County",
        },
        "98360": {"Pierce County": "Pierce County"},
        "98361": {"Lewis County": "Lewis County"},
        "98362": {"Clallam County": "Clallam County"},
        "98363": {"Clallam County": "Clallam County"},
        "98364": {"Kitsap County": "Kitsap County"},
        "98365": {"Jefferson County": "Jefferson County"},
        "98366": {"Kitsap County": "Kitsap County"},
        "98367": {"Kitsap County": "Kitsap County"},
        "98368": {"Jefferson County": "Jefferson County"},
        "98370": {"Kitsap County": "Kitsap County"},
        "98371": {"Pierce County": "Pierce County"},
        "98372": {"Pierce County": "Pierce County"},
        "98373": {"Pierce County": "Pierce County"},
        "98374": {"Pierce County": "Pierce County"},
        "98375": {"Pierce County": "Pierce County"},
        "98376": {"Jefferson County": "Jefferson County"},
        "98377": {"Lewis County": "Lewis County"},
        "98380": {
            "Kitsap County": "Kitsap County",
            "Mason County": "Mason County",
        },
        "98381": {"Clallam County": "Clallam County"},
        "98382": {
            "Clallam County": "Clallam County",
            "Jefferson County": "Jefferson County",
        },
        "98383": {"Kitsap County": "Kitsap County"},
        "98384": {"Kitsap County": "Kitsap County"},
        "98385": {"Pierce County": "Pierce County"},
        "98386": {"Kitsap County": "Kitsap County"},
        "98387": {"Pierce County": "Pierce County"},
        "98388": {"Pierce County": "Pierce County"},
        "98390": {"Pierce County": "Pierce County"},
        "98391": {"Pierce County": "Pierce County"},
        "98392": {"Kitsap County": "Kitsap County"},
        "98393": {"Kitsap County": "Kitsap County"},
        "98394": {"Pierce County": "Pierce County"},
        "98395": {"Pierce County": "Pierce County"},
        "98396": {"Pierce County": "Pierce County"},
        "98397": {"Pierce County": "Pierce County"},
        "98398": {"Pierce County": "Pierce County"},
        "98401": {"Pierce County": "Pierce County"},
        "98402": {"Pierce County": "Pierce County"},
        "98403": {"Pierce County": "Pierce County"},
        "98404": {"Pierce County": "Pierce County"},
        "98405": {"Pierce County": "Pierce County"},
        "98406": {"Pierce County": "Pierce County"},
        "98407": {"Pierce County": "Pierce County"},
        "98408": {"Pierce County": "Pierce County"},
        "98409": {"Pierce County": "Pierce County"},
        "98411": {"Pierce County": "Pierce County"},
        "98413": {"Pierce County": "Pierce County"},
        "98416": {"Pierce County": "Pierce County"},
        "98417": {"Pierce County": "Pierce County"},
        "98418": {"Pierce County": "Pierce County"},
        "98419": {"Pierce County": "Pierce County"},
        "98421": {"Pierce County": "Pierce County"},
        "98422": {
            "King County": "King County",
            "Pierce County": "Pierce County",
        },
        "98424": {"Pierce County": "Pierce County"},
        "98430": {"Pierce County": "Pierce County"},
        "98431": {"Pierce County": "Pierce County"},
        "98433": {"Pierce County": "Pierce County"},
        "98438": {"Pierce County": "Pierce County"},
        "98439": {"Pierce County": "Pierce County"},
        "98443": {"Pierce County": "Pierce County"},
        "98444": {"Pierce County": "Pierce County"},
        "98445": {"Pierce County": "Pierce County"},
        "98446": {"Pierce County": "Pierce County"},
        "98447": {"Pierce County": "Pierce County"},
        "98448": {"Pierce County": "Pierce County"},
        "98464": {"Pierce County": "Pierce County"},
        "98465": {"Pierce County": "Pierce County"},
        "98466": {"Pierce County": "Pierce County"},
        "98467": {"Pierce County": "Pierce County"},
        "98490": {"Pierce County": "Pierce County"},
        "98493": {"Pierce County": "Pierce County"},
        "98496": {"Pierce County": "Pierce County"},
        "98498": {"Pierce County": "Pierce County"},
        "98499": {"Pierce County": "Pierce County"},
        "98501": {"Thurston County": "Thurston County"},
        "98502": {
            "Mason County": "Mason County",
            "Thurston County": "Thurston County",
        },
        "98503": {"Thurston County": "Thurston County"},
        "98505": {"Thurston County": "Thurston County"},
        "98506": {"Thurston County": "Thurston County"},
        "98507": {"Thurston County": "Thurston County"},
        "98508": {"Thurston County": "Thurston County"},
        "98509": {"Thurston County": "Thurston County"},
        "98511": {"Thurston County": "Thurston County"},
        "98512": {"Thurston County": "Thurston County"},
        "98513": {"Thurston County": "Thurston County"},
        "98516": {"Thurston County": "Thurston County"},
        "98520": {"Grays Harbor County": "Grays Harbor County"},
        "98522": {"Lewis County": "Lewis County"},
        "98524": {"Mason County": "Mason County"},
        "98526": {"Grays Harbor County": "Grays Harbor County"},
        "98527": {"Pacific County": "Pacific County"},
        "98528": {
            "Kitsap County": "Kitsap County",
            "Mason County": "Mason County",
            "Pierce County": "Pierce County",
        },
        "98530": {"Thurston County": "Thurston County"},
        "98531": {
            "Lewis County": "Lewis County",
            "Thurston County": "Thurston County",
        },
        "98532": {"Lewis County": "Lewis County"},
        "98533": {"Lewis County": "Lewis County"},
        "98535": {"Grays Harbor County": "Grays Harbor County"},
        "98536": {"Grays Harbor County": "Grays Harbor County"},
        "98537": {
            "Grays Harbor County": "Grays Harbor County",
            "Pacific County": "Pacific County",
        },
        "98538": {"Lewis County": "Lewis County"},
        "98539": {"Lewis County": "Lewis County"},
        "98540": {"Thurston County": "Thurston County"},
        "98541": {
            "Grays Harbor County": "Grays Harbor County",
            "Mason County": "Mason County",
        },
        "98542": {"Lewis County": "Lewis County"},
        "98544": {"Lewis County": "Lewis County"},
        "98546": {"Mason County": "Mason County"},
        "98547": {
            "Grays Harbor County": "Grays Harbor County",
            "Pacific County": "Pacific County",
        },
        "98548": {"Mason County": "Mason County"},
        "98550": {"Grays Harbor County": "Grays Harbor County"},
        "98552": {"Grays Harbor County": "Grays Harbor County"},
        "98554": {"Pacific County": "Pacific County"},
        "98555": {"Mason County": "Mason County"},
        "98556": {"Thurston County": "Thurston County"},
        "98557": {
            "Grays Harbor County": "Grays Harbor County",
            "Mason County": "Mason County",
        },
        "98558": {"Pierce County": "Pierce County"},
        "98559": {"Grays Harbor County": "Grays Harbor County"},
        "98560": {"Mason County": "Mason County"},
        "98561": {"Pacific County": "Pacific County"},
        "98562": {"Grays Harbor County": "Grays Harbor County"},
        "98563": {
            "Grays Harbor County": "Grays Harbor County",
            "Mason County": "Mason County",
        },
        "98564": {"Lewis County": "Lewis County"},
        "98565": {"Lewis County": "Lewis County"},
        "98566": {"Grays Harbor County": "Grays Harbor County"},
        "98568": {
            "Grays Harbor County": "Grays Harbor County",
            "Lewis County": "Lewis County",
            "Thurston County": "Thurston County",
        },
        "98569": {"Grays Harbor County": "Grays Harbor County"},
        "98570": {"Lewis County": "Lewis County"},
        "98571": {"Grays Harbor County": "Grays Harbor County"},
        "98572": {
            "Lewis County": "Lewis County",
            "Pacific County": "Pacific County",
        },
        "98575": {"Grays Harbor County": "Grays Harbor County"},
        "98576": {"Thurston County": "Thurston County"},
        "98577": {"Pacific County": "Pacific County"},
        "98579": {
            "Grays Harbor County": "Grays Harbor County",
            "Lewis County": "Lewis County",
            "Thurston County": "Thurston County",
        },
        "98580": {"Pierce County": "Pierce County"},
        "98581": {"Cowlitz County": "Cowlitz County"},
        "98582": {"Lewis County": "Lewis County"},
        "98583": {"Grays Harbor County": "Grays Harbor County"},
        "98584": {"Mason County": "Mason County"},
        "98585": {"Lewis County": "Lewis County"},
        "98586": {"Pacific County": "Pacific County"},
        "98587": {"Grays Harbor County": "Grays Harbor County"},
        "98588": {"Mason County": "Mason County"},
        "98589": {"Thurston County": "Thurston County"},
        "98590": {"Pacific County": "Pacific County"},
        "98591": {"Lewis County": "Lewis County"},
        "98592": {"Mason County": "Mason County"},
        "98593": {"Lewis County": "Lewis County"},
        "98595": {"Grays Harbor County": "Grays Harbor County"},
        "98596": {"Lewis County": "Lewis County"},
        "98597": {"Thurston County": "Thurston County"},
        "98601": {
            "Clark County": "Clark County",
            "Cowlitz County": "Cowlitz County",
        },
        "98602": {"Klickitat County": "Klickitat County"},
        "98603": {"Cowlitz County": "Cowlitz County"},
        "98604": {"Clark County": "Clark County"},
        "98605": {
            "Klickitat County": "Klickitat County",
            "Skamania County": "Skamania County",
        },
        "98606": {"Clark County": "Clark County"},
        "98607": {"Clark County": "Clark County"},
        "98609": {"Cowlitz County": "Cowlitz County"},
        "98610": {"Skamania County": "Skamania County"},
        "98611": {"Cowlitz County": "Cowlitz County"},
        "98612": {"Wahkiakum County": "Wahkiakum County"},
        "98613": {"Klickitat County": "Klickitat County"},
        "98614": {"Pacific County": "Pacific County"},
        "98616": {
            "Cowlitz County": "Cowlitz County",
            "Skamania County": "Skamania County",
        },
        "98617": {"Klickitat County": "Klickitat County"},
        "98619": {"Klickitat County": "Klickitat County"},
        "98620": {"Klickitat County": "Klickitat County"},
        "98621": {"Wahkiakum County": "Wahkiakum County"},
        "98622": {"Clark County": "Clark County"},
        "98623": {"Klickitat County": "Klickitat County"},
        "98624": {"Pacific County": "Pacific County"},
        "98625": {"Cowlitz County": "Cowlitz County"},
        "98626": {"Cowlitz County": "Cowlitz County"},
        "98628": {"Klickitat County": "Klickitat County"},
        "98629": {"Clark County": "Clark County"},
        "98631": {"Pacific County": "Pacific County"},
        "98632": {
            "Cowlitz County": "Cowlitz County",
            "Wahkiakum County": "Wahkiakum County",
        },
        "98635": {"Klickitat County": "Klickitat County"},
        "98637": {"Pacific County": "Pacific County"},
        "98638": {
            "Pacific County": "Pacific County",
            "Wahkiakum County": "Wahkiakum County",
        },
        "98639": {"Skamania County": "Skamania County"},
        "98640": {"Pacific County": "Pacific County"},
        "98641": {"Pacific County": "Pacific County"},
        "98642": {"Clark County": "Clark County"},
        "98643": {"Wahkiakum County": "Wahkiakum County"},
        "98644": {"Pacific County": "Pacific County"},
        "98645": {"Cowlitz County": "Cowlitz County"},
        "98647": {"Wahkiakum County": "Wahkiakum County"},
        "98648": {"Skamania County": "Skamania County"},
        "98649": {"Cowlitz County": "Cowlitz County"},
        "98650": {"Klickitat County": "Klickitat County"},
        "98651": {
            "Klickitat County": "Klickitat County",
            "Skamania County": "Skamania County",
        },
        "98660": {"Clark County": "Clark County"},
        "98661": {"Clark County": "Clark County"},
        "98662": {"Clark County": "Clark County"},
        "98663": {"Clark County": "Clark County"},
        "98664": {"Clark County": "Clark County"},
        "98665": {"Clark County": "Clark County"},
        "98666": {"Clark County": "Clark County"},
        "98668": {"Clark County": "Clark County"},
        "98670": {"Klickitat County": "Klickitat County"},
        "98671": {
            "Clark County": "Clark County",
            "Skamania County": "Skamania County",
        },
        "98672": {
            "Klickitat County": "Klickitat County",
            "Skamania County": "Skamania County",
        },
        "98673": {"Klickitat County": "Klickitat County"},
        "98674": {
            "Clark County": "Clark County",
            "Cowlitz County": "Cowlitz County",
        },
        "98675": {"Clark County": "Clark County"},
        "98682": {"Clark County": "Clark County"},
        "98683": {"Clark County": "Clark County"},
        "98684": {"Clark County": "Clark County"},
        "98685": {"Clark County": "Clark County"},
        "98686": {"Clark County": "Clark County"},
        "98687": {"Clark County": "Clark County"},
        "98801": {"Chelan County": "Chelan County"},
        "98802": {"Douglas County": "Douglas County"},
        "98807": {"Chelan County": "Chelan County"},
        "98811": {"Chelan County": "Chelan County"},
        "98812": {
            "Douglas County": "Douglas County",
            "Kittitas County": "Kittitas County",
            "Okanogan County": "Okanogan County",
        },
        "98813": {
            "Douglas County": "Douglas County",
            "Okanogan County": "Okanogan County",
        },
        "98814": {"Okanogan County": "Okanogan County"},
        "98815": {"Chelan County": "Chelan County"},
        "98816": {
            "Chelan County": "Chelan County",
            "Okanogan County": "Okanogan County",
        },
        "98817": {"Chelan County": "Chelan County"},
        "98819": {"Okanogan County": "Okanogan County"},
        "98821": {"Chelan County": "Chelan County"},
        "98822": {"Chelan County": "Chelan County"},
        "98823": {
            "Douglas County": "Douglas County",
            "Grant County": "Grant County",
        },
        "98824": {"Grant County": "Grant County"},
        "98826": {"Chelan County": "Chelan County"},
        "98827": {"Okanogan County": "Okanogan County"},
        "98828": {
            "Chelan County": "Chelan County",
            "Kittitas County": "Kittitas County",
        },
        "98829": {"Okanogan County": "Okanogan County"},
        "98830": {"Douglas County": "Douglas County"},
        "98831": {"Chelan County": "Chelan County"},
        "98832": {
            "Adams County": "Adams County",
            "Grant County": "Grant County",
            "Lincoln County": "Lincoln County",
        },
        "98833": {"Okanogan County": "Okanogan County"},
        "98834": {"Okanogan County": "Okanogan County"},
        "98836": {"Chelan County": "Chelan County"},
        "98837": {"Grant County": "Grant County"},
        "98840": {"Okanogan County": "Okanogan County"},
        "98841": {"Okanogan County": "Okanogan County"},
        "98843": {"Douglas County": "Douglas County"},
        "98844": {"Okanogan County": "Okanogan County"},
        "98845": {"Douglas County": "Douglas County"},
        "98846": {
            "Chelan County": "Chelan County",
            "Okanogan County": "Okanogan County",
        },
        "98847": {"Chelan County": "Chelan County"},
        "98848": {
            "Douglas County": "Douglas County",
            "Grant County": "Grant County",
        },
        "98849": {"Okanogan County": "Okanogan County"},
        "98850": {"Douglas County": "Douglas County"},
        "98851": {"Grant County": "Grant County"},
        "98852": {"Chelan County": "Chelan County"},
        "98853": {"Grant County": "Grant County"},
        "98855": {"Okanogan County": "Okanogan County"},
        "98856": {"Okanogan County": "Okanogan County"},
        "98857": {
            "Adams County": "Adams County",
            "Grant County": "Grant County",
        },
        "98858": {
            "Douglas County": "Douglas County",
            "Grant County": "Grant County",
        },
        "98859": {"Okanogan County": "Okanogan County"},
        "98860": {"Grant County": "Grant County"},
        "98862": {"Okanogan County": "Okanogan County"},
        "98901": {
            "Kittitas County": "Kittitas County",
            "Yakima County": "Yakima County",
        },
        "98902": {"Yakima County": "Yakima County"},
        "98903": {"Yakima County": "Yakima County"},
        "98907": {"Yakima County": "Yakima County"},
        "98908": {"Yakima County": "Yakima County"},
        "98909": {"Yakima County": "Yakima County"},
        "98920": {"Yakima County": "Yakima County"},
        "98921": {"Yakima County": "Yakima County"},
        "98922": {"Kittitas County": "Kittitas County"},
        "98923": {"Yakima County": "Yakima County"},
        "98925": {"Kittitas County": "Kittitas County"},
        "98926": {"Kittitas County": "Kittitas County"},
        "98930": {
            "Benton County": "Benton County",
            "Yakima County": "Yakima County",
        },
        "98932": {"Yakima County": "Yakima County"},
        "98933": {"Yakima County": "Yakima County"},
        "98934": {"Kittitas County": "Kittitas County"},
        "98935": {
            "Klickitat County": "Klickitat County",
            "Yakima County": "Yakima County",
        },
        "98936": {"Yakima County": "Yakima County"},
        "98937": {
            "Pierce County": "Pierce County",
            "Yakima County": "Yakima County",
        },
        "98938": {"Yakima County": "Yakima County"},
        "98939": {"Yakima County": "Yakima County"},
        "98940": {"Kittitas County": "Kittitas County"},
        "98941": {"Kittitas County": "Kittitas County"},
        "98942": {"Yakima County": "Yakima County"},
        "98943": {"Kittitas County": "Kittitas County"},
        "98944": {
            "Benton County": "Benton County",
            "Yakima County": "Yakima County",
        },
        "98946": {"Kittitas County": "Kittitas County"},
        "98947": {"Yakima County": "Yakima County"},
        "98948": {"Yakima County": "Yakima County"},
        "98950": {"Kittitas County": "Kittitas County"},
        "98951": {"Yakima County": "Yakima County"},
        "98952": {"Yakima County": "Yakima County"},
        "98953": {"Yakima County": "Yakima County"},
        "99001": {"Spokane County": "Spokane County"},
        "99003": {"Spokane County": "Spokane County"},
        "99004": {
            "Lincoln County": "Lincoln County",
            "Spokane County": "Spokane County",
            "Whitman County": "Whitman County",
        },
        "99005": {"Spokane County": "Spokane County"},
        "99006": {
            "Pend Oreille County": "Pend Oreille County",
            "Spokane County": "Spokane County",
            "Stevens County": "Stevens County",
        },
        "99008": {
            "Lincoln County": "Lincoln County",
            "Spokane County": "Spokane County",
        },
        "99009": {
            "Pend Oreille County": "Pend Oreille County",
            "Spokane County": "Spokane County",
        },
        "99011": {"Spokane County": "Spokane County"},
        "99012": {"Spokane County": "Spokane County"},
        "99013": {
            "Lincoln County": "Lincoln County",
            "Spokane County": "Spokane County",
            "Stevens County": "Stevens County",
        },
        "99014": {"Spokane County": "Spokane County"},
        "99016": {"Spokane County": "Spokane County"},
        "99017": {
            "Adams County": "Adams County",
            "Whitman County": "Whitman County",
        },
        "99018": {"Spokane County": "Spokane County"},
        "99019": {"Spokane County": "Spokane County"},
        "99020": {"Spokane County": "Spokane County"},
        "99021": {"Spokane County": "Spokane County"},
        "99022": {
            "Lincoln County": "Lincoln County",
            "Spokane County": "Spokane County",
        },
        "99023": {"Spokane County": "Spokane County"},
        "99025": {"Spokane County": "Spokane County"},
        "99026": {
            "Spokane County": "Spokane County",
            "Stevens County": "Stevens County",
        },
        "99027": {"Spokane County": "Spokane County"},
        "99029": {
            "Lincoln County": "Lincoln County",
            "Spokane County": "Spokane County",
        },
        "99030": {"Spokane County": "Spokane County"},
        "99031": {"Spokane County": "Spokane County"},
        "99032": {
            "Adams County": "Adams County",
            "Lincoln County": "Lincoln County",
            "Spokane County": "Spokane County",
        },
        "99033": {
            "Spokane County": "Spokane County",
            "Whitman County": "Whitman County",
        },
        "99034": {"Stevens County": "Stevens County"},
        "99036": {"Spokane County": "Spokane County"},
        "99037": {"Spokane County": "Spokane County"},
        "99039": {"Spokane County": "Spokane County"},
        "99040": {"Stevens County": "Stevens County"},
        "99101": {"Stevens County": "Stevens County"},
        "99102": {"Whitman County": "Whitman County"},
        "99103": {
            "Grant County": "Grant County",
            "Lincoln County": "Lincoln County",
        },
        "99104": {"Whitman County": "Whitman County"},
        "99105": {"Adams County": "Adams County"},
        "99109": {"Stevens County": "Stevens County"},
        "99110": {
            "Spokane County": "Spokane County",
            "Stevens County": "Stevens County",
        },
        "99111": {"Whitman County": "Whitman County"},
        "99113": {"Whitman County": "Whitman County"},
        "99114": {"Stevens County": "Stevens County"},
        "99115": {
            "Douglas County": "Douglas County",
            "Grant County": "Grant County",
        },
        "99116": {
            "Douglas County": "Douglas County",
            "Grant County": "Grant County",
            "Okanogan County": "Okanogan County",
        },
        "99117": {"Lincoln County": "Lincoln County"},
        "99118": {"Ferry County": "Ferry County"},
        "99119": {"Pend Oreille County": "Pend Oreille County"},
        "99121": {"Ferry County": "Ferry County"},
        "99122": {
            "Lincoln County": "Lincoln County",
            "Stevens County": "Stevens County",
        },
        "99123": {"Grant County": "Grant County"},
        "99124": {"Okanogan County": "Okanogan County"},
        "99125": {
            "Adams County": "Adams County",
            "Whitman County": "Whitman County",
        },
        "99126": {"Stevens County": "Stevens County"},
        "99128": {"Whitman County": "Whitman County"},
        "99129": {"Stevens County": "Stevens County"},
        "99130": {"Whitman County": "Whitman County"},
        "99131": {"Stevens County": "Stevens County"},
        "99133": {
            "Douglas County": "Douglas County",
            "Grant County": "Grant County",
            "Lincoln County": "Lincoln County",
        },
        "99134": {"Lincoln County": "Lincoln County"},
        "99135": {"Grant County": "Grant County"},
        "99136": {"Whitman County": "Whitman County"},
        "99137": {"Stevens County": "Stevens County"},
        "99138": {"Ferry County": "Ferry County"},
        "99139": {"Pend Oreille County": "Pend Oreille County"},
        "99140": {"Ferry County": "Ferry County"},
        "99141": {
            "Ferry County": "Ferry County",
            "Stevens County": "Stevens County",
        },
        "99143": {
            "Columbia County": "Columbia County",
            "Whitman County": "Whitman County",
        },
        "99144": {"Lincoln County": "Lincoln County"},
        "99146": {"Ferry County": "Ferry County"},
        "99147": {"Lincoln County": "Lincoln County"},
        "99148": {"Stevens County": "Stevens County"},
        "99149": {"Whitman County": "Whitman County"},
        "99150": {"Ferry County": "Ferry County"},
        "99151": {"Stevens County": "Stevens County"},
        "99152": {"Pend Oreille County": "Pend Oreille County"},
        "99153": {"Pend Oreille County": "Pend Oreille County"},
        "99154": {"Lincoln County": "Lincoln County"},
        "99155": {"Okanogan County": "Okanogan County"},
        "99156": {
            "Pend Oreille County": "Pend Oreille County",
            "Spokane County": "Spokane County",
        },
        "99157": {"Stevens County": "Stevens County"},
        "99158": {"Whitman County": "Whitman County"},
        "99159": {
            "Adams County": "Adams County",
            "Lincoln County": "Lincoln County",
        },
        "99160": {
            "Ferry County": "Ferry County",
            "Stevens County": "Stevens County",
        },
        "99161": {"Whitman County": "Whitman County"},
        "99163": {"Whitman County": "Whitman County"},
        "99164": {"Whitman County": "Whitman County"},
        "99166": {
            "Ferry County": "Ferry County",
            "Okanogan County": "Okanogan County",
        },
        "99167": {"Stevens County": "Stevens County"},
        "99169": {
            "Adams County": "Adams County",
            "Lincoln County": "Lincoln County",
        },
        "99170": {
            "Spokane County": "Spokane County",
            "Whitman County": "Whitman County",
        },
        "99171": {"Whitman County": "Whitman County"},
        "99173": {"Stevens County": "Stevens County"},
        "99174": {"Whitman County": "Whitman County"},
        "99176": {"Whitman County": "Whitman County"},
        "99179": {"Whitman County": "Whitman County"},
        "99180": {"Pend Oreille County": "Pend Oreille County"},
        "99181": {"Stevens County": "Stevens County"},
        "99185": {"Lincoln County": "Lincoln County"},
        "99201": {"Spokane County": "Spokane County"},
        "99202": {"Spokane County": "Spokane County"},
        "99203": {"Spokane County": "Spokane County"},
        "99204": {"Spokane County": "Spokane County"},
        "99205": {"Spokane County": "Spokane County"},
        "99206": {"Spokane County": "Spokane County"},
        "99207": {"Spokane County": "Spokane County"},
        "99208": {"Spokane County": "Spokane County"},
        "99209": {"Spokane County": "Spokane County"},
        "99210": {"Spokane County": "Spokane County"},
        "99211": {"Spokane County": "Spokane County"},
        "99212": {"Spokane County": "Spokane County"},
        "99213": {"Spokane County": "Spokane County"},
        "99214": {"Spokane County": "Spokane County"},
        "99216": {"Spokane County": "Spokane County"},
        "99217": {"Spokane County": "Spokane County"},
        "99218": {"Spokane County": "Spokane County"},
        "99219": {"Spokane County": "Spokane County"},
        "99220": {"Spokane County": "Spokane County"},
        "99223": {"Spokane County": "Spokane County"},
        "99224": {"Spokane County": "Spokane County"},
        "99228": {"Spokane County": "Spokane County"},
        "99251": {"Spokane County": "Spokane County"},
        "99252": {"Spokane County": "Spokane County"},
        "99256": {"Spokane County": "Spokane County"},
        "99258": {"Spokane County": "Spokane County"},
        "99260": {"Spokane County": "Spokane County"},
        "99301": {"Franklin County": "Franklin County"},
        "99302": {"Franklin County": "Franklin County"},
        "99320": {"Benton County": "Benton County"},
        "99321": {"Grant County": "Grant County"},
        "99322": {
            "Klickitat County": "Klickitat County",
            "Yakima County": "Yakima County",
        },
        "99323": {"Walla Walla County": "Walla Walla County"},
        "99324": {"Walla Walla County": "Walla Walla County"},
        "99326": {
            "Adams County": "Adams County",
            "Franklin County": "Franklin County",
        },
        "99328": {
            "Columbia County": "Columbia County",
            "Garfield County": "Garfield County",
            "Walla Walla County": "Walla Walla County",
        },
        "99329": {"Walla Walla County": "Walla Walla County"},
        "99330": {"Franklin County": "Franklin County"},
        "99333": {"Whitman County": "Whitman County"},
        "99335": {"Franklin County": "Franklin County"},
        "99336": {"Benton County": "Benton County"},
        "99337": {"Benton County": "Benton County"},
        "99338": {"Benton County": "Benton County"},
        "99341": {"Adams County": "Adams County"},
        "99343": {"Franklin County": "Franklin County"},
        "99344": {
            "Adams County": "Adams County",
            "Franklin County": "Franklin County",
            "Grant County": "Grant County",
        },
        "99345": {"Benton County": "Benton County"},
        "99346": {"Benton County": "Benton County"},
        "99347": {
            "Asotin County": "Asotin County",
            "Columbia County": "Columbia County",
            "Garfield County": "Garfield County",
        },
        "99348": {
            "Columbia County": "Columbia County",
            "Walla Walla County": "Walla Walla County",
        },
        "99349": {"Grant County": "Grant County"},
        "99350": {
            "Benton County": "Benton County",
            "Klickitat County": "Klickitat County",
            "Yakima County": "Yakima County",
        },
        "99352": {"Benton County": "Benton County"},
        "99353": {"Benton County": "Benton County"},
        "99354": {"Benton County": "Benton County"},
        "99356": {"Klickitat County": "Klickitat County"},
        "99357": {"Grant County": "Grant County"},
        "99359": {"Columbia County": "Columbia County"},
        "99360": {"Walla Walla County": "Walla Walla County"},
        "99361": {
            "Columbia County": "Columbia County",
            "Walla Walla County": "Walla Walla County",
        },
        "99362": {"Walla Walla County": "Walla Walla County"},
        "99363": {"Walla Walla County": "Walla Walla County"},
        "99371": {
            "Adams County": "Adams County",
            "Franklin County": "Franklin County",
        },
        "99401": {"Asotin County": "Asotin County"},
        "99402": {"Asotin County": "Asotin County"},
        "99403": {
            "Asotin County": "Asotin County",
            "Garfield County": "Garfield County",
            "Whitman County": "Whitman County",
        },
    }

    # ==========================================================================================
    # CATEGORY BENEFITS
    # ==========================================================================================

    category_benefits = {
        "foodAndNutrition": {
            "benefits": {
                "snap": {
                    "name": {
                        "_label": "foodAndNutritionBenefits.snap",
                        "_default_message": "Supplemental Nutrition Assistance Program (SNAP): ",
                    },
                    "description": {
                        "_label": "foodAndNutritionBenefits.snap_desc",
                        "_default_message": "Food assistance",
                    },
                },
                "wic": {
                    "name": {
                        "_label": "foodAndNutritionBenefits.wic",
                        "_default_message": "Special Supplemental Nutrition Program for Women, Infants, and Children (WIC): ",
                    },
                    "description": {
                        "_label": "foodAndNutritionBenefits.wic_desc",
                        "_default_message": "Food and breastfeeding assistance",
                    },
                },
                "nslp": {
                    "name": {
                        "_label": "foodAndNutritionBenefits.nslp",
                        "_default_message": "National School Lunch Program: ",
                    },
                    "description": {
                        "_label": "foodAndNutritionBenefits.nslp_desc",
                        "_default_message": "Free school meals",
                    },
                },
                "csfp": {
                    "name": {
                        "_label": "foodAndNutritionBenefits.csfp",
                        "_default_message": "Commodity Supplemental Food Program (CSFP): ",
                    },
                    "description": {
                        "_label": "foodAndNutritionBenefits.csfp_desc",
                        "_default_message": "Food support for people 60 years of age or older",
                    },
                },
            },
            "category_name": {
                "_label": "foodAndNutrition",
                "_default_message": "Food and Nutrition",
            },
        },
        "housingAndUtilities": {
            "benefits": {
                "lifeline": {
                    "name": {
                        "_label": "housingAndUtilities.lifeline",
                        "_default_message": "Lifeline: ",
                    },
                    "description": {
                        "_label": "housingAndUtilities.lifeline_desc",
                        "_default_message": "Phone or internet discount",
                    },
                },
                "acp": {
                    "name": {
                        "_label": "housingAndUtilities.acp",
                        "_default_message": "Affordable Connectivity Program (ACP): ",
                    },
                    "description": {
                        "_label": "housingAndUtilities.acp_desc",
                        "_default_message": "Internet discount",
                    },
                },
            },
            "category_name": {
                "_label": "housing",
                "_default_message": "Housing and Utilities",
            },
        },
        "cash": {
            "benefits": {
                "ssdi": {
                    "name": {
                        "_label": "cashAssistanceBenefits.ssdi",
                        "_default_message": "Social Security Disability Insurance (SSDI): ",
                    },
                    "description": {
                        "_label": "cashAssistanceBenefits.ssdi_desc",
                        "_default_message": "Social security benefit for people with disabilities",
                    },
                },
                "ssi": {
                    "name": {
                        "_label": "cashAssistanceBenefits.ssi",
                        "_default_message": "Supplemental Security Income (SSI): ",
                    },
                    "description": {
                        "_label": "cashAssistanceBenefits.ssi_desc",
                        "_default_message": "Federal cash assistance for individuals who are disabled, blind, or 65 years of age or older",
                    },
                },
                "tanf": {
                    "name": {
                        "_label": "cashAssistanceBenefits.tanf",
                        "_default_message": "Temporary Assistance for Needy Families (TANF): ",
                    },
                    "description": {
                        "_label": "cashAssistanceBenefits.tanf_desc",
                        "_default_message": "Cash assistance for families with children",
                    },
                },
            },
            "category_name": {
                "_label": "cashAssistance",
                "_default_message": "Cash Assistance",
            },
        },
        "healthCare": {
            "benefits": {
                "medicaid": {
                    "name": {
                        "_label": "healthCareBenefits.medicaid.wa",
                        "_default_message": "Apple Health (Medicaid): ",
                    },
                    "description": {
                        "_label": "healthCareBenefits.medicaid_desc",
                        "_default_message": "Free or low-cost health coverage",
                    },
                },
                "chp": {
                    "name": {
                        "_label": "healthCareBenefits.chp.wa",
                        "_default_message": "Apple Health for Kids: ",
                    },
                    "description": {
                        "_label": "healthCareBenefits.chp_desc",
                        "_default_message": "Free or low-cost health coverage for children",
                    },
                },
                "medicare_savings": {
                    "name": {
                        "_label": "healthCareBenefits.medicare_savings",
                        "_default_message": "Medicare Savings Program: ",
                    },
                    "description": {
                        "_label": "healthCareBenefits.medicare_savings_desc",
                        "_default_message": "Help paying Medicare premiums and costs",
                    },
                },
            },
            "category_name": {
                "_label": "healthCare",
                "_default_message": "Health Care",
            },
        },
    }

    # ==========================================================================================
    # REFERRER DATA
    # ==========================================================================================

    # Inherit base referrer_data (favicon, noResultMessage, uiOptions, etc.) and
    # override only the keys WA customizes.
    referrer_data = {
        **ConfigurationData.referrer_data,
        "theme": {"default": "default"},
        "logoSource": {"default": "MFB_Logo"},
        "logoAlt": {
            "default": {
                "id": "referrerHook.logoAlts.default",
                "defaultMessage": "MyFriendBen home page button",
            },
        },
        "logoFooterSource": {"default": "MFB_Logo"},
        "logoFooterAlt": {
            "default": {"id": "footer.logo.alt", "defaultMessage": "MFB Logo"},
        },
        "logoClass": {"default": "logo"},
        "shareLink": {
            "default": "https://screener.myfriendben.org/wa/step-1",
        },
        "stepDirectory": {
            "default": [
                "zipcode",
                # the hhSize and hhData have to be consecutive
                "householdSize",
                "householdData",
                "hasExpenses",
                "householdAssets",
                "hasBenefits",
                "acuteHHConditions",
                "referralSource",
                "signUpInfo",
            ],
        },
        "defaultLanguage": {"default": "en-us"},
        "stateName": {"default": "Washington"},
    }
