# Generated by Django 4.0.5 on 2022-06-14 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Screen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_date", models.DateTimeField(auto_now=True)),
                ("agree_to_tos", models.BooleanField()),
                ("applicant_age", models.IntegerField()),
                ("zipcode", models.CharField(max_length=5)),
                ("student", models.BooleanField()),
                ("student_full_time", models.BooleanField()),
                ("pregnant", models.BooleanField()),
                ("unemployed", models.BooleanField()),
                ("worked_in_last_18_mos", models.BooleanField()),
                ("visually_impaired", models.BooleanField()),
                ("disabled", models.BooleanField()),
                ("veteran", models.BooleanField()),
                ("medicaid", models.BooleanField()),
                ("disability_medicaid", models.BooleanField()),
                ("has_income", models.BooleanField()),
                ("has_expenses", models.BooleanField()),
                ("household_size", models.IntegerField()),
                (
                    "household_assets",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="incomeStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=30)),
                ("label", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("frequency", models.CharField(max_length=30)),
                (
                    "screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="screener.screen",
                    ),
                ),
            ],
        ),
    ]
