# Generated by Django 4.0.5 on 2022-06-16 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0002_screen_housing_situation_expense"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incomestream",
            old_name="type",
            new_name="name",
        ),
    ]
