# Generated by Django 4.0.5 on 2022-06-21 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0004_remove_incomestream_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomestream",
            name="screen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incomestreams",
                to="screener.screen",
            ),
        ),
    ]
