# Generated by Django 4.0.5 on 2022-07-14 20:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0006_rename_name_expense_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="screen",
            old_name="applicant_age",
            new_name="age",
        ),
    ]
