# Generated by Django 4.0.5 on 2022-07-14 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0008_householdmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='householdmember',
            name='zipcode',
        ),
    ]
