# Generated by Django 4.0.5 on 2022-07-14 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0010_remove_screen_age_remove_screen_disability_medicaid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="household_member",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="screener.householdmember",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="incomestream",
            name="household_member",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incomestreams",
                to="screener.householdmember",
            ),
            preserve_default=False,
        ),
    ]
