# Generated by Django 4.0.5 on 2022-08-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0019_screen_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='is_test',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
