# Generated by Django 4.0.5 on 2022-08-18 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0021_messages"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Messages",
            new_name="Message",
        ),
    ]
