# Generated by Django 4.0.5 on 2022-09-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0025_screen_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='filed_taxes',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
