# Generated by Django 4.0.5 on 2022-09-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0028_screen_last_tax_filing_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='housing_situation',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
