# Generated by Django 4.0.5 on 2022-09-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0031_alter_householdmember_disability_medicaid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='uid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
