# Generated by Django 4.0.5 on 2022-09-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0033_screen_referral_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screen",
            name="household_assets",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=10, null=True
            ),
        ),
    ]
