# Generated by Django 4.0.5 on 2022-10-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0035_screen_county"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="request_language_code",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
