# Generated by Django 4.0.5 on 2022-12-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0038_alter_programeligibilitysnapshot_estimated_application_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='has_ssi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
