# Generated by Django 4.0.5 on 2023-02-13 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0044_screen_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
