# Generated by Django 4.0.5 on 2023-02-17 17:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0045_screen_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screen",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
