# Generated by Django 4.0.5 on 2023-03-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0047_incomestream_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='needs_family_planning_help',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
