# Generated by Django 4.0.5 on 2023-03-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0048_screen_needs_family_planning_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitysnapshot',
            name='batch',
            field=models.BooleanField(default=False),
        ),
    ]
