# Generated by Django 4.0.5 on 2023-03-22 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0049_eligibilitysnapshot_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eligibilitysnapshot',
            old_name='batch',
            new_name='is_batch',
        ),
    ]
