# Generated by Django 4.0.5 on 2023-03-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0050_rename_batch_eligibilitysnapshot_is_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="programeligibilitysnapshot",
            name="new",
            field=models.BooleanField(default=False),
        ),
    ]
