# Generated by Django 4.0.5 on 2023-04-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0053_alter_householdmember_has_expenses_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="frequency",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="householdmember",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="householdmember",
            name="disabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="householdmember",
            name="has_expenses",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="householdmember",
            name="has_income",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="householdmember",
            name="pregnant",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="householdmember",
            name="relationship",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="householdmember",
            name="student",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="householdmember",
            name="student_full_time",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="householdmember",
            name="unemployed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="householdmember",
            name="veteran",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="householdmember",
            name="visually_impaired",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="householdmember",
            name="worked_in_last_18_mos",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incomestream",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incomestream",
            name="frequency",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="incomestream",
            name="hours_worked",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incomestream",
            name="type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="screen",
            name="agree_to_tos",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="screen",
            name="household_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="screen",
            name="submission_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="screen",
            name="zipcode",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
