# Generated by Django 4.0.5 on 2023-04-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0055_screen_has_andcs_screen_has_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='completed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
