# Generated by Django 4.0.5 on 2023-05-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0059_webhook_webhookfunction_webhooktranslation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='is_test_data',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
