# Generated by Django 4.0.5 on 2023-06-01 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0062_alter_screen_is_test_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webhooktranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='webhooktranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='WebHook',
        ),
        migrations.DeleteModel(
            name='WebHookFunction',
        ),
        migrations.DeleteModel(
            name='WebHookTranslation',
        ),
    ]
