# Generated by Django 4.0.5 on 2023-08-03 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0064_screen_needs_dental_care_help_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="screen",
            old_name="needs_dental_care_help",
            new_name="needs_dental_care",
        ),
    ]
