# Generated by Django 4.0.5 on 2023-08-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0065_rename_needs_dental_care_help_screen_needs_dental_care"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="is_13_or_older",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
