# Generated by Django 4.0.5 on 2023-09-05 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('screener', '0066_screen_is_13_or_older'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='household_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='screener.householdmember'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screens', to=settings.AUTH_USER_MODEL),
        ),
    ]
