# Generated by Django 4.2.6 on 2023-10-25 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0070_remove_programeligibilitysnapshot_legal_status_required"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="householdmember",
            name="insurance",
        ),
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dont_know", models.BooleanField(default=True)),
                ("none", models.BooleanField(default=False)),
                ("employer", models.BooleanField(default=False)),
                ("private", models.BooleanField(default=False)),
                ("chp", models.BooleanField(default=False)),
                ("medicaid", models.BooleanField(default=False)),
                ("medicare", models.BooleanField(default=False)),
                ("emergency_medicaid", models.BooleanField(default=False)),
                ("family_planning", models.BooleanField(default=False)),
                (
                    "household_member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance",
                        to="screener.householdmember",
                    ),
                ),
            ],
        ),
    ]
