# Generated by Django 4.2.6 on 2023-10-26 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0071_remove_householdmember_insurance_insurance"),
        ("screener", "0071_screen_has_pell_grant_screen_has_ssdi"),
    ]

    operations = []
