# Generated by Django 4.2.6 on 2023-11-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0072_merge_20231026_1216"),
    ]

    operations = [
        migrations.AddField(
            model_name="householdmember",
            name="long_term_disability",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
