# Generated by Django 4.2.6 on 2023-11-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0073_householdmember_long_term_disability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screen",
            name="household_assets",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
