# Generated by Django 4.2.6 on 2024-01-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0074_alter_screen_household_assets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screen",
            name="household_assets",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=10, null=True
            ),
        ),
    ]
