# Generated by Django 4.2.6 on 2024-01-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0075_alter_screen_household_assets"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_wap",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
