# Generated by Django 4.2.6 on 2024-01-19 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0076_screen_has_wap"),
    ]

    operations = [
        migrations.RenameField(
            model_name="screen",
            old_name="has_wap",
            new_name="has_cowap",
        ),
    ]
