# Generated by Django 4.2.6 on 2024-02-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0078_screen_has_ubp"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurance",
            name="va",
            field=models.BooleanField(default=False),
        ),
    ]
