# Generated by Django 4.2.6 on 2024-02-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0078_screen_has_ubp"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_rag",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
