# Generated by Django 4.2.6 on 2024-02-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0079_screen_has_rag"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurance",
            name="va",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="screen",
            name="has_va",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="dont_know",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="none",
            field=models.BooleanField(default=True),
        ),
    ]
