# Generated by Django 4.2.11 on 2024-04-24 20:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "screener",
            "0080_insurance_va_screen_has_va_alter_insurance_dont_know_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="cell",
        ),
        migrations.RemoveField(
            model_name="message",
            name="email",
        ),
    ]
