# Generated by Django 4.2.11 on 2024-06-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0081_remove_message_cell_remove_message_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="eligibilitysnapshot",
            name="had_error",
            field=models.BooleanField(default=False),
        ),
    ]
