# Generated by Django 4.2.11 on 2024-06-12 22:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0082_eligibilitysnapshot_had_error"),
        ("screener", "0082_screen_has_nfp"),
    ]

    operations = []
