# Generated by Django 4.2.11 on 2024-06-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0083_merge_20240612_2229"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_fatc",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
