# Generated by Django 4.2.14 on 2024-07-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0084_screen_has_fatc"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="frozen",
            field=models.BooleanField(default=False),
        ),
    ]
