# Generated by Django 4.2.15 on 2024-11-05 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0085_householdmember_birth_year_month_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhiteLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name="screen",
            name="white_label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screens",
                to="screener.whitelabel",
            ),
        ),
    ]
