# Generated by Django 4.2.15 on 2024-11-05 20:08

from django.db import migrations


def forwards_func(apps, schema_editor):
    WhiteLabel = apps.get_model("screener", "WhiteLabel")
    Screen = apps.get_model("screener", "Screen")
    ProgramCategory = apps.get_model("programs", "ProgramCategory")
    Document = apps.get_model("programs", "Document")
    Program = apps.get_model("programs", "Program")
    UrgentNeedCategory = apps.get_model("programs", "UrgentNeedCategory")
    UrgentNeed = apps.get_model("programs", "UrgentNeed")
    County = apps.get_model("programs", "County")
    Navigator = apps.get_model("programs", "Navigator")
    WarningMessage = apps.get_model("programs", "WarningMessage")
    Referrer = apps.get_model("programs", "Referrer")
    TranslationOverride = apps.get_model("programs", "TranslationOverride")
    Link = apps.get_model("integrations", "Link")
    Configuration = apps.get_model("configuration", "Configuration")

    white_label = WhiteLabel.objects.create(name="[PLACEHOLDER]", code="[PLACEHOLDER]")
    Screen.objects.all().update(white_label=white_label)
    ProgramCategory.objects.all().update(white_label=white_label)
    Document.objects.all().update(white_label=white_label)
    Program.objects.all().update(white_label=white_label)
    UrgentNeedCategory.objects.all().update(white_label=white_label)
    UrgentNeed.objects.all().update(white_label=white_label)
    County.objects.all().update(white_label=white_label)
    Navigator.objects.all().update(white_label=white_label)
    WarningMessage.objects.all().update(white_label=white_label)
    Referrer.objects.all().update(white_label=white_label)
    TranslationOverride.objects.all().update(white_label=white_label)
    Link.objects.all().update(white_label=white_label)
    Configuration.objects.all().update(white_label=white_label)


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0086_whitelabel_screen_white_label"),
        ("programs", "0095_county_white_label_document_white_label_and_more"),
        ("integrations", "0008_link_white_label"),
        ("configuration", "0004_configuration_white_label"),
    ]

    operations = [migrations.RunPython(forwards_func, migrations.RunPython.noop)]
