# Generated by Django 4.2.15 on 2024-11-05 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0087_auto_20241105_2008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screen",
            name="white_label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screens",
                to="screener.whitelabel",
            ),
        ),
    ]
