# Generated by Django 4.2.15 on 2024-12-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0088_alter_screen_white_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_sunbucks",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
