# Generated by Django 4.2.15 on 2024-12-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0089_screen_has_sunbucks"),
        ("screener", "0089_whitelabel_cms_method"),
    ]

    operations = []
