# Generated by Django 4.2.15 on 2025-01-09 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0090_merge_20241213_1726"),
    ]

    operations = [
        migrations.AddField(
            model_name="householdmember",
            name="frontend_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
