# Generated by Django 4.2.15 on 2025-01-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0090_merge_20241213_1726"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_nc_lieap",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
