# Generated by Django 4.2.15 on 2025-01-09 17:21
import uuid
from django.db import migrations


def make_frontend_ids(apps, _):
    HouseholdMember = apps.get_model("screener", "HouseholdMember")

    bulk_updates = []
    for member in HouseholdMember.objects.all():
        member.frontend_id = uuid.uuid4()
        bulk_updates.append(member)

    HouseholdMember.objects.bulk_update(bulk_updates, ["frontend_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0091_householdmember_frontend_id"),
    ]

    operations = [migrations.RunPython(make_frontend_ids, migrations.RunPython.noop)]
