# Generated by Django 4.2.15 on 2025-01-31 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0091_screen_has_nc_lieap"),
        ("screener", "0092_auto_20250109_1721"),
        ("screener", "0092_screen_has_nccip"),
    ]

    operations = []
