# Generated by Django 4.2.15 on 2025-01-28 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0092_auto_20250109_1721"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="alternate_path",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="has_section_8",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name="EnergyCaluculatorScreen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_home_owner",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "is_renter",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "electric_provider",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "gas_provider",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "electricity_is_disconnected",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "has_past_due_energy_bills",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "needs_water_heater",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "needs_hvac",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "needs_stove",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "needs_dryer",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "screen",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_calculator",
                        to="screener.screen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnergyCaluculatorMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "surviving_spouse",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "totally_disabled",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "recieves_ssi",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "household_member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_calculator",
                        to="screener.householdmember",
                    ),
                ),
            ],
        ),
    ]
