# Generated by Django 4.2.15 on 2025-01-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0093_screen_alternate_path_screen_has_section_8_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="energycaluculatormember",
            name="totally_disabled",
        ),
        migrations.AddField(
            model_name="energycaluculatormember",
            name="disabled",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
