# Generated by Django 4.2.15 on 2025-01-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0093_merge_20250131_1715"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_ncwap",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
