# Generated by Django 4.2.15 on 2025-01-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0094_remove_energycaluculatormember_totally_disabled_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="energycaluculatormember",
            old_name="recieves_ssi",
            new_name="receives_ssi",
        ),
    ]
