# Generated by Django 4.2.15 on 2025-01-29 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0095_rename_recieves_ssi_energycaluculatormember_receives_ssi"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EnergyCaluculatorMember",
            new_name="EnergyCalculatorMember",
        ),
        migrations.RenameModel(
            old_name="EnergyCaluculatorScreen",
            new_name="EnergyCalculatorScreen",
        ),
    ]
