# Generated by Django 4.2.15 on 2025-01-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "screener",
            "0096_rename_energycaluculatormember_energycalculatormember_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="path",
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
