# Generated by Django 4.2.15 on 2025-02-07 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0094_screen_has_ncwap"),
        (
            "screener",
            "0096_rename_energycaluculatormember_energycalculatormember_and_more",
        ),
    ]

    operations = []
