# Generated by Django 4.2.15 on 2025-02-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0097_merge_20250207_1915"),
        ("screener", "0097_screen_path"),
    ]

    operations = []
