# Generated by Django 4.2.15 on 2025-02-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0098_merge_0097_merge_20250207_1915_0097_screen_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="energycalculatormember",
            name="disabled",
        ),
    ]
