# Generated by Django 4.2.15 on 2025-03-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0100_screen_has_ncscca"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_ccfa",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="has_csfp",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="has_ma_eaedc",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="has_ma_macftc",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="has_ma_maeitc",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="has_ma_mbta",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="has_ma_ssp",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
