# Generated by Django 4.2.15 on 2025-04-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0102_insurance_mass_health"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_co_andso",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
