# Generated by Django 4.2.15 on 2025-04-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0102_insurance_mass_health"),
    ]

    operations = [
        migrations.RenameField(
            model_name="screen",
            old_name="has_ccfa",
            new_name="has_ccdf",
        ),
    ]
