# Generated by Django 4.2.15 on 2025-04-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0103_rename_has_ccfa_screen_has_ccdf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="screen",
            old_name="has_ma_macftc",
            new_name="has_ma_macfc",
        ),
    ]
