# Generated by Django 4.2.15 on 2025-04-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0104_rename_has_ma_macftc_screen_has_ma_macfc"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="needs_veteran_services",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
