# Generated by Django 4.2.15 on 2025-04-14 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0103_screen_has_co_andso"),
        ("screener", "0105_screen_needs_veteran_services"),
    ]

    operations = []
