# Generated by Django 4.2.15 on 2025-04-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0106_merge_20250414_2227"),
    ]

    operations = [
        migrations.AddField(
            model_name="whitelabel",
            name="state_code",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
