# Generated by Django 4.2.15 on 2025-04-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0106_merge_20250414_2227"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_aca",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
