# Generated by Django 4.2.15 on 2025-04-30 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0107_screen_has_aca"),
        ("screener", "0107_whitelabel_state_code"),
    ]

    operations = []
