# Generated by Django 4.2.15 on 2025-05-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0108_merge_0107_screen_has_aca_0107_whitelabel_state_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="energycalculatorscreen",
            name="has_old_car",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
