# Generated by Django 4.2.15 on 2025-05-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0109_energycalculatorscreen_has_old_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_co_care",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
