# Generated by Django 4.2.15 on 2025-05-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0110_screen_has_co_care"),
    ]

    operations = [
        migrations.AddField(
            model_name="energycalculatormember",
            name="medical_equipment",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
