# Generated by Django 4.2.11 on 2025-01-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0111_energycalculatormember_medical_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_cfhc",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="has_shitc",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
