# Generated by Django 4.2.15 on 2025-06-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0112_screen_has_connectforhealth_screen_has_seniorhousingincome"),
    ]

    operations = [
        migrations.AddField(
            model_name="energycalculatorscreen",
            name="electric_provider_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="energycalculatorscreen",
            name="gas_provider_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
