# Generated by Django 4.2.18 on 2025-08-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0113_energycalculatorscreen_electric_provider_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="utm_campaign",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="utm_content",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="utm_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="utm_medium",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="utm_source",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="utm_term",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
