# Generated by Django 4.2.28 on 2026-09-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0164_householdmember_was_in_foster_care'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitysnapshot',
            name='had_external_api_failure',
            field=models.BooleanField(default=False),
        ),
    ]
