# Generated by Django 4.2.14 on 2024-07-25 17:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0084_screen_has_fatc"),
        ("validations", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="validation",
            unique_together={("screen", "program_name")},
        ),
    ]
