eligible_zipcode = [
    "Adams County",
    "Alamosa County",
    "Arapahoe County",
    "Archuleta County",
    "Bent County",
    "Boulder County",
    "Chaffee County",
    "Conejos County",
    "Costilla County",
    "Delta County",
    "Denver County",
    "Eagle County",
    "El Paso County",
    "Fremont County",
    "Garfield County",
    "Huerfano County",
    "Jefferson County",
    "La Plata County",
    "Lake County",
    "Larimer County",
    "Las Animas County",
    "Lincoln County",
    "Logan County",
    "Mesa County",
    "Moffat County",
    "Montezuma County",
    "Montrose County",
    "Morgan County",
    "Otero County",
    "Prowers County",
    "Pueblo County",
    "Rio Grande County",
    "Saguache County",
    "Summit County",
    "Teller County",
    "Washington County",
    "Weld County",
    "Yuma County",
]
