# Generated by Django 4.0.5 on 2022-08-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tcpa_consent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
