# Generated by Django 4.0.5 on 2022-08-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_cell_alter_user_email_alter_user_screen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='screen',
        ),
    ]
