# Generated by Django 4.0.5 on 2022-09-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_alter_user_cell_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="send_offers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="send_updates",
            field=models.BooleanField(default=False),
        ),
    ]
