# Generated by Django 4.1.5 on 2023-02-02 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0010_user_language_code"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
