# Generated by Django 4.0.5 on 2023-02-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_id',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
