# Generated by Django 4.2.15 on 2025-02-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0099_remove_energycalculatormember_disabled"),
        ("authentication", "0012_user_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="white_labels",
            field=models.ManyToManyField(blank=True, related_name="admins", to="screener.whitelabel"),
        ),
    ]
