# Generated by Django 4.2.15 on 2025-03-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_user_white_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="explicit_tcpa_consent",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="tcpa_consent",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
