# Generated by Django 4.2.15 on 2024-10-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_squashed_0004_alter_link_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="status_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="hash",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
