# Generated by Django 4.2.15 on 2024-10-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0005_link_status_code_alter_link_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="valid_status_code",
            field=models.BooleanField(default=False),
        ),
    ]
