# Generated by Django 4.0.5 on 2022-07-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_alter_program_estimated_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='legal_status_required',
            field=models.CharField(max_length=120),
        ),
    ]
