# Generated by Django 4.0.5 on 2022-08-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0008_alter_program_legal_status_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="value_type",
            field=models.CharField(default="non-discretionary", max_length=120),
            preserve_default=False,
        ),
    ]
