# Generated by Django 4.0.5 on 2022-12-08 22:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0017_navigator_navigatortranslation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigatortranslation",
            name="cell",
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
