# Generated by Django 4.0.5 on 2022-12-08 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0019_rename_cell_navigatortranslation_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigatortranslation',
            name='program',
        ),
    ]
