# Generated by Django 4.0.5 on 2022-12-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0020_remove_navigatortranslation_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigatortranslation",
            name="program",
            field=models.ManyToManyField(
                related_name="navigator", to="programs.program"
            ),
        ),
    ]
