# Generated by Django 4.0.5 on 2022-12-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0022_remove_navigatortranslation_assistance_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigator',
            name='assistance_link',
            field=models.CharField(blank=True, max_length=320),
        ),
    ]
