# Generated by Django 4.0.5 on 2022-12-09 17:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0025_remove_navigatortranslation_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigator',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='navigatortranslation',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None),
            preserve_default=False,
        ),
    ]
