# Generated by Django 4.0.5 on 2023-01-30 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0029_programtranslation_catagory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="programtranslation",
            old_name="catagory",
            new_name="category",
        ),
    ]
