# Generated by Django 4.0.5 on 2023-03-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0032_urgentneedfunction_urgentneed_functions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urgentneed",
            name="functions",
            field=models.ManyToManyField(blank=True, related_name="function", to="programs.urgentneedfunction"),
        ),
    ]
