# Generated by Django 4.0.5 on 2023-05-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0033_alter_urgentneed_functions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgentneedtranslation',
            name='link',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
