# Generated by Django 4.0.5 on 2023-09-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0043_auto_20230906_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='legal_status_required_1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='name_abbreviated_1',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
