# Generated by Django 4.0.5 on 2023-09-06 15:51

from django.db import migrations


def other_data_migrations(apps, _):
    Program = apps.get_model("programs", "Program")

    non_translated_fields = ("active", "legal_status_required", "name_abbreviated")
    for program in Program.objects.all():
        for field in non_translated_fields:
            setattr(program, field + "_1", getattr(program, field))
        program.save()


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0044_program_legal_status_required_1_and_more"),
    ]

    operations = [migrations.RunPython(other_data_migrations)]
