# Generated by Django 4.0.5 on 2023-09-06 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0045_auto_20230906_0951"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProgramTranslation",
        ),
    ]
