# Generated by Django 4.0.5 on 2023-09-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0056_urgentneedcategory_remove_urgentneed_type_short_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urgentneedcategory',
            options={'verbose_name_plural': 'Urgent Need Categories'},
        ),
        migrations.AlterField(
            model_name='urgentneed',
            name='type_short',
            field=models.ManyToManyField(related_name='urgent_needs', to='programs.urgentneedcategory'),
        ),
    ]
