# Generated by Django 4.2.6 on 2023-10-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0059_alter_program_legal_status_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigator",
            name="program",
            field=models.ManyToManyField(
                blank=True, related_name="navigator", to="programs.program"
            ),
        ),
    ]
