# Generated by Django 4.2.6 on 2023-12-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0060_alter_navigator_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="referrer",
            name="remove_programs",
            field=models.ManyToManyField(
                blank=True, related_name="removed_programs", to="programs.program"
            ),
        ),
    ]
