# Generated by Django 4.2.6 on 2024-01-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0004_translation_no_auto"),
        ("programs", "0061_referrer_remove_programs"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="documents",
            field=models.ManyToManyField(
                blank=True,
                related_name="program_documents",
                to="translations.translation",
            ),
        ),
    ]
