# Generated by Django 4.2.6 on 2024-01-22 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0004_translation_no_auto"),
        ("programs", "0061_referrer_remove_programs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=265)),
                (
                    "text",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="translations.translation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="program",
            name="documents",
            field=models.ManyToManyField(blank=True, related_name="program_documents", to="programs.document"),
        ),
    ]
