# Generated by Django 4.2.6 on 2024-01-26 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0063_navigatorcounty_delete_navigatorcounties_and_more"),
        ("programs", "0063_remove_document_name_document_external_name"),
    ]

    operations = []
