# Generated by Django 4.2.6 on 2024-01-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0064_merge_20240126_1001"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="low_confidence",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="urgentneed",
            name="low_confidence",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
