# Generated by Django 4.2.6 on 2024-01-30 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0004_translation_no_auto"),
        ("programs", "0066_auto_20240130_1146"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="warning",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="program_warning",
                to="translations.translation",
            ),
        ),
        migrations.AlterField(
            model_name="urgentneed",
            name="warning",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="urgent_need_warning",
                to="translations.translation",
            ),
        ),
    ]
