# Generated by Django 4.2.6 on 2024-01-30 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0065_program_low_confidence_urgentneed_low_confidence"),
        ("programs", "0067_alter_program_warning_alter_urgentneed_warning"),
    ]

    operations = []
