# Generated by Django 4.2.11 on 2024-05-06 18:17
from django.db import migrations


def add_estimated_value(apps, schema_editor):
    Program = apps.get_model("programs", "Program")
    Translation = apps.get_model("translations", "Translation")

    for program in Program.objects.all():
        translation = Translation.objects.add_translation(
            f"programs.{program.name_abbreviated}-{program.id}_estimated_value", ""
        )
        Program.objects.filter(pk=program.id).update(estimated_value=translation.id)


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0069_program_estimated_value"),
        ("translations", "0004_translation_no_auto"),
    ]

    operations = [migrations.RunPython(add_estimated_value, migrations.RunPython.noop)]
