# Generated by Django 4.2.11 on 2024-05-21 17:27
from django.db import migrations


def add_website_description(apps, schema_editor):
    Program = apps.get_model("programs", "Program")
    Translation = apps.get_model("translations", "Translation")

    for program in Program.objects.all():
        translation = Translation.objects.add_translation(
            f"programs.{program.name_abbreviated}-{program.id}_website_description", "[PLACEHOLDER]"
        )
        Program.objects.filter(pk=program.id).update(website_description=translation.id)


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0072_program_website_description"),
        ("translations", "0004_translation_no_auto"),
    ]

    operations = [migrations.RunPython(add_website_description, migrations.RunPython.noop)]
