# Generated by Django 4.2.11 on 2024-05-21 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0004_translation_no_auto"),
        ("programs", "0074_alter_program_website_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="urgentneed",
            name="website_description",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="urgent_website_description",
                to="translations.translation",
            ),
        ),
    ]
