# Generated by Django 4.2.11 on 2024-05-21 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0004_translation_no_auto"),
        ("programs", "0076_auto_20240521_2055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urgentneed",
            name="website_description",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="urgent_website_description",
                to="translations.translation",
            ),
        ),
    ]
