# Generated by Django 4.2.11 on 2024-06-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0077_alter_urgentneed_website_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="federalpoverylimit",
            name="additional",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
