# Generated by Django 4.2.14 on 2024-07-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0078_federalpoverylimit_additional"),
    ]

    operations = [
        migrations.AddField(
            model_name="federalpoverylimit",
            name="pe_period",
            field=models.CharField(default=2024, max_length=32),
            preserve_default=False,
        ),
    ]
