# Generated by Django 4.2.14 on 2024-07-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0078_federalpoverylimit_additional"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigatorLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name="navigator",
            name="languages",
            field=models.ManyToManyField(blank=True, related_name="navigator", to="programs.navigatorlanguage"),
        ),
    ]
