# Generated by Django 4.2.14 on 2024-07-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0079_navigatorlanguage_navigator_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigatorlanguage",
            name="code",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
