# Generated by Django 4.2.14 on 2024-08-02 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0079_federalpoverylimit_pe_period"),
        ("programs", "0080_alter_navigatorlanguage_code"),
    ]

    operations = []
