# Generated by Django 4.2.14 on 2024-08-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0081_merge_20240802_1619"),
    ]

    operations = [
        migrations.RenameField(
            model_name="federalpoverylimit",
            old_name="pe_period",
            new_name="period",
        ),
        migrations.RemoveField(
            model_name="federalpoverylimit",
            name="additional",
        ),
        migrations.RemoveField(
            model_name="federalpoverylimit",
            name="has_1_person",
        ),
        migrations.RemoveField(
            model_name="federalpoverylimit",
            name="has_2_people",
        ),
        migrations.RemoveField(
            model_name="federalpoverylimit",
            name="has_3_people",
        ),
        migrations.RemoveField(
            model_name="federalpoverylimit",
            name="has_4_people",
        ),
        migrations.RemoveField(
            model_name="federalpoverylimit",
            name="has_5_people",
        ),
        migrations.RemoveField(
            model_name="federalpoverylimit",
            name="has_6_people",
        ),
        migrations.RemoveField(
            model_name="federalpoverylimit",
            name="has_7_people",
        ),
        migrations.RemoveField(
            model_name="federalpoverylimit",
            name="has_8_people",
        ),
    ]
