# Generated by Django 4.2.14 on 2024-08-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0082_warningmessage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NavigatorCounty",
            new_name="County",
        ),
        migrations.AddField(
            model_name="warningmessage",
            name="counties",
            field=models.ManyToManyField(blank=True, related_name="warning_message", to="programs.county"),
        ),
    ]
