# Generated by Django 4.2.14 on 2024-08-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0084_alter_warningmessage_counties_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="navigator",
            old_name="program",
            new_name="programs",
        ),
        migrations.RenameField(
            model_name="warningmessage",
            old_name="program",
            new_name="programs",
        ),
    ]
