# Generated by Django 4.2.14 on 2024-08-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0082_rename_pe_period_federalpoverylimit_period_and_more"),
        ("programs", "0085_rename_program_navigator_programs_and_more"),
    ]

    operations = []
