# Generated by Django 4.2.14 on 2024-09-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0086_merge_20240827_1541"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="warning",
        ),
    ]
