# Generated by Django 4.2.14 on 2024-09-24 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0004_translation_no_auto"),
        ("programs", "0087_remove_program_warning"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calculator", models.CharField(max_length=120)),
                (
                    "external_name",
                    models.CharField(blank=True, max_length=120, null=True, unique=True),
                ),
                ("field", models.CharField(max_length=64)),
                ("active", models.BooleanField(blank=True, default=True)),
                (
                    "counties",
                    models.ManyToManyField(related_name="translation_overrides", to="programs.county"),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation_overrides",
                        to="programs.program",
                    ),
                ),
                (
                    "translation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="translation_overrides",
                        to="translations.translation",
                    ),
                ),
            ],
        ),
    ]
