# Generated by Django 4.2.15 on 2024-10-09 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0004_translation_no_auto"),
        ("programs", "0089_alter_translationoverride_counties_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_name",
                    models.CharField(
                        blank=True, max_length=120, null=True, unique=True
                    ),
                ),
                ("calculator", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "description",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="program_category_description",
                        to="translations.translation",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="program_category_name",
                        to="translations.translation",
                    ),
                ),
            ],
        ),
    ]
