# Generated by Django 4.2.15 on 2024-10-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0090_programcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="category_v2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="programs",
                to="programs.programcategory",
            ),
        ),
    ]
