# Generated by Django 4.2.15 on 2024-10-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0091_program_category_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="programcategory",
            name="icon",
            field=models.CharField(default="housing", max_length=120),
            preserve_default=False,
        ),
    ]
