# Generated by Django 4.2.15 on 2024-10-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0092_programcategory_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="category",
        ),
    ]
