# Generated by Django 4.2.15 on 2024-10-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0093_remove_program_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="program",
            old_name="category_v2",
            new_name="category",
        ),
    ]
