# Generated by Django 4.2.15 on 2024-10-30 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0004_translation_no_auto"),
        ("programs", "0094_rename_category_v2_program_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="link_text",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_link_text",
                to="translations.translation",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="link_url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_link_url",
                to="translations.translation",
            ),
        ),
    ]
