# Generated by Django 4.2.15 on 2024-11-07 17:21

from django.db import migrations
from integrations.services.google_translate.integration import Translate


def add_apply_button_description(apps, schema_editor):
    Program = apps.get_model("programs", "Program")
    Translation = apps.get_model("translations", "Translation")

    for program in Program.objects.all():
        translation = Translation.objects.add_translation(
            f"programs.{program.name_abbreviated}-{program.id}_apply_button_description", "Apply Online"
        )

        auto_translations = Translate().bulk_translate(["__all__"], ["Apply Online"])["Apply Online"]

        for [language, auto_text] in auto_translations.items():
            Translation.objects.edit_translation_by_id(translation.id, language, auto_text, False)
            
        Program.objects.filter(pk=program.id).update(apply_button_description=translation.id)

class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0095_program_apply_button_description"),
        ("translations", "0004_translation_no_auto"),
    ]

    operations = [migrations.RunPython(add_apply_button_description, migrations.RunPython.noop)]
