# Generated by Django 4.2.15 on 2024-11-05 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0088_alter_screen_white_label"),
        ("programs", "0095_county_white_label_document_white_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="county",
            name="white_label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counties",
                to="screener.whitelabel",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="white_label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="screener.whitelabel",
            ),
        ),
        migrations.AlterField(
            model_name="navigator",
            name="white_label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="navigators",
                to="screener.whitelabel",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="white_label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="screener.whitelabel",
            ),
        ),
        migrations.AlterField(
            model_name="programcategory",
            name="white_label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="program_categories",
                to="screener.whitelabel",
            ),
        ),
        migrations.AlterField(
            model_name="referrer",
            name="white_label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrers",
                to="screener.whitelabel",
            ),
        ),
        migrations.AlterField(
            model_name="translationoverride",
            name="white_label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translation_overrides",
                to="screener.whitelabel",
            ),
        ),
        migrations.AlterField(
            model_name="urgentneed",
            name="white_label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="urgent_needs",
                to="screener.whitelabel",
            ),
        ),
        migrations.AlterField(
            model_name="urgentneedcategory",
            name="white_label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="urgent_need_categories",
                to="screener.whitelabel",
            ),
        ),
        migrations.AlterField(
            model_name="warningmessage",
            name="white_label",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warning_messages",
                to="screener.whitelabel",
            ),
        ),
    ]
