# Generated by Django 4.2.15 on 2024-11-06 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0004_translation_no_auto"),
        ("programs", "0096_document_link_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="link_text",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_link_text",
                to="translations.translation",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="link_url",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_link_url",
                to="translations.translation",
            ),
        ),
    ]
