# Generated by Django 4.2.15 on 2024-11-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "programs",
            "0096_alter_county_white_label_alter_document_white_label_and_more",
        ),
        ("programs", "0097_document_link_required"),
    ]

    operations = []
