# Generated by Django 4.2.15 on 2024-11-08 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0097_alter_program_apply_button_description"),
        ("programs", "0098_merge_20241108_1701"),
    ]

    operations = []
