# Generated by Django 4.2.15 on 2024-12-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0099_merge_20241108_1521"),
    ]

    operations = [
        migrations.AddField(
            model_name="warningmessage",
            name="legal_statuses",
            field=models.ManyToManyField(blank=True, related_name="warning_messages", to="programs.legalstatus"),
        ),
    ]
