# Generated by Django 4.2.15 on 2025-02-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0100_warningmessage_legal_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="required_programs",
            field=models.ManyToManyField(blank=True, related_name="dependent_programs", to="programs.program"),
        ),
    ]
