# Generated by Django 4.2.15 on 2025-02-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0100_warningmessage_legal_statuses"),
    ]

    operations = [
        migrations.RenameField(
            model_name="program",
            old_name="fpl",
            new_name="year",
        ),
    ]
