# Generated by Django 4.2.15 on 2025-02-07 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0101_program_required_programs"),
        ("programs", "0101_rename_fpl_program_year"),
    ]

    operations = []
