# Generated by Django 4.2.15 on 2025-02-25 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0102_merge_20250207_2059"),
    ]

    operations = [
        migrations.AddField(
            model_name="urgentneed",
            name="year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="urgent_need",
                to="programs.federalpoverylimit",
            ),
        ),
    ]
