# Generated by Django 4.2.15 on 2025-03-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0104_urgentneed_counties"),
    ]

    operations = [
        migrations.AddField(
            model_name="programcategory",
            name="tax_category",
            field=models.BooleanField(default=False),
        ),
    ]
