# Generated by Django 4.2.15 on 2025-04-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0105_programcategory_tax_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="value_format",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
