# Generated by Django 4.2.15 on 2025-04-30 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0105_programcategory_tax_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="urgentneedcategory",
            name="white_label",
        ),
    ]
