# Generated by Django 4.2.15 on 2025-05-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0106_remove_urgentneedcategory_white_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="programcategory",
            name="priority",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
