# Generated by Django 4.2.15 on 2025-05-20 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0004_translation_no_auto"),
        ("programs", "0107_programcategory_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="warningmessage",
            name="link_text",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warning_message_link_text",
                to="translations.translation",
            ),
        ),
        migrations.AddField(
            model_name="warningmessage",
            name="link_url",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warning_message_link_url",
                to="translations.translation",
            ),
        ),
    ]
