# Generated by Django 4.2.15 on 2025-05-22 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0106_program_value_format"),
        ("programs", "0107_programcategory_priority"),
    ]

    operations = []
