# Generated by Django 4.2.15 on 2025-05-20 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0004_translation_no_auto"),
        ("programs", "0109_warningmessage_default_link_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warningmessage",
            name="link_text",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warning_message_link_text",
                to="translations.translation",
            ),
        ),
        migrations.AlterField(
            model_name="warningmessage",
            name="link_url",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warning_message_link_url",
                to="translations.translation",
            ),
        ),
    ]
