# Generated by Django 4.2.18 on 2025-05-29 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0108_merge_20250522_1945"),
        ("programs", "0110_warningmessage_link_text_fields_no_null"),
    ]

    operations = []
