# Generated by Django 4.2.15 on 2025-06-07 03:49

from django.db import migrations, models
import django.db.models.deletion


def populate_icon_names(apps, _):
    CategoryIconName = apps.get_model("programs", "CategoryIconName")

    icon_names = [
        "veterans resources",
        "civil legal needs",
        "low-cost dental care",
        "job resources",
        "family planning",
        "child's development",
        "behavioral health",
        "managing housing costs",
        "baby supplies",
        "food or groceries",
        "talk",
        "low_fuel",
        "heat",
        "light_bulb",
        "water_heater",
        "child_care",
        "cash",
        "tax_credit",
        "transportation",
        "health_care",
        "food",
        "housing",
    ]

    for name in icon_names:
        CategoryIconName.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0004_translation_no_auto"),
        ("screener", "0112_screen_has_connectforhealth_screen_has_seniorhousingincome"),
        ("programs", "0111_merge_20250529_2037"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryIconName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name="urgentneed",
            name="type",
        ),
        migrations.CreateModel(
            name="UrgentNeedType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="urgent_need_type_icon",
                        to="programs.categoryiconname",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="urgent_need_type_name",
                        to="translations.translation",
                    ),
                ),
                (
                    "white_label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urgent_need_types",
                        to="screener.whitelabel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="urgentneed",
            name="category_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="urgent_needs",
                to="programs.urgentneedtype",
            ),
        ),
        migrations.RunPython(populate_icon_names, migrations.RunPython.noop),
    ]
