# Generated by Django 4.2.15 on 2025-06-07 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0112_categoryiconname_remove_urgentneed_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programcategory",
            name="icon",
        ),
        migrations.AddField(
            model_name="programcategory",
            name="icon",
            field=models.ForeignKey(
                to="programs.categoryiconname",
                on_delete=django.db.models.deletion.SET_NULL,
                blank=True,
                null=True,
                related_name="program_categories_icon",
            ),
        ),
    ]
