# Generated by Django 4.2.18 on 2025-07-11 14:11

from django.db import migrations, models


def updated_urgent_need_type_external_name(apps, schema_editor):
    UrgentNeedType = apps.get_model("programs", "UrgentNeedType")
    Translation = apps.get_model("translations", "Translation")

    # populates the external_name field
    for urgent_need_type in UrgentNeedType.objects.all():
        if urgent_need_type.external_name:
            continue
        wl = urgent_need_type.white_label.code
        text = urgent_need_type.name.text.replace(" ", "_").replace("'", "").replace(",", "").lower()
        if wl == "co":
            urgent_need_type.external_name = text
        else:
            urgent_need_type.external_name = f"{wl}_{text}"
        urgent_need_type.save()

    # updates urgentneedtype name field labels
    for urgent_need_type in UrgentNeedType.objects.all():
        if not urgent_need_type.external_name:
            continue

        new_label = f"urgent_need_type.{urgent_need_type.external_name}_{urgent_need_type.id}-name"
        try:
            translation = Translation.objects.get(label=urgent_need_type.name.label)
            translation.label = new_label
            translation.save()
        except Translation.DoesNotExist:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0114_alter_categoryiconname_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="urgentneedtype",
            name="external_name",
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.RunPython(updated_urgent_need_type_external_name, migrations.RunPython.noop),
    ]
