# Generated by Django 4.2.22 on 2025-08-01 16:49

from django.db import migrations


def update_category_icon_names(apps, _):
    CategoryIconName = apps.get_model("programs", "CategoryIconName")

    name_mapping = {
        "food or groceries": "food_groceries",
        "baby supplies": "baby_supplies",
        "managing housing costs": "managing_housing",
        "behavioral health": "behavioral_health",
        "child's development": "child_development",
        "family planning": "family_planning",
        "job resources": "job_resources",
        "low-cost dental care": "dental_care",
        "civil legal needs": "legal_services",
        "veterans resources": "veteran_services",
    }

    for old_name, new_name in name_mapping.items():
        try:
            # Get records to update (to check if they exist)
            records = CategoryIconName.objects.filter(name=old_name)
            count = records.count()

            # Update records
            if count > 0:
                records.update(name=new_name)

        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0115_urgentneedtype_external_name"),
    ]

    operations = [
        migrations.RunPython(update_category_icon_names, migrations.RunPython.noop),
    ]
