# Generated by Django 4.2.28 on 2026-09-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0174_consolidate_missed_program_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fpl', to='programs.federalpoverylimit'),
        ),
    ]
