# Generated by Django 4.2.28 on 2026-05-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0175_seed_dynamic_fpl_rows"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="year_type",
            field=models.CharField(
                choices=[
                    ("hardcoded", "Hardcoded"),
                    ("fiscal_year", "Fiscal Year"),
                    ("calendar_year", "Calendar Year"),
                ],
                default="hardcoded",
                max_length=32,
            ),
        ),
    ]
