# Generated by Django 4.0.5 on 2023-09-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
