# Generated by Django 4.0.5 on 2023-10-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0003_alter_translation_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="no_auto",
            field=models.BooleanField(default=False),
        ),
    ]
