# Generated by Django 4.2.15 on 2025-07-18 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("translations", "0004_translation_no_auto"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTranslation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                ("active", models.BooleanField(default=True)),
                ("no_auto", models.BooleanField(default=False)),
                ("label", models.CharField(db_index=True, max_length=128)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "affected_language",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("original_text", models.TextField(blank=True, null=True)),
                ("changed_text", models.TextField(blank=True, null=True)),
                ("edit_type", models.BooleanField(blank=True, null=True)),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical translation",
                "verbose_name_plural": "historical translations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
