# Generated by Django 4.2.15 on 2025-08-05 17:49

from django.db import migrations


def move_zh_to_zh_hans(apps, _):
    Translation = apps.get_model("translations", "Translation")
    translations = Translation.objects.prefetch_related("translations").all()
    try:
        for translation in translations:
            for language in translation.translations.all():
                if language.language_code == "zh":
                    translation.set_current_language("zh-hans")
                    translation.text = language.text
                    translation.save()

                    language.delete()
    except Exception as e:
        print(f"Error: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0005_historicaltranslation"),
    ]

    operations = [
        migrations.RunPython(move_zh_to_zh_hans, migrations.RunPython.noop),
    ]
