name: Auto-Draft New PRs

on:
  pull_request:
    types: [opened]

jobs:
  mark-as-draft:
    name: Convert to draft
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Mark as draft
        uses: voiceflow/draft-pr@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}